images:
  image:
    repository: wabayang/jelu
    tag: "0.88.2@sha256:aa5878664e4100189c0e67635f56fd27066aab2f0cdc2e835cbc641d87b3176c"

consts:
  jelu_container_name: jelu
  internal_web_port: 11111
  database_path: /database
  files_images_path: /files/images
  files_imports_path: /files/imports
