app_version: 0.11.5
capabilities: []
categories:
- ai
changelog_url: https://github.com/open-webui/open-terminal/releases
date_added: '2026-03-03'
description: Open Terminal is a lightweight, self-hosted terminal that gives AI agents
  and automation tools a dedicated environment to run commands, manage files, and
  execute code all through a simple API.
home: https://github.com/open-webui/open-terminal
host_mounts: []
icon: https://media.sys.truenas.net/apps/open-terminal/icons/icon.svg
keywords:
- ai
- llm
- open-terminal
- open-webui
lib_version: 2.2.6
lib_version_hash: 481cac7a3f4a590dd8e48f8497a0c10169691bc85186cf022e0e6192436e78eb
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: open-terminal
run_as_context:
- description: Container [open-terminal] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/open-webui/open-terminal
title: Open Terminal
train: community
version: 1.0.4
