resources:
  limits:
    cpus: 2.0
    memory: 4096

teslamate:
  db_password: test-teslamate-db-password
  encryption_key: test-encryption-key-for-teslamate
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  disable_mqtt: true
  additional_envs: []
  enable_api: false
  api_token: ""

network:
  web_port:
    bind_mode: published
    port_number: 30411
  api_port:
    bind_mode: published
    port_number: 30410

ix_volumes:
  test_teslamate_import: /opt/tests/mnt/teslamate/import
  test_teslamate_postgres: /opt/tests/mnt/teslamate/postgres

storage:
  import_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: test_teslamate_import
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: test_teslamate_postgres
      create_host_path: true
  additional_storage: []
