#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "collabora": {
            "server_name": config["collaboraConfig"]["serverName"],
            "enable_webui": config["collaboraConfig"]["enableWebUI"],
            "username": config["collaboraConfig"].get("username", ""),
            "password": config["collaboraConfig"].get("password", ""),
            "aliasgroup1": config["collaboraConfig"]["aliasGroup1"],
            "dictionaries": config["collaboraConfig"]["dictionaries"],
            "extra_params": config["collaboraConfig"]["extraParams"],
            "additional_envs": config["collaboraConfig"].get("additionalEnvs", []),
        },
        "network": {
            "web_port": config["collaboraNetwork"]["webPort"],
            "certificate_id": config["collaboraNetwork"].get("certificateID"),
        },
        "storage": {
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["collaboraStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
