app_version: 2026.9.3
capabilities: []
categories:
- networking
changelog_url: https://developers.cloudflare.com/changelog/product/mesh/
date_added: '2026-09-25'
description: Cloudflare Mesh connects your private networks to Cloudflare using the
  Cloudflare One Client.
home: https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-mesh/
host_mounts: []
icon: https://media.sys.truenas.net/apps/cloudflare-mesh/icons/icon.svg
keywords:
- network
- cloudflare
- mesh
lib_version: 2.3.4
lib_version_hash: 2e3a8847308fb2eb0da046018f287c73822c094b5950a10377c3235794ff1242
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: cloudflare-mesh
run_as_context:
- description: Container [cloudflare-mesh] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://apps.truenas.com/catalog/cloudflare-mesh_community/
- https://developers.cloudflare.com/cloudflare-one/networks/connectors/cloudflare-mesh/
- https://hub.docker.com/r/cloudflare/mesh
title: Cloudflare Mesh
train: community
version: 1.0.0
