images:
  image:
    repository: dxflrs/garage
    tag: "v2.4.1@sha256:9c96caa2612d3411acc5b0e6701fb238dbfba33e533a6d7d3d811a4b12d0d020"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  web_image:
    repository: khairul169/garage-webui
    tag: "1.1.0@sha256:17c793551873155065bf9a022dabcde874de808a1f26e648d4b82e168806439c"
  toml_image:
    repository: ghcr.io/tomwright/dasel
    tag: "2.8.1@sha256:e2c9019e3a0081b88103cf45bea482eea1f2863e65e7de72a57b2bc9c3a57a4b"

consts:
  garage_container_name: garage
  config_container_name: config
  perms_container_name: permissions
  web_container_name: web

  config_path: /var/lib/garage/config
  metadata_path: /var/lib/garage/meta
  data_path: /var/lib/garage/data
  metadata_snapshots_path: /var/lib/garage/snapshots
