images:
  image:
    repository: ghcr.io/bookorbit/bookorbit
    tag: "3.1.0@sha256:78b6eac18306eb7eba0dbf6592ecdee01b15f24de9a941cb853db4a0232d7999"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  postgres_18_image:
    repository: pgvector/pgvector
    tag: "0.8.6-pg18-trixie@sha256:78bf48b801e792f99e3ac62b5036fd3876e9be48afda16c1e331af1c75ceb2ff"
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: "1.2.17@sha256:8a905af2f0cde30e19e41f0a2db6f69154818532f50e7de923f0d7977c1c9c38"

consts:
  bookorbit_container_name: bookorbit
  postgres_container_name: postgres
  perms_container_name: permissions
  db_user: bookorbit
  db_name: bookorbit
  data_path: /data
  book_drop_path: /books-drop
