app_version: 1.0.2
capabilities:
- description: Odysseus is able to change file ownership arbitrarily
  name: CHOWN
- description: Odysseus is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Odysseus is able to bypass permission checks for file operations
  name: FOWNER
- description: Odysseus is able to change group ID of processes
  name: SETGID
- description: Odysseus is able to change user ID of processes
  name: SETUID
categories:
- ai
changelog_url: ''
date_added: '2026-06-25'
description: Odysseus is a AI Chat tool with RAG, Deep Search, Web Search, Code editing,
  and more. Also includes image editor, task planning & email handling. Project was
  started by PewDiePie
home: https://pewdiepie-archdaemon.github.io/odysseus
host_mounts: []
icon: https://media.sys.truenas.net/apps/odysseus/icons/icon.svg
keywords:
- ai
- llm
- webui
- odysseus
- pewdiepie
lib_version: 2.3.7
lib_version_hash: acd86f2d8a0b26321eb73e42c799b5d55945f1c131eea4a3fb01e30844a5ec87
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: odysseus
run_as_context:
- description: Container [chromadb] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [odysseus] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://apps.truenas.com/catalog/odysseus_community/
- https://github.com/pewdiepie-archdaemon/odysseus
title: Odysseus
train: community
version: 1.0.1
