images:
  image:
    repository: qbsoon/odysseus-pewds
    tag: v1.0.0_5
  image-auth:
    repository: qbsoon/odysseus-pewds
    tag: v1.0.0_5-auth
  chromadb_image:
    repository: docker.io/chromadb/chroma
    tag: latest
  ntfy_image:
    repository: docker.io/binwiederhier/ntfy
    tag: v2.24
  searxng_image:
    repository: docker.io/searxng/searxng
    tag: 2026.5.31-7159b8aed
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  run_as_user: 568
  run_as_group: 568
  perms_container_name: "perms"
  data_path: "/app/data"
  logs_path: "/app/logs"
  ssh_path: "/app/.ssh"
  huggingface_path: "/app/.cache/huggingface"
  local_path: "/app/.local"
  chromadb_path: "/chroma/chroma"
  ntfy_path: "/var/cache/ntfy"
  searxng_path: "/etc/searxng"
