#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "npm": {
            "additional_envs": config["npmConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["npmID"].get("user", 568),
            "group": config["npmID"].get("group", 568),
        },
        "network": {
            "web_port": config["npmNetwork"].get("webPort", 32400),
            "http_port": config["npmNetwork"].get("httpPort", 32401),
            "https_port": config["npmNetwork"].get("httpsPort", 32402),
        },
        "storage": {
            "certs": migrate_storage_item(config["npmStorage"]["certs"]),
            "data": migrate_storage_item(config["npmStorage"]["data"]),
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
