app_version: 2.3.0
capabilities:
- description: Borg UI is able to change file ownership arbitrarily
  name: CHOWN
- description: Borg UI is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Borg UI is able to bypass permission checks for file operations
  name: FOWNER
- description: Borg UI is able to change group ID of processes
  name: SETGID
- description: Borg UI is able to change user ID of processes
  name: SETUID
- description: Borg UI is able to perform system administration operations
  name: SYS_ADMIN
categories:
- backup
changelog_url: https://github.com/karanhudia/borg-ui/releases
date_added: '2026-09-04'
description: Borg UI is a web interface for BorgBackup to run backups, browse and
  restore archives, manage repositories and schedules.
home: https://borgui.com
host_mounts:
- description: Fuse Device
  host_path: /dev/fuse
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/borg-ui/icons/icon.png
keywords:
- backup
- borg
- borgbackup
- restore
lib_version: 2.3.15
lib_version_hash: 418b1697e018a564438ced4d735f4ced3ea16cc9fa74971a6040e769c80a66e5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: borg-ui
run_as_context:
- description: Container [borg-ui] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots:
- https://media.sys.truenas.net/apps/borg-ui/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/borg-ui/screenshots/screenshot2.png
sources:
- https://apps.truenas.com/catalog/borg-ui_community/
- https://github.com/karanhudia/borg-ui
- https://hub.docker.com/r/ainullcode/borg-ui
title: Borg UI
train: community
version: 1.0.0
