app_version: 0.7.3
capabilities:
- description: ArchiveBox, Scheduler are able to change file ownership arbitrarily
  name: CHOWN
- description: ArchiveBox, Scheduler are able to bypass file permission checks
  name: DAC_OVERRIDE
- description: ArchiveBox, Scheduler are able to bypass permission checks for file
    operations
  name: FOWNER
- description: ArchiveBox, Scheduler are able to change group ID of processes
  name: SETGID
- description: ArchiveBox, Scheduler are able to change user ID of processes
  name: SETUID
categories:
- productivity
date_added: '2026-03-12'
description: ArchiveBox is a powerful, self-hosted internet archiving solution to
  collect, save, and view websites offline. Save pages as HTML, PDF, screenshots,
  WARC, and more.
home: https://archivebox.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/archivebox/icons/icon.svg
keywords:
- web
- internet
- bookmarks
- links
- rss
- archive
- archiving
- wayback
- preservation
- scraping
- chrome
lib_version: 2.2.8
lib_version_hash: 76b40b42163deb26edbad5f973f1bd69b68bd85625bcd8247545194d99b9f912
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: archivebox
run_as_context:
- description: Container [archivebox] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [scheduler] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [sonic] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/archivebox/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/archivebox/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/archivebox/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/archivebox/screenshots/screenshot4.png
sources:
- https://github.com/ArchiveBox/ArchiveBox
- https://archivebox.io
title: ArchiveBox
train: community
version: 1.0.0
