app_version: 0.7.3
capabilities: []
categories:
- productivity
date_added: '2026-03-11'
description: ArchiveBox is a powerful, self-hosted internet archiving solution to
  collect, save, and view websites offline. Save pages as HTML, PDF, screenshots,
  WARC, and more.
home: https://archivebox.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/archivebox/icons/icon.png
keywords:
- archiving
- bookmarks
- web
- wayback
- preservation
lib_version: 2.2.8
lib_version_hash: ""
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: archivebox
run_as_context:
- description: Container [archivebox] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://archivebox.io
- https://github.com/ArchiveBox/ArchiveBox
title: ArchiveBox
train: community
version: 1.0.0
