images:
  image:
    repository: archivebox/archivebox
    tag: 0.7.3
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  sonic_image:
    repository: archivebox/sonic
    tag: latest

consts:
  archivebox_container_name: archivebox
  scheduler_container_name: archivebox_scheduler
  sonic_container_name: sonic
  perms_container_name: permissions
