images:
  image:
    repository: archivebox/archivebox
    tag: 0.7.3
  sonic_image:
    repository: archivebox/sonic
    tag: latest

consts:
  archivebox_container_name: archivebox
  sonic_container_name: sonic
  perms_container_name: permissions
