images:
  image:
    repository: archivebox/archivebox
    tag: 0.9.50@sha256:5a2aa5f80e2d6e11637cd2feb7759b68b3e4122e8adab4fe7914fc5048fbe4c2
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  archivebox_container_name: archivebox
  perms_container_name: permissions
  data_path: /data
