#!/usr/bin/python3

import os
import sys
import yaml
import secrets


def migrate(values):
    if not values["dawarich"].get("redis_password"):
        values["dawarich"]["redis_password"] = secrets.token_urlsafe(16)[:16]
    values["storage"].pop("db_data", None)
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
