app_version: 3.54.0
capabilities: []
categories:
- financial
changelog_url: https://github.com/ghostfolio/ghostfolio/releases
date_added: '2026-08-11'
description: Open Source Wealth Management Software.
home: https://ghostfol.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/ghostfolio/icons/icon.svg
keywords:
- finance
lib_version: 2.3.9
lib_version_hash: a8673072613a14c3b5468881b4912f7bb4c789ed663c142e2e9aa0a12d7ed101
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ghostfolio
run_as_context:
- description: Container [ghostfolio] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/ghostfolio_community/
- https://github.com/ghostfolio/ghostfolio/
title: Ghostfolio
train: community
version: 1.0.8
