images:
  image:
    repository: tinymediamanager/tinymediamanager
    tag: "5.3.3@sha256:6f332431a2aedcc7c4f4e9604c3ee1f4d2f7427a532752cc2ed99024a4140829"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  tiny_media_manager_container_name: tiny-media-manager
  perms_container_name: permissions
  internal_web_port: 4000
