resources:
  limits:
    cpus: 2.0
    memory: 4096

hermes_agent:
  enable_basic_auth: true
  basic_auth_username: hermes
  basic_auth_password: hermes_password
  hmac_key: 89c49b325ba54ce7397ca192d2b43fc483437a3f20c692328083c79c9a767ed8
  gateway_key: 89c49b325ba54ce7397ca192d2b43fc483437a3f20c692328083c79c9a767ed8
  allow_all_users_access: true
  shm_size_mb: 64
  additional_envs: []

network:
  gateway_port:
    bind_mode: published
    port_number: 8080
  dashboard_port:
    bind_mode: published
    port_number: 8081
  webhook_port:
    bind_mode: published
    port_number: 8082

ix_volumes:
  data: /opt/tests/mnt/hermes-agent/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
