#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "passbolt": {
            "additional_envs": config["passboltConfig"].get("additionalEnvs", []),
            "db_password": get_value_from_secret(
                k8s_secrets, "mariadb-creds", "MARIADB_PASSWORD"
            ),
            "db_root_password": get_value_from_secret(
                k8s_secrets, "mariadb-creds", "MARIADB_ROOT_PASSWORD"
            ),
            "app_url": config["passboltConfig"]["appUrl"],
        },
        "network": {
            "web_port": config["passboltNetwork"].get("webPort", 30097),
            "certificate_id": config["passboltNetwork"].get("certificateId"),
        },
        "storage": {
            "gpg": migrate_storage_item(config["passboltStorage"]["gpg"]),
            "jwt": migrate_storage_item(config["passboltStorage"]["jwt"]),
            "mariadb_data": migrate_storage_item(
                config["passboltStorage"]["mariadbData"]
            ),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["passboltStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
