#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    new_csp = []
    for x in values["opencloud"].get("additional_csp", []):
        new_item = {"directive": x["directive"], "items": []}
        for i in x["items"]:
            if isinstance(i, str):
                new_item["items"].append({"value": i, "placeholder": ""})
            else:
                new_item["items"].append(i)
        new_csp.append(new_item)
    values["opencloud"]["additional_csp"] = new_csp
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
