images:
  image:
    repository: ghcr.io/tailscale/tailscale
    tag: "v1.102.5@sha256:c507f3a2a6ab1cabd8d809b98edeb41edbd5c3fb6ad9632ffd098b4c7d0b4065"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  tailscale_container_name: tailscale
  perms_container_name: permissions
  state_path: /var/lib/tailscale
  reserved_keys:
    - --advertise-exit-node
    - --accept-routes
    - --hostname
    - --authkey
    - --reset
