images:
  image:
    repository: collabora/code
    tag: "26.04.4.2.1@sha256:4e983196eb9878f339cc506c38c21f1cc3473bca3d6de883c5de08f9c0cc3a6c"
  nginx_image:
    repository: nginx
    tag: "1.31.6@sha256:908dc23e643a1447dbfb2e189ed268bfde6a51a5bf9a34d3dd3440a24f58ccf7"

consts:
  collabora_container_name: collabora
  nginx_container_name: nginx
  nginx_ssl_cert_path: /etc/certs/server.crt
  nginx_ssl_key_path: /etc/certs/server.key

  run_as_user: 1001
  run_as_group: 1001
