resources:
  limits:
    cpus: 2.0
    memory: 4096

run_as:
  user: 568
  group: 568

scarletx:
  additional_envs:
    - name: SCARLETX_TEST_MODE
      value: "1"

network:
  web_port:
    bind_mode: published
    port_number: 30970
    host_ips: []

labels: []

storage:
  config:
    type: host_path
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/scarletx-hostpath/config
  downloads:
    type: host_path
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/scarletx-hostpath/downloads
  media:
    type: host_path
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/scarletx-hostpath/media
  backups:
    type: host_path
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/scarletx-hostpath/backups
