TZ: Etc/UTC

clumoove:
  db_password: test_postgres_password_123
  redis_password: test_redis_password_123
  encryption_secret_key: test_encryption_secret_key_32_bytes_test
  jwt_secret_key: test_jwt_signing_key_32_bytes_test
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: "published"
    port_number: 8380
    host_ips: []

ix_volumes:
  storage: /opt/tests/mnt/clumoove/storage
  postgres_data: /opt/tests/mnt/clumoove/postgres_data
  redis_data: /opt/tests/mnt/clumoove/redis_data

storage:
  local_storage:
    type: "ix_volume"
    ix_volume_config:
      acl_enable: false
      dataset_name: "storage"
  postgres_data:
    type: "ix_volume"
    ix_volume_config:
      acl_enable: false
      dataset_name: "postgres_data"
  redis_data:
    type: "ix_volume"
    ix_volume_config:
      acl_enable: false
      dataset_name: "redis_data"

labels: []

resources:
  limits:
    cpus: 4
    memory: 4096
