#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "castopod": {
            "additional_envs": config["castopodConfig"].get("additionalEnvs", []),
            "db_password": get_value_from_secret(
                k8s_secrets, "mariadb-creds", "MARIADB_PASSWORD"
            ),
            "db_root_password": get_value_from_secret(
                k8s_secrets, "mariadb-creds", "MARIADB_ROOT_PASSWORD"
            ),
            "redis_password": get_value_from_secret(
                k8s_secrets, "redis-creds", "REDIS_PASSWORD"
            ),
            "analytics_salt": get_value_from_secret(
                k8s_secrets, "castopod-creds", "CP_ANALYTICS_SALT"
            ),
            "base_url": config["castopodConfig"]["baseUrl"],
            "web_timeout": config["castopodConfig"]["webTimeout"],
            "web_max_body_size": config["castopodConfig"]["webMaxBodySize"],
            "php_memory_limit": config["castopodConfig"]["phpMemoryLimit"],
            "enable_2fa": config["castopodConfig"]["enable2fa"],
            "disable_https_redirect": config["castopodConfig"]["disableHttpsRedirect"],
        },
        "network": {
            "web_port": config["castopodNetwork"].get("webPort", 30066),
        },
        "storage": {
            "data": migrate_storage_item(config["castopodStorage"]["data"]),
            "mariadb_data": migrate_storage_item(
                config["castopodStorage"]["mariadbData"]
            ),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["castopodStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
