#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "tdarr": {
            "internal_node": config["tdarrConfig"].get("internalNode", True),
            "node_name": config["tdarrConfig"].get("nodeName", "Tdarr"),
            "additional_envs": config["tdarrConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["tdarrID"].get("user", 568),
            "group": config["tdarrID"].get("group", 568),
        },
        "network": {
            "host_network": config["tdarrNetwork"].get("hostNetwork", False),
            "web_port": config["tdarrNetwork"].get("webPort", 30028),
            "server_port": config["tdarrNetwork"].get("serverPort", 30029),
        },
        "storage": {
            "configs": migrate_storage_item(config["tdarrStorage"]["configs"]),
            "server": migrate_storage_item(config["tdarrStorage"]["server"]),
            "logs": migrate_storage_item(config["tdarrStorage"]["logs"]),
            "transcodes": migrate_storage_item(config["tdarrStorage"]["transcodes"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["tdarrStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(
            config["resources"], config["tdarrGPU"], values.get("gpu_choices", {})
        ),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
