#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "filebrowser": {
            "additional_envs": config["filebrowserConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["filebrowserRunAs"].get("user", 568),
            "group": config["filebrowserRunAs"].get("group", 568),
        },
        "network": {
            "host_network": config["filebrowserNetwork"]["hostNetwork"],
            "web_port": config["filebrowserNetwork"].get("webPort", 30044),
            "certificate_id": config["filebrowserNetwork"].get("certificateID", None),
        },
        "storage": {
            "config": migrate_storage_item(config["filebrowserStorage"]["config"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["filebrowserStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
