app_version: latest
capabilities: []
categories:
- social
date_added: '2026-03-18'
description: GoToSocial is an ActivityPub social network server, written in Golang.
home: https://gotosocial.org/
host_mounts: []
icon: https://codeberg.org/superseriousbusiness/gotosocial/raw/branch/main/docs/overrides/public/sloth.webp
keywords:
- social
- activitypub
- fediverse
lib_version: 2.2.8
lib_version_hash: 76b40b42163deb26edbad5f973f1bd69b68bd85625bcd8247545194d99b9f912
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: gotosocial
run_as_context:
- description: gotosocial runs as any non-root user
  gid: 568
  group_name: gotosocial
  uid: 568
  user_name: gotosocial
screenshots: []
sources:
- https://codeberg.org/superseriousbusiness/gotosocial
title: GoToSocial
train: community
version: 1.0.0
