images:
  image:
    repository: netbirdio/netbird-server
    tag: 0.70.4
  dashboard_image:
    repository: netbirdio/dashboard
    tag: v2.37.1
  yq_image:
    repository: mikefarah/yq
    tag: 4.53.2
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  netbird_container_name: server
  dashboard_container_name: dashboard
  cfg_container_name: config
  perms_container_name: permissions
  config_path: /config
  config_file_name: config.yaml
  data_path: /var/lib/netbird
