#!/usr/bin/python3

import os
import sys
import yaml
import secrets


def migrate(values):
    values["ollama"]["override_context_length"] = False
    values["ollama"]["override_context_length"]["context_length"] = "4096"
    values["ollama"]["flash_attention"] = False
    values["ollama"]["flash_attention"]["kv_cache_type"] = "f16"
    values["ollama"]["override_keep_alive"] = False
    values["ollama"]["override_keep_alive"]["keep_alive"] = "5m"
    values["ollama"]["new_engine"] = False
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
