images:
  image:
    repository: ghcr.io/fosrl/newt
    tag: "1.18.0@sha256:07507a530f3f239bee4dc208aabdd25095df650f132e926245659e1a67aa5de9"

consts:
  newt_container_name: newt
  health_file_path: /tmp/newt_healthcheck
  config_file_path: /tmp/newt_config.json
