resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

adguardhome_sync:
  cron: "*/10 * * * *"
  run_on_start: true
  continue_on_error: false
  origin_url: http://adguard-origin.local:3000
  origin_username: fake-origin-user
  origin_password: fake-origin-password
  origin_api_path: /control
  origin_insecure_skip_verify: false
  origin_cookie: ""
  replica_url: http://adguard-replica.local:3000
  replica_username: fake-replica-user
  replica_password: fake-replica-password
  replica_api_path: /control
  replica_insecure_skip_verify: false
  replica_cookie: ""
  api_username: ""
  api_password: ""
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  config: /opt/tests/mnt/adguardhome-sync/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  additional_storage: []
