images:
  image:
    repository: invoiceninja/invoiceninja-octane
    tag: "5.12.28-o@sha256:b9366b3d1009a1ecc31c76d92f24669c32e9821a0fda6cd8703de23edf3fc767"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  mariadb_image:
    repository: mariadb
    tag: "13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"
  redis_image:
    repository: valkey/valkey
    tag: "9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd"
  nginx_image:
    repository: nginx
    tag: "1.31.6@sha256:908dc23e643a1447dbfb2e189ed268bfde6a51a5bf9a34d3dd3440a24f58ccf7"

consts:
  invoice_ninja_container_name: invoice-ninja
  invoice_ninja_worker_container_name: worker
  invoice_ninja_scheduler_container_name: scheduler
  perms_container_name: permissions
  mariadb_container_name: mariadb
  redis_container_name: redis
  admin_internal_port: 2019
  db_user: ninja
  db_name: ninja
