#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    # Remove all the *_provider_ip keys. Not needed anymore
    for provider in values["ddns"]["config"]:
        keys_to_delete = [key for key in provider.keys() if key.endswith("_provider_ip")]
        for key in keys_to_delete:
            provider.pop(key, None)
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
