annotations:
  min_scale_version: 25.10.0
app_version: v0.16.0
capabilities: []
categories:
- management
changelog_url: https://github.com/bearbinary/omni-infra-provider-truenas/releases
date_added: '2026-04-24'
description: Sidero Omni infrastructure provider that provisions Talos Linux VMs on
  TrueNAS SCALE.
home: https://github.com/bearbinary/omni-infra-provider-truenas
host_mounts: []
icon: https://media.sys.truenas.net/apps/omni-infra-provider-truenas/icons/icon.png
keywords:
- kubernetes
- omni
- talos
- sidero
- cluster
- vm-provisioning
lib_version: 2.3.2
lib_version_hash: b6a043c5dc3d4ba71901b9833713b4352b031f3bf39a1b3908e2cf17f1129d8d
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: omni-infra-provider-truenas
run_as_context:
- description: Container [omni-infra-provider-truenas] runs as non-root user and group.
  gid: 65534
  group_name: Host group is [nogroup]
  uid: 65534
  user_name: Host user is [nobody]
screenshots: []
sources:
- https://github.com/bearbinary/omni-infra-provider-truenas
title: Omni TrueNAS Provider
train: community
version: 1.0.0
