#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "mineos": {
            "additional_envs": config["mineosConfig"].get("additionalEnvs", []),
            "username": config["mineosConfig"]["username"],
            "password": config["mineosConfig"]["password"],
            "stop_grace_period": config["mineosConfig"]["terminationGracePeriodSeconds"],
        },
        "network": {
            "web_port": config["mineosNetwork"]["webPort"],
            "use_https": config["mineosNetwork"]["useHTTPS"],
            "additional_ports": [
                p
                for p in range(
                    config["mineosNetwork"]["mineosPortRangeStart"],
                    config["mineosNetwork"]["mineosPortRangeEnd"] + 1,
                )
            ],
            "certificate_id": config["mineosNetwork"].get("certificateID", None),
        },
        "run_as": {
            "user": config["mineosID"].get("user", 568),
            "group": config["mineosID"].get("group", 568),
        },
        "storage": {
            "data": migrate_storage_item(config["mineosStorage"]["data"]),
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
