images:
  image:
    repository: storjlabs/storagenode
    tag: "latest@sha256:21ca0ac819d1d66240830d28097eeb693923e51383aa3bb07bf823f9fad1f6e9"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  init_container_name: init
  storj_container_name: storj
  perms_container_name: permissions
  container_p2p_port: 28967
  identity_dir: /app/identity
  identity_tool_dir_files: /.local/share/storj/identity
  config_dir: /app/config
