images:
  image:
    repository: subsimail/subsimail
    tag: "7.0.0@sha256:f640ab2f02ce84d54c72076a3f90508cdcff669b2d56779f68d14b3262b0a5ec"

consts:
  subsimail_container_name: subsimail
  data_dir: /app/data
