#!/usr/bin/python3

import os
import sys
import yaml


def migrate():
    raise Exception(
        "Upgrading to version 2.0.0 from 1.x.x is not supported. "
        "Please perform a clean install of version 2.0.0 and migrate your data manually. "
        "See https://v2.dictionarry.dev/devlogs/profilarr-v2 for more details."
    )


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate()))
