images:
  image:
    repository: ghcr.io/libredb/libredb-studio
    tag: 0.9.66
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  libredb_container_name: libredb-studio
  perms_container_name: permissions
  run_user: 568
  run_group: 568
  data_path: /app/data
