resources:
  limits:
    cpus: 2
    memory: 512

glance:
  enable_docker_socket: false
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: published
    port_number: 30057
    host_ips: []
  host_network: false

ix_volumes:
  test_glance_config: /opt/tests/mnt/glance/config
  test_glance_assets: /opt/tests/mnt/glance/assets

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: test_glance_config
      create_host_path: true
  assets:
    type: ix_volume
    ix_volume_config:
      dataset_name: test_glance_assets
      create_host_path: true
  additional_storage: []

labels: []
