resources:
  limits:
    cpus: 2
    memory: 512

glance:
  enable_docker_socket: false
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: published
    port_number: 30080
    host_ips: []
  host_network: false

storage:
  config:
    type: host_path
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/glance/config
  assets:
    type: host_path
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/glance/assets
  additional_storage: []

labels: []
