#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    additional_envs = []
    origins = []
    for env in values["timelinize"].get("additional_envs", []):
        if env["name"] != "TLZ_ORIGIN":
            additional_envs.append(env)
        else:
            origins = [o.strip() for o in env["value"].split(",") if o.strip()]
    values["timelinize"]["additional_envs"] = additional_envs
    values["timelinize"]["origins"] = origins

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
