images:
  image:
    repository: ghcr.io/derkezorm/nexdeck
    tag: "0.28.0@sha256:07f6f9f96c2dace152a5354a47c614ee8df49bb3da7658cd601aaba8b45eabe8"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  nexdeck_container_name: nexdeck
  perms_container_name: permissions
