admin_password: test-password
web_port: 30492
shared_folder: /opt/tests/mnt/shares
advanced: false
basic_config_storage:
  type: ix_volume
  ix_volume_config:
    dataset_name: config
    create_host_path: true
ix_volumes:
  config: /opt/tests/mnt/config
