#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    data = values["storage"]["data"]
    data["mount_path"] = "/data"
    data["index_data"] = True
    values["storage"]["additional_storage"].append(data)
    values["storage"].pop("data")
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
