images:
  image:
    repository: ghcr.io/fclairamb/solidping
    tag: "0.38.0@sha256:be1a635658d89bdf20139aa5d4270e399fb96b7136214c6999b43a61f9254611"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  solidping_container_name: solidping
  perms_container_name: permissions
  data_path: /data

  notes_body: |
    Default credentials:
    - Username: `admin@solidping.io`
    - Password: `solidpass`
