images:
  image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.7.2-java21
  j21_alpine_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.7.2-java21-alpine
  j25_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.7.2-java25
  j8_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.7.2-java8
  j11_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.7.2-java11
  j17_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.7.2-java17

consts:
  minecraft_container_name: minecraft
