resources:
  limits:
    cpus: 2.0
    memory: 1024

TZ: Etc/UTC
caddy:
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  host_network: false
  http_port:
    bind_mode: published
    port_number: 30080
  https_port:
    bind_mode: published
    port_number: 30443
  additional_ports: []

ix_volumes:
  caddyfile: /opt/tests/mnt/caddy/caddyfile
  data: /opt/tests/mnt/caddy/data
  config: /opt/tests/mnt/caddy/config

storage:
  caddyfile:
    type: ix_volume
    ix_volume_config:
      dataset_name: caddyfile
      create_host_path: true
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  additional_storage: []
