words:
  - aliyun
  - allinkl
  - changeip
  - cooldown
  - CPUS
  - DDNS
  - ddnss
  - desec
  - dnsomatic
  - dnspod
  - dondominio
  - dreamhost
  - duckdns
  - dynu
  - dynv
  - easydns
  - freedns
  - gandi
  - godaddy
  - goip
  - Healtcheck
  - hetzner
  - icanhazip
  - inwx
  - ionos
  - ipify
  - ipinfo
  - ipleak
  - isready
  - logsearch
  - luadns
  - Mebibytes
  - minio
  - namecheap
  - netcup
  - njalla
  - nnev
  - nocopy
  - noip
  - nowdns
  - opendns
  - porkbun
  - proxied
  - PUBLICIP
  - PUBLICIPV
  - seeip
  - selfhost.de
  - servercow
  - shoutrrr
  - spdyn
  - strato
  - tmpfs
  - tracebacklimit
  - variomedia
  - wtfismyip
  - zoneedit
