#!/usr/bin/python3

if __name__ == "__main__":
    raise Exception(
        "Upgrading to v2 is not supported,"
        " due to incompatible embedded mongodb version."
        " Please export the UniFi configuration from UniFi UI Console,"
        " reinstall the app fresh and import the configuration."
    )
