app_version: 1.1.2
capabilities: []
categories:
- media
changelog_url: https://github.com/nzbfast/nzbfast/releases
date_added: '2026-08-15'
description: nzbfast is a speed-focused Usenet (NZB) downloader with a web dashboard
  and a SABnzbd-compatible API.
home: https://nzbfast.github.io/nzbfast/
host_mounts: []
icon: https://media.sys.truenas.net/apps/nzbfast/icons/icon.svg
keywords:
- media
- usenet
- newsreader
lib_version: 2.3.11
lib_version_hash: 874636814efb275e5276ea9d709b7cd665fed42bb1d50328e853d9253a2e1229
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: nzbfast
run_as_context:
- description: Container [nzbfast] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/nzbfast_community/
- https://github.com/nzbfast/nzbfast
- https://nzbfast.github.io/nzbfast/
title: nzbfast
train: community
version: 1.0.0
