images:
  image:
    repository: ghcr.io/analogj/scrutiny
    tag: "v0.9.5-omnibus@sha256:6ee271ee531458f134220ca8b2c5c8ccc2711a799c827fef953fa865d91e312f"

consts:
  scrutiny_container_name: scrutiny
  config_dir: /opt/scrutiny/config
  internal_influxdb_port: 8086
  internal_web_port: 8080
  notes_body: |
    Default InfluxDB Credentials:
    - Username: admin
    - Password: password12345
