images:
  image:
    repository: ghcr.io/pterodactyl/panel
    tag: "v1.15.1@sha256:e27a06cfcd078691ddf9805ae0dee2ee529b35ce18e427ef970de4d503602f2c"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  mariadb_image:
    repository: mariadb
    tag: "13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"
  redis_image:
    repository: valkey/valkey
    tag: "9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd"

consts:
  pterodactyl_container_name: pterodactyl
  perms_container_name: permissions
  mariadb_container_name: mariadb
  redis_container_name: redis
  db_user: pterodactyl-panel
  db_name: pterodactyl-panel
  internal_web_port: 80
  notes_body: |
    To create an admin user after successful installation,
    open a shell in the container and run the command
    following the on-screen instructions: `php artisan p:user:make`
