{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.restic_manager_container_name, "image") %}

{% do c1.set_user(0, 0) %}
{% do c1.healthcheck.set_custom_test(["CMD", "/usr/local/bin/truenas-restic-manager", "healthcheck"]) %}
{% do c1.healthcheck.set_timeout(10) %}
{% do c1.healthcheck.set_start_period(5) %}
{% do c1.healthcheck.set_start_interval(5) %}

{% do c1.environment.add_env("TRM_LISTEN", ":%d" | format(values.network.web_port.port_number)) %}
{% do c1.environment.add_env("TRM_STORE_PATH", values.consts.store_path) %}
{% do c1.environment.add_env("TRM_WORKDIR", values.consts.work_dir_path) %}
{% do c1.environment.add_env("TRM_TRUENAS_MIDDLEWARE_SOCKET", values.consts.truenas_middleware_socket_path) %}
{% do c1.environment.add_env("TRM_LOG_LEVEL", values.restic_manager.log_level) %}
{% do c1.environment.add_env("TRM_LOG_COLOR", false) %}
{% do c1.environment.add_env("TRM_LOG_FORMAT", values.restic_manager.log_format) %}
{% do c1.environment.add_env("RESTIC_CACHE_DIR", values.consts.cache_dir_path) %}

{% if values.restic_manager.upstream_trusted_address %}
  {% do c1.environment.add_env("TRM_UPSTREAM_TRUSTED_ADDRESS", values.restic_manager.upstream_trusted_address) %}
{% endif %}

{% do c1.add_port(values.network.web_port) %}

{% do c1.add_storage(values.consts.data_dir_path, values.storage.data) %}
{% do c1.add_storage(values.consts.cache_mount_path, values.storage.cache) %}
{% do c1.add_storage(values.consts.work_dir_path, {"type": "tmpfs", "tmpfs_config": {}}) %}
{% do c1.add_truenas_mnt(mount_path=values.consts.truenas_mnt_path) %}
{% do c1.add_truenas_middleware_socket(mount_path=values.consts.truenas_middleware_socket_path) %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
