resources:
  limits:
    cpus: 2.0
    memory: 4096

pulsarr:
  allow_iframes: false
  log_requests: true
  additional_envs: []
  authentication: "required"

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 38383
  cookie_secured: false

run_as:
  user: 568
  group: 568

ix_volumes:
  app_data: /opt/tests/mnt/config

storage:
  app_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: app_data
      create_host_path: true
  additional_storage:
    - type: anonymous
      mount_path: /scratchpad
      volume_config:
        nocopy: true
