images:
  image:
    repository: ghcr.io/prophetse7en/clonarr
    tag: "v3.4.0@sha256:9400d298b37a61b89f77ff3e46be4feb51fec68f294e00ba6c15beca00970d29"

consts:
  clonarr_container_name: clonarr
  config_path: /config
