images:
  image:
    repository: ghcr.io/endless1233214/plainnvr
    tag: "0.1.5@sha256:dc04572b9204224a872c0fbb4606147912944203ed869a5eed5b34e4dc0b2713"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  plainnvr_container_name: plainnvr
  perms_container_name: permissions
  data_path: /data
  recordings_path: /recordings
