images:
  image:
    repository: ghcr.io/louislam/uptime-kuma
    tag: "2.5.5@sha256:c74379ac4509ce2d2c2633f509e67003ee2e45b6e995c5e43fc101f45a0e1fbe"

consts:
  uptime_kuma_container_name: uptime-kuma
