images:
  image:
    repository: nzbgetcom/nzbget
    tag: "v26.3@sha256:f451d98066cbc0c108146420a61a60f7638de50e067738951461e0105eeaa56d"

consts:
  nzbget_container_name: nzbget
  notes_body: |
    Default Credentials:
    - Username: nzbget
    - Password: tegbzn6789
