frpc:
  custom_toml: false
  server_addr: frps.example.com
  server_port: 7000
  login_user: ""
  auth_token: testtoken1234567890
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  host_network: true
  web_server: false

storage:
  additional_storage: []

labels: []

resources:
  limits:
    cpus: 1
    memory: 256
