images:
  image:
    repository: ghcr.io/jinjinov/openhabittracker
    tag: "1.2.5@sha256:c040b1b7c961554a6e60c2b84d916298056d9703f5e1da5b1e54b2720f14177b"

consts:
  openhabittracker_container_name: openhabittracker
