images:
  image:
    repository: ghcr.io/huncrys/minio-console
    tag: "v1.8.1@sha256:c4b0be15c6fd1aacb0fed9f93a5390bf360c409d3a3b1929636cf357dbd3570a"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  console_container_name: console
  perms_container_name: permissions
  certs_dir: /certs
