resources:
  limits:
    cpus: 2.0
    memory: 4096

cwa:
  hardcover_token: ""
  network_share_mode: false
  watch_mode: false
  trusted_proxy_count: 1
  disable_library_automount: false

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 8080

run_as:
  user: 568
  group: 568

ix_volumes:
  config: /opt/tests/mnt/config
  calibre_library: /opt/tests/mnt/calibre-library
  cwa_book_ingest: /opt/tests/mnt/cwa-book-ingest

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true

  calibre_library:
    type: ix_volume
    ix_volume_config:
      dataset_name: calibre_library
      create_host_path: true

  book_ingest:
    type: ix_volume
    ix_volume_config:
      dataset_name: cwa_book_ingest
      create_host_path: true

  additional_storage: []
