#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "unifi": {
            "additional_envs": config["netdataConfig"].get("additionalEnvs", []),
        },
        "network": {
            "host_network": config["netdataNetwork"]["hostNetwork"],
            "enable_web_http": config["netdataNetwork"].get("enableWebHttp", 33000),
            "web_http_port": config["netdataNetwork"].get("webHttpPort", 33001),
            "web_https_port": config["netdataNetwork"].get("webHttpsPort", 33002),
            "enable_portal_http": config["netdataNetwork"].get("enablePortalHttp", 33003),
            "portal_http_port": config["netdataNetwork"].get("portalHttpPort", 33004),
            "portal_https_port": config["netdataNetwork"].get("portalHttpsPort", 33005),
            "certificate_id": config["netdataNetwork"].get("certificateID", 33006),
        },
        "storage": {
            "data": migrate_storage_item(config["netdataStorage"]["data"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["netdataStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
