#!/usr/bin/python3

if __name__ == "__main__":
    raise Exception(
        "Upgrading to v2 is not supported,"
        " due to incompatible embedded mongodb version."
        " Do note that newer mongo version requires AVX cpu instruction set on the CPU."
        " Before proceeding with the following, verify that your CPU supports AVX."
        " Please export the UniFi configuration from UniFi UI Console,"
        " reinstall the app fresh and import the configuration."
    )
