#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "mumble": {
            "additional_envs": config["mumbleConfig"].get("additionalEnvs", []),
            "superuser_password": config["mumbleConfig"]["superUserPassword"],
            "server_password": config["mumbleConfig"]["serverPassword"],
            "ice_secret_read": config["mumbleConfig"]["iceSecretRead"],
            "ice_secret_write": config["mumbleConfig"]["iceSecretWrite"],
            "welcome_text": config["mumbleConfig"]["welcomeText"],
            "users": config["mumbleConfig"]["users"],
        },
        "network": {
            "server_port": config["mumbleNetwork"]["serverPort"],
            "ice_port": config["mumbleNetwork"]["icePort"],
            "certificate_id": config["mumbleNetwork"].get("certificateID", None),
        },
        "storage": {
            "data": migrate_storage_item(config["mumbleStorage"]["data"]),
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
