#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "ipfs": {
            "additional_envs": config["ipfsConfig"].get("additionalEnvs", []),
        },
        "network": {
            "host_network": config["ipfsNetwork"]["hostNetwork"],
            "api_port": config["ipfsNetwork"]["apiPort"],
            "swarm_port": config["ipfsNetwork"]["swarmPort"],
            "gateway_port": config["ipfsNetwork"]["gatewayPort"],
        },
        "run_as": {
            "user": config["ipfsRunAs"].get("user", 568),
            "group": config["ipfsRunAs"].get("group", 568),
        },
        "storage": {
            "data": migrate_storage_item(config["ipfsStorage"]["data"]),
            "staging": migrate_storage_item(config["ipfsStorage"]["staging"]),
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
