resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: America/New_York

hytale:
  server_name: "Test Hytale Server"
  server_motd: "Welcome to the test server"
  server_password: ""
  max_players: 10
  default_gamemode: Adventure
  patchline: release
  additional_envs: []
  auto_update:
    enabled: false
    interval: 3600
    time: ""
    restart: true
    backup: true
  api:
    client_secret: "testpassword123"
    client_id: "hyos-manager"
  advanced:
    show_advanced: false
    auth_mode: ""

run_as:
  user: 568
  group: 568

network:
  game_port:
    bind_mode: published
    port_number: 30520
  api_port:
    bind_mode: published
    port_number: 30365
  manager_port:
    bind_mode: published
    port_number: 30366

ix_volumes:
  data: /opt/tests/mnt/hyos/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      acl_enable: false
      dataset_name: data
      create_host_path: true
  additional_storage: []
