annotations:
  min_scale_version: 24.10.2.2
app_version: 1.37.1
capabilities:
- description: Frontend is able to change file ownership arbitrarily
  name: CHOWN
- description: Frontend is able to change group ID of processes
  name: SETGID
- description: Frontend is able to change user ID of processes
  name: SETUID
categories:
- productivity
changelog_url: https://github.com/tess1o/GeoPulse/releases
date_added: '2026-08-11'
description: GeoPulse is an open-source, privacy-first Google Timeline alternative
home: https://github.com/tess1o/GeoPulse
host_mounts: []
icon: https://media.sys.truenas.net/apps/geopulse/icons/icon.svg
keywords:
- location
- gps
- timeline
- history
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: geopulse
run_as_context:
- description: Container [backend] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [frontend] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [postgis] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots:
- https://media.sys.truenas.net/apps/geopulse/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/geopulse/screenshots/screenshot2.png
sources:
- https://apps.truenas.com/catalog/geopulse_community/
- https://github.com/tess1o/GeoPulse
- https://hub.docker.com/r/tess1o/geopulse-backend
- https://hub.docker.com/r/tess1o/geopulse-ui
title: GeoPulse
train: community
version: 1.0.1
