images:
  image:
    repository: registry.gitlab.com/storyteller-platform/storyteller
    tag: web-v2.14.17
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  storyteller_container_name: storyteller
  perms_container_name: permissions
  data_path: /data
