resources:
  limits:
    cpus: 2.0
    memory: 4096

libredb:
  admin_email: admin@example.com
  admin_password: changeme-please-8chars
  jwt_secret: change-this-to-a-long-random-secret-min-32-chars
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30504

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
