resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

inbox_zero:
  postgres_image_selector: postgres_18_image
  db_password: secret
  redis_password: secret
  base_url: http://localhost:8080
  auth_secret: 0123456789abcdef0123456789abcdef
  email_encrypt_secret: 0123456789abcdef0123456789abcdef
  email_encrypt_salt: 0123456789abcdef
  auth_provider: microsoft
  google:
    client_id: ""
    client_secret: ""
    pubsub_topic_name: ""
  microsoft:
    client_id: test-client-id
    client_secret: test-client-secret
  llm:
    provider: ollama
    model: qwen3.5:4b
    api_key: ""
    base_url: http://ollama:11434/api
  additional_envs:
    - name: NEXT_PUBLIC_DIGEST_ENABLED
      value: "true"

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: published
    port_number: 8080

storage:
  postgres_data:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/inbox-zero/postgres_data_hostpath
      auto_permissions: true
      create_host_path: true
  additional_storage: []
