images:
  image:
    repository: borgwarehouse/borgwarehouse
    tag: v3.5.0
  cron_image:
    repository: ixsystems/cron
    tag: 1.0.8
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  borgwarehouse_container_name: borgwarehouse
  borgwarehouse_cron_container_name: cron
  perms_container_name: permissions

  internal_ssh_port: 22
  internal_web_port: 3000

  notes_body: |
    Default credentials:
    - Username: `admin`
    - Password: `admin`
