#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["network"]["web_port"] = {
        "port_number": values["network"].get("web_port", 30038),
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["torrent_port"] = {
        "port_number": values["network"].get("torrent_port", 30039),
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["daemon_port"] = {
        "port_number": values["network"].get("daemon_port", 58846),
        "bind_mode": "published" if values["network"]["expose_daemon_port"] else "",
        "host_ips": [],
    }
    values["network"].pop("expose_daemon_port", None)

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
