spokes:
  master_password: "super_secret_password"
network:
  web_port:
    port: 8080
ix_volumes:
  test_spokes_data: /opt/tests/mnt/spokes/data
storage:
  data:
    type: "ix_volume"
    ix_volume_config:
      dataset_name: test_spokes_data
      create_host_path: true
      acl_enable: false
