resources:
  limits:
    cpus: 2.0
    memory: 4096

traefik:
  api_insecure: true
  dashboard: true
  additional_args:
    - flag: --log.level
      value: DEBUG
  additional_envs: []

network:
  host_network: false
  api_port:
    bind_mode: published
    port_number: 8080
  entry_points:
    - entrypoint_name: web
      bind_mode: published
      port_number: 8082
      protocol: tcp

run_as:
  user: 568
  group: 568

ix_volumes:
  config: /opt/tests/mnt/traefik/config
  acme: /opt/tests/mnt/traefik/acme

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  acme:
    type: ix_volume
    ix_volume_config:
      dataset_name: acme
      create_host_path: true
  additional_storage: []
