images:
  image:
    repository: ghcr.io/zwave-js/zwave-js-ui
    tag: "11.24.2@sha256:717f9d2609021b001d3543ec7144c4fc3ba0e31b61dbcd616383b93613b22f89"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  zwave_container_name: zwave
  config_container_name: config
  perms_container_name: permissions
  ssl_key_path: /certs/tls.key
  ssl_cert_path: /certs/tls.crt

  data_path: /usr/src/app/store
  zwave_serial_path: /dev/zwave
