resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

sparkyfitness:
  postgres_image_selector: postgres_18_image
  db_password: test-db-password
  api_encryption_key: a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2
  better_auth_secret: test-better-auth-secret-value-at-least-32-chars-long
  frontend_url: http://localhost:30840
  admin_email: ""
  disable_signup: false
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30840

run_as:
  user: 568
  group: 568

ix_volumes:
  postgres_data: /opt/tests/mnt/sparkyfitness/postgres-data
  backup: /opt/tests/mnt/sparkyfitness/backup
  uploads: /opt/tests/mnt/sparkyfitness/uploads

storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  backup:
    type: ix_volume
    ix_volume_config:
      dataset_name: backup
      create_host_path: true
  uploads:
    type: ix_volume
    ix_volume_config:
      dataset_name: uploads
      create_host_path: true
  additional_storage: []
