#!/usr/bin/python3

import os
import sys
import yaml
import secrets


def migrate(values):
    values["open_webui"]["webui_secret_key"] = secrets.token_urlsafe(32)[:32]
    values["open_webui"]["redis_password"] = secrets.token_urlsafe(32)[:32]
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
