resources:
  limits:
    cpus: 2.0
    memory: 4096

ratelog:
  tmdb_api_key: "test-tmdb-key"
  db_password: "test-pass"

network:
  web_port:
    bind_mode: published
    port_number: 30080

ix_volumes:
  test_ratelog_postgres_data: /opt/tests/mnt/ratelog/postgres_data

storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: test_ratelog_postgres_data
      create_host_path: true