images:
  image:
    repository: ghcr.io/stdapi-ai/stdapi.ai-community
    tag: "1.19.1@sha256:2e9c9ac7938e85a4ea9846e864072301c8277f2a67326f707462ba4542cddf8c"

consts:
  stdapi_ai_container_name: stdapi-ai
