#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "network": {
            "web_port": config["adguardNetwork"].get("webPort", 32400),
            "dns_port": config["adguardNetwork"].get("dnsPort", 30153),
            "host_network": config["adguardNetwork"].get("hostNetwork", False),
            "dhcp_enabled": config["adguardNetwork"].get("enableDHCP", False),
        },
        "storage": {
            "config": migrate_storage_item(config["adguardStorage"]["conf"]),
            "work": migrate_storage_item(config["adguardStorage"]["work"]),
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
