images:
  image:
    repository: ghcr.io/twin/gatus
    tag: "v5.37.0@sha256:094eb186e55235db367e90e9d56140e5897b7044c41de23cde4cc18e6da1242e"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  yq_image:
    repository: mikefarah/yq
    tag: "4.53.6@sha256:cfc4eee658595834ef304eadb0c3ea721f3b7cb6404ad8b7cb909cc5b5145b23"

consts:
  gatus_container_name: gatus
  perms_container_name: permissions
  config_container_name: config
  data_path: /app/data
  ssl_key_path: /app/certs/ssl.key
  ssl_cert_path: /app/certs/ssl.crt

  notes_body: |
    For additional configuration, you can create YAML file(s) in the
    /app/data/config.d/ directory.</br>

    Additional documentation can be found at:</br>
    - https://github.com/TwiN/gatus?tab=readme-ov-file#keeping-your-configuration-small
    - https://github.com/TwiN/gatus?tab=readme-ov-file#usage
    - https://github.com/TwiN/gatus?tab=readme-ov-file#configuration
