images:
  image:
    repository: ghcr.io/derkezorm/nexbeat
    tag: 0.2.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  nexbeat_container_name: nexbeat
  perms_container_name: permissions
