resources:
  limits:
    cpus: 1.0
    memory: 512

TZ: Etc/UTC

run_as:
  user: 1234
  group: 1234

ghostfolio:
  postgres_image_selector: postgres_18_image
  db_password: supersecret123
  redis_password: supersecret234
  jwt_secret_key: supersecret345

network:
  web_port:
    bind_mode: published
    port_number: 3333

ix_volumes:
  postgres_data: /opt/tests/mnt/ghostfolio/postgres_data_other

storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []
