resources:
  limits:
    cpus: 4.0
    memory: 8192

vllm:
  image_selector: cpu_image
  model_name: "Qwen/Qwen3-0.6B"
  max_model_len: 4096
  hf_token: ""
  additional_envs:
    - name: VLLM_CPU_KVCACHE_SPACE
      value: "2"

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30423

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/vllm/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
