images:
  image:
    repository: ghcr.io/notifiarr/notifiarr
    tag: "v0.9.7@sha256:2b0a8784d8a43177cbc5a19110e7eb066d9321572c3352eda79c0a89898c7735"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  notifiarr_container_name: notifiarr
  perms_container_name: permissions
  ssl_key_path: /cert/key.pem
  ssl_cert_path: /cert/cert.pem
