resources:
  limits:
    cpus: 2
    memory: 512

TZ: Etc/UTC

stdapi_ai:
  aws_access_key_id: test-access-key-id
  aws_secret_access_key: test-secret-access-key
  aws_bedrock_regions: us-east-1
  enable_docs: false
  additional_envs: []

network:
  host_network: false
  api_port:
    bind_mode: published
    port_number: 30396
