images:
  image:
    repository: ghcr.io/libredb/libredb-studio
    tag: "0.17.0@sha256:ce4d58724e2507a4467bcce6702d00760475e0f339071d878fce83e90c99718f"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  libredb_container_name: libredb-studio
  perms_container_name: permissions
  data_path: /app/data
