resources:
  limits:
    cpus: 2.0
    memory: 4096

nzbfast:
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 30056
  additional_ports: []

run_as:
  user: 568
  group: 568

ix_volumes:
  config: /opt/tests/mnt/nzbfast/config
  downloads: /opt/tests/mnt/nzbfast/downloads
  watch: /opt/tests/mnt/nzbfast/watch

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  downloads:
    type: ix_volume
    ix_volume_config:
      dataset_name: downloads
      create_host_path: true
  watch:
    type: ix_volume
    ix_volume_config:
      dataset_name: watch
      create_host_path: true
  additional_storage: []
