#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["network"]["web_port"] = {
        "port_number": values["network"]["web_port"],
        "bind_mode": "published",
        "host_ips": [],
    }

    values["network"]["additional_ports"] = [
        {
            "bind_mode": "published",
            "port_number": p["published"],
            "container_port": p["target"],
            "protocol": p["protocol"],
            "host_ips": [],
        }
        for p in values["network"].get("additional_ports", [])
    ]

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
