#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "rust_desk": {
            "allow_only_encrypted_connections": config["rustConfig"].get(
                "allowOnlyEncryptedConnections", False
            ),
            "additional_relay_servers": config["rustConfig"].get(
                "additionalRelayServers", []
            ),
            "additional_envs": config["rustConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["rustRunAs"].get("user", 568),
            "group": config["rustRunAs"].get("group", 568),
        },
        "network": {
            "host_network": config["rustNetwork"].get("hostNetwork", False),
            "nat_type_test_port": config["rustNetwork"].get("natTypeTestPort", 21115),
            "id_reg_hole_punch_port": config["rustNetwork"].get(
                "idRegHolePunchPort", 21116
            ),
            "relay_port": config["rustNetwork"].get("relayPort", 21117),
            "enable_web_clients": config["rustNetwork"].get("enableWebClientPorts", True),
            "server_web_clients_port": config["rustNetwork"].get(
                "serverWebClientsPort", 21118
            ),
            "relay_web_clients_port": config["rustNetwork"].get(
                "relayWebClientsPort", 21119
            ),
        },
        "storage": {
            "data": migrate_storage_item(config["rustStorage"]["data"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["rustStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
