TZ: Europe/Zurich

zab:
  backup_name: offsite
  source_datasets:
    - tank/data
  target_path: backup/truenas
  ssh_target: root@backup.example.com
  ssh_source: ""
  keep_source: "10,1d1w,1w1m,1m1y"
  keep_target: "10,1d1w,1w1m,1m1y"
  strip_path: 1
  verbose: true
  additional_args:
    - --exclude-received
  cron_schedule: "0 3 * * *"
  run_on_startup: false
  ping_url: https://hc-ping.com/00000000-0000-0000-0000-000000000000
  trust_host_key_on_first_use: true
  additional_envs: []

network:
  host_network: false

ix_volumes:
  config: /opt/tests/mnt/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  additional_storage: []

resources:
  limits:
    cpus: 2.0
    memory: 4096
