TZ: Etc/UTC

zab:
  backup_name: daily
  source_datasets: []
  target_path: ""
  ssh_target: ""
  ssh_source: ""
  keep_source: "30"
  keep_target: ""
  strip_path: 1
  verbose: false
  additional_args: []
  cron_schedule: "@daily"
  run_on_startup: true
  ping_url: ""
  trust_host_key_on_first_use: false
  additional_envs: []

network:
  host_network: false

ix_volumes:
  config: /opt/tests/mnt/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  additional_storage: []

resources:
  limits:
    cpus: 2.0
    memory: 4096
