resources:
  limits:
    cpus: 2.0
    memory: 1024

mediathek:
  channels: "ARD,3Sat"
  public_url: "https://mediathek.example.com"
  additional_envs:
    - name: CATALOG_DEPTH
      value: "1000"

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 8081

run_as:
  user: 568
  group: 568

storage:
  additional_storage: []
