#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    # If run_as is already set, respect it.
    if "run_as" in values:
        return values

    # If its not try to use an appropriate default based on image_selector
    run_as_id = 0 if values["image_selector"] == "tve_image" else 568
    values["run_as"] = {"user": run_as_id, "group": run_as_id}
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
