{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.actuallyfreecd_container_name, "image") %}

{% do c1.add_caps(["CHOWN", "DAC_OVERRIDE", "FOWNER", "SETGID", "SETUID"]) %}
{% do c1.healthcheck.set_test("http", {"port": values.consts.internal_web_port, "path": "/api/status"}) %}

{% for device in values.actuallyfreecd.devices %}
  {% do c1.devices.add_device(device.host_device, device.container_device) %}
  {% if not device.container_device.startswith("/hostdev/") %}
    {% do tpl.funcs.fail("Container device must start with /hostdev/") %}
  {% endif %}
{% endfor %}

{% do c1.environment.add_env("DEVICE_ROOT", "/hostdev") %}
{% do c1.environment.add_env("MUSIC_ROOT", "/music") %}
{% do c1.environment.add_user_envs(values.actuallyfreecd.additional_envs) %}

{% do c1.add_port(values.network.web_port, {"container_port": values.consts.internal_web_port}) %}

{% do c1.add_storage("/music", values.storage.music) %}

{% do tpl.portals.add(values.network.web_port, {"port": values.consts.internal_web_port if values.network.host_network else None}) %}

{{ tpl.render() | tojson }}
