images:
  image:
    repository: chrislusf/seaweedfs
    tag: "4.17"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  master_container_name: master
  admin_container_name: admin
  worker_container_name: worker
  volume_container_name: volume
  filer_container_name: filer
  s3_container_name: s3
  perms_container_name: permissions
  data_path: /data
  s3_ssl_key_path: /certs/s3-key.pem
  s3_ssl_cert_path: /certs/s3-cert.pem

  reserved_flags:
    master:
      - ip
      - ip.bind
      - port
      - port.grpc
      - mdir
      - volumeSizeLimitMB
      - peers
    s3:
      - filer
      - ip.bind
      - port
      - port.grpc
      - metricsPort
      - key.file
      - cert.file
    filer:
      - master
      - ip
      - ip.bind
      - port
      - port.grpc
      - defaultStoreDir
      - metricsPort
    volume:
      - master
      - ip
      - ip.bind
      - port
      - port.grpc
      - dir
      - max
      - rack
      - dataCenter
      - metricsPort
    worker:
      - workingDir
      - metricsPort
      - admin
    admin:
      - masters
      - dataDir
      - adminUser
      - adminPassword
      - port
      - port.grpc
