#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    envs = []
    admin_token = config["vaultwardenConfig"].get("adminToken")
    for env in config["vaultwardenConfig"].get("additionalEnvs", []):
        if env["name"] == "ADMIN_TOKEN":
            admin_token = env["value"]
        else:
            envs.append(env)

    new_values = {
        "TZ": config["TZ"],
        "vaultwarden": {
            "admin_token": admin_token,
            "db_password": get_value_from_secret(k8s_secrets, "postgres-creds", "POSTGRES_PASSWORD"),
            "additional_envs": envs,
        },
        "run_as": {
            "user": config["vaultwardenRunAs"].get("user", 568),
            "group": config["vaultwardenRunAs"].get("group", 568),
        },
        "network": {
            "web_port": config["vaultwardenNetwork"]["webPort"],
            "ws_enabled": config["vaultwardenNetwork"]["wsEnabled"],
            "ws_port": config["vaultwardenNetwork"].get("wsPort", 30033),
            "certificate_id": config["vaultwardenNetwork"].get("certificateID"),
            "domain": config["vaultwardenNetwork"].get("domain"),
        },
        "storage": {
            "data": migrate_storage_item(config["vaultwardenStorage"]["data"]),
            "postgres_data": migrate_storage_item(config["vaultwardenStorage"]["pgData"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["vaultwardenStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
