app_version: 3.3.1
capabilities: []
categories:
- storage
changelog_url: https://github.com/rejetto/hfs/releases
date_added: '2026-09-16'
description: HTTP file server with uploads, downloads, accounts, permissions and a
  virtual file system.
home: https://rejetto.com/hfs/
host_mounts: []
icon: https://raw.githubusercontent.com/rejetto/hfs/main/admin/public/hfs-logo-icon.svg
keywords:
- files
- sharing
- http
lib_version: 2.3.12
lib_version_hash: ''
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: hfs
run_as_context:
- description: HFS runs as the selected user and group.
  uid: 568
  gid: 568
  user_name: apps
  group_name: apps
screenshots: []
sources:
- https://github.com/rejetto/hfs
- https://hub.docker.com/r/rejetto/hfs
title: HFS
train: community
version: 1.0.0
