resources:
  limits:
    cpus: 2.0
    memory: 4096

finachy:
  postgres_image_selector: postgres_18_image
  db_password: test_password
  redis_password: test_redis_password
  secret_key_base: a7523c3d0ae56415046ad8abae168d71074a79534a7062258f8d1d51ac2f76d3
  additional_envs: []

run_as:
  user: 1000
  group: 1000

network:
  web_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  data: /opt/tests/mnt/finachy/data
  pg_data: /opt/tests/mnt/finachy/pg_data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: pg_data
      create_host_path: true
  additional_storage: []

labels: []
