appversion: 7.1.2
capabilities: []
categories:
- security
dateadded: '2026-03-10'
description: CUDA Hashcat + John Ripper - GPU password cracking
home: https://hashcat.net
hostmounts: []
icon: https://hashcat.net/img/hashcat-logo.png
keywords:
- hashcat
- password
- gpu
lib_version: 2.2.8
lib_version_hash: 76b40b42163deb26edbad5f973f1bd69b68bd85625bcd8247545194d99b9f912
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: cuda-hashcat
runascontext:
- description: Container [cuda-hashcat] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/hashcat/hashcat
title: CUDA Hashcat
train: community
version: 1.0.0
