#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "fresh_rss": {
            "additional_envs": config["freshrssConfig"].get("additionalEnvs", []),
            "default_admin_user": config["freshrssConfig"]["defaultAdmin"],
            "default_admin_password": config["freshrssConfig"]["defaultAdminPass"],
            "cron_min": "*/15",
            "db_password": get_value_from_secret(
                k8s_secrets, "postgres-creds", "POSTGRES_PASSWORD"
            ),
            "db_user": get_value_from_secret(
                k8s_secrets, "postgres-creds", "POSTGRES_USER"
            ),
            "db_name": get_value_from_secret(
                k8s_secrets, "postgres-creds", "POSTGRES_DB"
            ),
        },
        "network": {
            "web_port": config["freshrssNetwork"].get("webPort", 30027),
        },
        "storage": {
            "data": migrate_storage_item(config["freshrssStorage"]["data"]),
            "extensions": migrate_storage_item(config["freshrssStorage"]["extensions"]),
            "postgres_data": migrate_storage_item(config["freshrssStorage"]["pgData"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["freshrssStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
