#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if values["storage"].get("use_old_storage_config", False) is True:
        raise Exception(
            "Cannot remove old storage config while it is still in use."
            " Please migrate to the new storage config first before upgrading."
        )
    for key in ["use_old_storage_config", "library", "uploads", "thumbs", "profile", "video", "backups"]:
        values["storage"].pop(key, None)

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
