resources:
  limits:
    cpus: 2.0
    memory: 4096

openhabittracker:
  username: testuser
  email: test@example.com
  password: test-password-1234
  jwt_secret: test-jwt-secret-must-be-long-enough-1234567890
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8081

ix_volumes:
  data: /opt/tests/mnt/openhabittracker/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
