images:
  image:
    repository: ghcr.io/getarcaneapp/manager
    tag: "v2.15.1@sha256:540c01198ca3e58dfd398d25c57c8dc241fa7e7f3d1d8d646c8268f19525b1a8"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  arcane_container_name: arcane
  perms_container_name: permissions
  notes_body: |
    Default credentials:
    - User: arcane
    - Password: arcane-admin
