images:
  image:
    repository: ghcr.io/karakeep-app/karakeep
    tag: "0.33.2@sha256:b069e4307dec06ea06d16989c6861c30a1ff208568be44ed5fb5d422cd3e950c"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  meilisearch_image:
    repository: getmeili/meilisearch
    tag: "v1.54.3@sha256:e68913ab7d6f5b159529e472cfd362ce3c741fafd3c127961b2142abbe41b3c9"
  chrome_image:
    repository: ghcr.io/karakeep-app/karakeep-chrome
    tag: "151.0.7922.47-r1@sha256:5b19bbb160e9ff60681a3abd97e1c4ec9f64212301410de658c3900ab7ef31e7"

consts:
  karakeep_container_name: karakeep
  meilisearch_container_name: meilisearch
  chrome_container_name: chrome
  perms_container_name: permissions
  chrome_port: 9222
  data_path: /data
  run_user: 568
  run_group: 568
