app_version: 2.6.9
capabilities: []
categories:
- productivity
changelog_url: https://github.com/wallabag/wallabag/releases
date_added: '2026-05-22'
description: wallabag is a read-it-later application. It saves a web page by keeping content only. Elements like navigation or ads are deleted.
home: https://wallabag.org/
host_mounts: []
icon: https://doc.wallabag.org/img/wallabag.png
keywords:
- productivity
- read-it-later
- bookmarks
lib_version: 2.3.5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: wallabag
run_as_context:
- description: Container [wallabag] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/wallabag/wallabag
title: wallabag
train: community
version: 1.0.0
