images:
  image:
    repository: wallabag/wallabag
    tag: "2.6.9"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  wallabag_container_name: wallabag
  perms_container_name: permissions
  internal_web_port: 80
  data_path: /var/www/wallabag/data
  images_path: /var/www/wallabag/web/assets/images
