#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "pgadmin": {
            "admin_email": config["pgadminConfig"].get("adminEmail", ""),
            "admin_password": config["pgadminConfig"].get("adminPassword", ""),
            "additional_envs": config["pgadminConfig"].get("additionalEnvs", []),
        },
        "network": {
            "host_network": config["pgadminNetwork"].get("hostNetwork", False),
            "web_port": config["pgadminNetwork"].get("webPort", 20910),
            "certificate_id": config["pgadminNetwork"].get("certificateID", None),
        },
        "storage": {
            "config": migrate_storage_item(config["pgadminStorage"]["config"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["pgadminStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
