resources:
  limits:
    cpus: 4.0
    memory: 8192

TZ: Etc/UTC

consts:
  run_as_user: 568
  run_as_group: 568
  perms_container_name: "perms"
  data_path: "/app/data"
  logs_path: "/app/logs"
  ssh_path: "/app/.ssh"
  huggingface_path: "/app/.cache/huggingface"
  local_path: "/app/.local"
  chromadb_path: "/chroma/chroma"
  ntfy_path: "/var/cache/ntfy"

odysseus:
  image_selector: image
  searxng_instance: http://searxng:8080
  use_local_searxng: true
  secure_cookies: false
  additional_envs: []

images:
  chromadb_image:
    repository: docker.io/chromadb/chroma
    tag: latest
  ntfy_image:
    repository: docker.io/binwiederhier/ntfy

chromadb:
  anonymized_telemetry: false

network:
  web_port:
    bind_mode: published
    port_number: 7000
  ntfy_port:
    bind_mode: published
    port_number: 8091
  host_network: false

ix_volumes:
  data: /opt/tests/mnt/odysseus/data
  logs: /opt/tests/mnt/odysseus/logs
  ssh: /opt/tests/mnt/odysseus/ssh
  huggingface: /opt/tests/mnt/odysseus/huggingface
  local: /opt/tests/mnt/odysseus/local
  chromadb: /opt/tests/mnt/odysseus/chromadb
  ntfy: /opt/tests/mnt/odysseus/ntfy
  searxng: /opt/tests/mnt/odysseus/searxng

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  logs:
    type: ix_volume
    ix_volume_config:
      dataset_name: logs
      create_host_path: true
  ssh:
    type: ix_volume
    ix_volume_config:
      dataset_name: ssh
      create_host_path: true
  huggingface:
    type: ix_volume
    ix_volume_config:
      dataset_name: huggingface
      create_host_path: true
  local:
    type: ix_volume
    ix_volume_config:
      dataset_name: local
      create_host_path: true
  chromadb:
    type: ix_volume
    ix_volume_config:
      dataset_name: chromadb
      create_host_path: true
  ntfy:
    type: ix_volume
    ix_volume_config:
      dataset_name: ntfy
      create_host_path: true
  searxng:
    type: ix_volume
    ix_volume_config:
      dataset_name: searxng
      create_host_path: true
  additional_storage: []
