images:
  image:
    repository: ghcr.io/corsfix/corsfix-app
    tag: 8899bb15e71c7238285ccefc4c95a0cd47daeaf0
  proxy_image:
    repository: ghcr.io/corsfix/corsfix-proxy
    tag: 8899bb15e71c7238285ccefc4c95a0cd47daeaf0
  mongodb_image:
    repository: mongo
    tag: 8.0.17
  redis_image:
    repository: redis
    tag: 7.4.11-alpine
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  app_container_name: app
  proxy_container_name: proxy
  mongodb_container_name: mongodb
  redis_container_name: redis
  perms_container_name: permissions
  mongodb_user: corsfix
  mongodb_database: db
  app_port: 3000
  proxy_port: 80

run_as:
  user: 568
  group: 568
