services:
  hashcat:
    image: hikage/cuda-hashcat-john:latest
    container_name: hashcat
    restart: unless-stopped
    user: "568:568"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - HASHCAT_MODE=0
      - HASHCAT_WORKLOAD=3
    ports:
      - "2222:22"
    volumes:
      - workspace:/workspace
    deploy:
      resources:
        reservations:
          memory: 4G