resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: America/New_York

netbird:
  mgmt_address: "http://localhost:8081"
  dashboard_address: "http://localhost:8080"
  # openssl rand -base64 32
  store_encryption_key: vJ1ExxP2gTzdYKuEShJXjWdRJb8Ir/ks4U3Y4ykPB8g=
  #  openssl rand -base64 32 | sed s/=//g
  auth_secret: "Z49jp/BX/e6YTZSl1DvqfpdxA1BpY5NKvJcHcyNYw8A"
  embedded_idp: true
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    port_number: 8080
    bind_mode: "published"
  mgmt_port:
    port_number: 8081
    bind_mode: "published"
  stun_port:
    port_number: 8082
    bind_mode: "published"

ix_volumes:
  config: /opt/tests/mnt/netbird/config
  data: /opt/tests/mnt/netbird/data

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
