#!/usr/bin/python3

if __name__ == "__main__":
    raise Exception(
        "Cannot upgrade to v2, please re-install the app from the catalog, "
        "pointing the data storage to the one you used before. This should "
        "allow the app to migrate from SQLite to Postgres automatically."
    )
