images:
  image:
    repository: kimai/kimai2
    tag: "apache-2.57.0@sha256:efa66c5eadf948b94d8031e9436feae491d90b2ceaa3d5e45e4d7c1a59dd8c38"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  mariadb_image:
    repository: mariadb
    tag: "13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"

consts:
  kimai_container_name: kimai
  mariadb_container_name: mariadb
  perms_container_name: permissions
  db_user: kimai
  db_name: kimai
  internal_web_port: 8001
