app_version: 16.3.0
capabilities: []
categories:
- games
changelog_url: https://github.com/Phalcode/gamevault-backend/releases
date_added: '2026-04-29'
description: The self-hosted gaming platform for your DRM-free collection. Host your
  own library, track your stats, and share the experience with friends. It's like
  having your own personal Steam, but you're the one in control
home: https://gamevau.lt/
host_mounts: []
icon: https://media.sys.truenas.net/apps/game-vault/icons/icon.png
keywords:
- gaming
- platform
lib_version: 2.3.4
lib_version_hash: 2e3a8847308fb2eb0da046018f287c73822c094b5950a10377c3235794ff1242
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: vaultwarden
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [vaultwarden] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://gamevau.lt/
- https://github.com/Phalcode/gamevault-backend
title: GameVault
train: community
version: 1.0.0
