images:
  image:
    repository: ghcr.io/phalcode/gamevault-backend
    tag: 16.3.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.7

consts:
  game_vault_container_name: game-vault
  postgres_container_name: postgres
  perms_container_name: permissions
  ssl_key_path: /certs/ssl.key
  ssl_cert_path: /certs/ssl.cert
  db_user: game-vault
  db_name: game-vault

  savefiles_path: /savefiles
  media_path: /media
  files_path: /files
  config_path: /config
  plugins_path: /plugins
