images:
  image:
    repository: ghcr.io/tinyauthapp/tinyauth
    tag: "v5.2.0@sha256:220aa235c76393a73fece831d7ba967b8698d3907fd8e3c4c952f699c7b142a5"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  tinyauth_container_name: tinyauth
  perms_container_name: permissions
  data_base_path: /data
