app_version: 1.3.0
capabilities: []
categories:
- security
changelog_url: https://github.com/ans-ib/keeyo/releases
date_added: '2026-08-21'
description: Keeyo is a self-hosted inventory for your hardware security keys - track
  which key holds which passkey, 2FA registration and TOTP.
home: https://ans-ib.github.io/keeyo/
host_mounts: []
icon: https://media.sys.truenas.net/apps/keeyo/icons/icon.png
keywords:
- security
- fido2
- webauthn
- yubikey
- passkeys
- inventory
lib_version: 2.3.11
lib_version_hash: 874636814efb275e5276ea9d709b7cd665fed42bb1d50328e853d9253a2e1229
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: keeyo
run_as_context:
- description: Container [keeyo] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://ans-ib.github.io/keeyo/
- https://apps.truenas.com/catalog/keeyo_community/
- https://github.com/ans-ib/keeyo
- https://github.com/ans-ib/keeyo/pkgs/container/keeyo
title: Keeyo
train: community
version: 1.0.1
