images:
  image:
    repository: captdany/kestrel
    tag: 0.1.0
  playwright_image:
    repository: captdany/kestrel-scraper
    tag: 0.1.0

consts:
  kestrel_container_name: kestrel
  scraper_container_name: kestrel-scraper
  perms_container_name: permissions
  run_as_user: 568
  run_as_group: 568
