#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    tmdb_api_key = values["ratelog"].pop("tmdb_api_key", "")
    if not tmdb_api_key:
        return values

    additional_envs = values["ratelog"].get("additional_envs", [])
    additional_envs.append({"name": "TMDB_API_KEY", "value": tmdb_api_key})
    values["ratelog"]["additional_envs"] = additional_envs

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
