app_version: 7.4.9-ubuntu
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/zabbix/zabbix-docker/releases
date_added: '2026-03-10'
description: The universal, open-source observability solution for IT & OT
home: https://www.zabbix.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/zabbix/icons/icon.svg
keywords:
- monitoring
- zabbix
lib_version: 2.3.4
lib_version_hash: 2e3a8847308fb2eb0da046018f287c73822c094b5950a10377c3235794ff1242
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: zabbix
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [server] runs as non-root user and group.
  gid: 1997
  group_name: Host group is [unknown (1997)]
  uid: 1997
  user_name: Host user is [unknown (1997)]
- description: Container [web] runs as non-root user and group.
  gid: 1997
  group_name: Host group is [unknown (1997)]
  uid: 1997
  user_name: Host user is [unknown (1997)]
- description: Container [web-service] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/zabbix/zabbix-docker
title: Zabbix
train: community
version: 1.0.10
