resources:
  limits:
    cpus: 2
    memory: 4096

restic_manager:
  log_level: INFO
  log_format: text
  upstream_trusted_address: ""

network:
  web_port:
    bind_mode: published
    port_number: 39080
    host_ips: []

ix_volumes:
  data: /opt/tests/mnt/restic-manager-data
  cache: /opt/tests/mnt/restic-manager-cache

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  cache:
    type: ix_volume
    ix_volume_config:
      dataset_name: cache
      create_host_path: true
