#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    port = 28967
    if not values["network"]["host_network"]:
        port = values["network"]["p2p_port"]["port_number"]
    values["storj"]["domain_address"] = f"{values['storj']['domain_address']}:{port}"

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
