#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    new_ports = []
    for port in values.get("ports", []):
        new_ports.append(
            {
                "bind_mode": "published",
                "port_number": port["published"],
                "container_port": port["target"],
                "protocol": port["protocol"],
                "host_ips": [],
            }
        )

    values["ports"] = new_ports

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
