resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

gluetun:
  vpn_service_provider: custom
  vpn_type: wireguard
  openvpn_user: fake-openvpn-user
  openvpn_password: fake-openvpn-password
  wireguard_private_key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
  wireguard_addresses:
    - address: 10.123.0.2/32
  wireguard_endpoint_ip: 203.0.113.10
  wireguard_endpoint_port: 51820
  wireguard_public_key: AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE=
  wireguard_preshared_key: AgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgI=
  updater_period: ""
  additional_envs:
    - name: HEALTH_TARGET_ADDRESSES
      value: 127.0.0.1:8000
    - name: HEALTH_ICMP_TARGET_IPS
      value: 127.0.0.1
    - name: HEALTH_RESTART_VPN
      value: "off"

network:
  host_network: false
  control_port:
    bind_mode: published
    port_number: 30471
  http_proxy_port:
    bind_mode: published
    port_number: 30472
  shadowsocks_tcp_port:
    bind_mode: published
    port_number: 30473
  shadowsocks_udp_port:
    bind_mode: published
    port_number: 30474

ix_volumes:
  data: /opt/tests/mnt/gluetun/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
