images:
  image:
    repository: jjdenhertog/spotify-to-plex
    tag: 1.0.104

consts:
  app_container_name: spotify-to-plex
  internal_web_port: 9030
  plex_app_id: eXf+f9ktw3CZ8i45OY468WxriOCtoFxuNPzVeDcAwfw=
  spotify_api_redirect_uri: https://jjdenhertog.github.io/spotify-to-plex/callback.html
