images:
  image:
    repository: registry.gitlab.com/storyteller-platform/storyteller
    tag: "web-v2.14.23@sha256:1ae16005572519f56abac2d65ab879d20115cd257fde7e89cf739ea82aed4de3"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  storyteller_container_name: storyteller
  perms_container_name: permissions
  data_path: /data
