images:
  image:
    repository: chrislusf/seaweedfs
    tag: "4.48@sha256:4e61d15fd35994cb1e43e1e553dff106794841fd9a99ade2fc8c8bfce4d7872d"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  seaweedfs_container_name: seaweedfs
  perms_container_name: permissions
  data_path: /data
