#!/usr/bin/python3

import os
import sys
import yaml
import secrets
import base64


def migrate(values):
    random_bytes = secrets.token_bytes(64)
    values["vitransfer"]["share_token_secret"] = base64.b64encode(random_bytes).decode("utf-8")

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
