#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config.get("TZ", "Etc/UTC"),
        "jellyfin": {
            "additional_envs": config["jellyfinConfig"].get("additionalEnvs", []),
            "publish_server_url": config["jellyfinConfig"].get("publishServerUrl", ""),
        },
        "run_as": {
            "user": config["jellyfinRunAs"].get("user", 568),
            "group": config["jellyfinRunAs"].get("group", 568),
        },
        "network": {
            "host_network": config["jellyfinNetwork"].get("hostNetwork", False),
            "web_port": config["jellyfinNetwork"].get("webPort", 30013),
        },
        "storage": {
            "config": migrate_storage_item(config["jellyfinStorage"]["config"]),
            "cache": migrate_storage_item(config["jellyfinStorage"]["cache"]),
            "transcodes": migrate_storage_item(config["jellyfinStorage"]["transcodes"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["jellyfinStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"], config["jellyfinGPU"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
