images:
  image:
    repository: ghcr.io/snapotter-hq/snapotter
    tag: 2.1.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  redis_image:
    repository: valkey/valkey
    tag: 9.1.0
  postgres_18_image:
    repository: postgres
    tag: 18.4-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.11

consts:
  snapotter_container_name: snapotter
  redis_container_name: redis
  postgres_container_name: postgres
  perms_container_name: permissions
  data_path: /data
  workspace_path: /tmp/workspace

  db_user: snapotter
  db_name: snapotter
