#!/usr/bin/python3

import os
import sys
import yaml
import secrets


def migrate(values):
    values["invidious"]["companion_key"] = secrets.token_hex(16)[:16]

    values["invidious"].pop("visitor_data")
    values["invidious"].pop("po_token")
    values["invidious"].pop("enable_inv_sig_helper")

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
