images:
  image:
    repository: ghcr.io/dgtlmoon/changedetection.io
    tag: "0.60.8@sha256:34df3680db1cbffc45ac1e9c1514bc0507dd0c5b5fde47d1992fe6f14a7b40e4"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  change_detection_container_name: change-detection
  perms_container_name: permissions
