app_version: 2.4.0
capabilities:
- description: Gameyfin is able to change file ownership arbitrarily
  name: CHOWN
- description: Gameyfin is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Gameyfin is able to bypass permission checks for file operations
  name: FOWNER
- description: Gameyfin is able to change group ID of processes
  name: SETGID
- description: Gameyfin is able to change user ID of processes
  name: SETUID
categories:
- games
changelog_url: https://github.com/gameyfin/gameyfin/releases
date_added: '2026-05-07'
description: Gameyfin will turn your disorganized collection of video games into a
  beautiful, easy-to-navigate library that you can access from any device with a web
  browser.
home: https://gameyfin.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/gameyfin/icons/icon.svg
keywords:
- games
lib_version: 2.3.5
lib_version_hash: c0d042e3de6350fae9aee546d3c79bc0accf1f2011da89cc1ebff29421aa7fc9
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: gameyfin
run_as_context:
- description: Container [gameyfin] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://github.com/gameyfin/gameyfin
- https://gameyfin.org/
title: Gameyfin
train: community
version: 1.0.1
