app_version: 3.6.9
capabilities: []
categories:
- networking
changelog_url: https://github.com/traefik/traefik/releases
date_added: '2026-03-06'
description: The Cloud Native Application Proxy
home: https://traefik.io/
host_mounts:
- description: Docker socket
  host_path: /var/run/docker.sock
icon: https://media.sys.truenas.net/apps/traefik/icons/icon.svg
keywords:
- networking
- reverse-proxy
lib_version: 2.2.8
lib_version_hash: 76b40b42163deb26edbad5f973f1bd69b68bd85625bcd8247545194d99b9f912
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: traefik
run_as_context:
- description: Container [traefik] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://doc.traefik.io/
- https://github.com/traefik/traefik
title: Traefik
train: community
version: 1.0.0
