images:
  image:
    repository: ghcr.io/linuxserver/lazylibrarian
    tag: "061e07d8-ls358@sha256:704be75eebd3097400e566d11026d4e26320e13e3e4d54d8dbd6b6acd9bdb53a"

consts:
  lazylibrarian_container_name: lazylibrarian
  internal_web_port: 5299
