resources:
  limits:
    cpus: 2.0
    memory: 4096

ultra_explorer:
  admin_password: synthetic-test-password
  secure_cookies: false
  local_roots:
    - /mnt/local
    - /mnt/archive
  additional_envs: []
network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 8080

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/data
  media: /opt/tests/mnt/media
  certs: /opt/tests/mnt/certs

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage:
    - mount_path: /mnt/local
      type: ix_volume
      ix_volume_config:
        dataset_name: media
        create_host_path: true
    - mount_path: /mnt/archive
      type: host_path
      read_only: true
      host_path_config:
        path: /opt/tests/mnt/archive
        create_host_path: true
    - mount_path: /certs
      type: ix_volume
      ix_volume_config:
        dataset_name: certs
        create_host_path: true
