resources:
  limits:
    cpus: 2.0
    memory: 1024

TZ: Etc/UTC

matterjs:
  log_level: info
  log_file: ""
  primary_interface: ""
  listen_address: ""
  production_mode: false
  disable_dashboard: false
  vendor_id: ""
  fabric_id: ""
  dcl:
    enable_test_net_dcl: false
    disable_dcl_seed: false
  ota:
    disable_ota: false
    enable_provider: false
  ble:
    bluetooth_adapter: ""
    ble_proxy: false
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  host_network: false
  additional_ports: []
  web_port:
    bind_mode: published
    port_number: 35580

ix_volumes:
  data: /opt/tests/mnt/matterjs/data
  ota: /opt/tests/mnt/matterjs/ota

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  ota:
    type: ix_volume
    ix_volume_config:
      dataset_name: ota
      create_host_path: true
  additional_storage: []
