images:
  image:
    repository: ghcr.io/amruthpillai/reactive-resume
    tag: v5.0.16
  chromedp_image:
    repository: chromedp/headless-shell
    tag: 148.0.7766.3
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.4

consts:
  reactive_resume_container_name: reactive-resume
  chromedp_container_name: chromedp
  postgres_container_name: postgres
  perms_container_name: permissions
  db_user: reactive_resume
  db_name: reactive_resume
  chromedp_port: 9222
