#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if values["terraria"].get("image_selector", "") == "image":
        raise Exception("In order to use TShock, please migrate to the new dedicate Terraria TShock app.")

    values["terraria"].pop("image_selector", None)
    values["network"].pop("tshock_api_port", None)

    values["storage"].pop("plugins", None)

    values["terraria"]["world_file_name"] = values["terraria"]["world_name"] + ".wld"
    values["terraria"].pop("world_name", None)

    diff = values["terraria"]["world_difficulty"]
    if diff == "normal":
        values["terraria"]["world_difficulty"] = "0"
    elif diff == "expert":
        values["terraria"]["world_difficulty"] = "1"
    elif diff == "master":
        values["terraria"]["world_difficulty"] = "2"
    elif diff == "journey":
        values["terraria"]["world_difficulty"] = "3"
    else:
        raise Exception(f"Unknown world difficulty [{diff}]")

    size = values["terraria"]["world_size"]
    if size == "small":
        values["terraria"]["world_size"] = "1"
    elif size == "medium":
        values["terraria"]["world_size"] = "2"
    elif size == "large":
        values["terraria"]["world_size"] = "3"
    else:
        raise Exception(f"Unknown world size [{size}]")

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
