images:
  image:
    repository: borgwarehouse/borgwarehouse
    tag: "v3.7.0@sha256:3a41ea9d0dd5cbe03fa184a0704dbac0e9574adb235b46b52f049dca59a0a50e"
  cron_image:
    repository: ixsystems/cron
    tag: "1.0.10@sha256:9402c7ab452b2400491180017305667196d9257bfa2aaf75848954837de9d5c5"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  borgwarehouse_container_name: borgwarehouse
  borgwarehouse_cron_container_name: cron
  perms_container_name: permissions

  internal_ssh_port: 22
  internal_web_port: 3000

  notes_body: |
    Default credentials:
    - Username: `admin`
    - Password: `admin`
