annotations:
  min_scale_version: 24.10.2.2
app_version: RELEASE.2026-06-06T02-44-06Z
capabilities: []
categories:
- storage
date_added: '2024-08-15'
description: High Performance, Kubernetes Native Object Storage
home: https://min.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/minio/icons/icon.png
keywords:
- object storage
- minio
- cloud
- s3
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: minio
run_as_context:
- description: Container [minio] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/minio/screenshots/screenshot3.png
sources:
- https://apps.truenas.com/catalog/minio_enterprise/
- https://docs.min.io/enterprise/aistor-object-store/installation/container/install/
- https://github.com/minio/minio
title: AIStor
train: enterprise
version: 1.3.18
