images:
  image:
    repository: quay.io/minio/aistor/minio
    tag: RELEASE.2026-09-19T17-05-25Z
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  aistor_container_name: aistor
  perms_container_name: permissions
  license_path: /minio.license
