stlquest:
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: published
    port_number: 30058
    host_ips: []
  host_network: false

storage:
  data:
    type: host_path
    host_path_config:
      path: /opt/tests/stlquest-data
      acl_enable: false
      auto_permissions: true
      create_host_path: true
  prints:
    type: host_path
    host_path_config:
      path: /opt/tests/stlquest-prints
      acl_enable: false
      auto_permissions: true
      create_host_path: true

labels: []

resources:
  limits:
    cpus: 2
    memory: 4096
