resources:
  limits:
    cpus: 2.0
    memory: 4096

psono:
  image_selector: ce_image
  postgres_image_selector: postgres_18_image
  db_password: psono1234
  base_url: http://127.0.0.1:8080
  service_name: Psono
  server_keys:
    secret_key: cd91d5bcf2ba0e1a3f39a2e9f4b06d5c8a17d2e0b9c34f6a8d1e5b7c0f2a4d69
    activation_link_secret: 7f2b9c4e1a6d8035b7e0c2f4a9d16b83e5c7a0d2f4b6981c3e5a7d9f0b2c4e68
    db_secret: 3a8f1c5e7b9d024680acbdef1357924680bdf13579ace2468bdf0246813579ac
    email_secret_salt: "$2b$12$XUG.sKxC2jmkUvWQjg53.e"
    private_key: 302650c3c82f7111c2e8ceb660d32173cdc8c3d7717f1d4f982aad5234648fcb
    public_key: 02da2ad857321d701d754a7e60d0a147cdbc400ff4465e1f57bc2d9fbfeddf0b
  allowed_domains:
    - example.com
  allowed_hosts:
    - "*"
  management_enabled: true
  num_proxies: null
  auth:
    authentication_methods:
      - AUTHKEY
    allowed_second_factors:
      - google_authenticator
      - webauthn
    multifactor_enabled: false
    allow_registration: true
    registration_email_filter: []
    allow_lost_password: true
    allow_custom_server: false
    enforce_matching_username_and_email: false
    allow_user_search_by_email: false
    allow_user_search_by_username_partial: false
    disable_last_passwords: 0
    yubikey:
      client_id: ""
      secret_key: ""
    duo:
      integration_key: ""
      secret_key: ""
      api_hostname: ""
  smtp:
    enabled: false
    email_from: psono@example.com
    host: ""
    port: 587
    encryption: starttls
    username: ""
    password: ""
    subject_prefix: ""
  cache:
    type: none
    redis_password: ""
    throttling: true
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080
  networks: []

ix_volumes:
  pg_data: /opt/tests/mnt/pg_data

storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: pg_data
      create_host_path: true
  additional_storage: []
