images:
  image:
    repository: 1password/connect-api
    tag: "1.8.3@sha256:656e4b10df83ca258d8a75b2a051f7c06dd608212f8ae5ba4722e3fe164099d3"
  sync_image:
    repository: 1password/connect-sync
    tag: "1.8.3@sha256:a760350c941a3e7c98dd66394e9fc3c7e68b6a0a2246a837c74084e534f75f6b"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  api_container_name: api
  sync_container_name: sync
  perms_container_name: permissions
  home_dir: /home/opuser/
  data_dir: /home/opuser/.op/data
  bus_port: 11223

  run_as_user: 999
  run_as_group: 999
