#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "odoo": {
            "additional_envs": config["odooConfig"].get("additionalEnvs", []),
            "additional_conf": config["odooConfig"].get("additionalConf", []),
            "db_password": get_value_from_secret(
                k8s_secrets, "postgres-creds", "POSTGRES_PASSWORD"
            ),
        },
        "network": {
            "web_port": config["odooNetwork"]["webPort"],
        },
        "storage": {
            "data": migrate_storage_item(config["odooStorage"]["data"]),
            "addons": migrate_storage_item(config["odooStorage"]["addons"]),
            "postgres_data": migrate_storage_item(config["odooStorage"]["pgData"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["odooStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
