images:
  image:
    repository: docker.io/snapetech/bookshelfng
    tag: hardcover-v0.4.21.37
  softcover_image:
    repository: docker.io/snapetech/bookshelfng
    tag: softcover-v0.4.21.37

consts:
  bookshelfng_container_name: bookshelfng
