#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if values["opencloud"]["collaboration"]["enabled"]:
        values["opencloud"]["collaboration"]["proof_disable"] = values["opencloud"]["proof_disable"]
    values["opencloud"].pop("proof_disable", None)
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
