images:
  image:
    repository: ghcr.io/tuschla/mediathekview-2-stremio
    tag: "0.1.0@sha256:46dcee298e1c4f38fd75929b48f6c4fe26dd5722099149484adc9746739b541a"

consts:
  mediathek_container_name: mediathek
