images:
  image:
    repository: ghcr.io/tuschla/mediathekview-2-stremio
    tag: "0.1.0@sha256:b5d200e1558a61cb2a6cebce6293a3135af4ab3af8d767be38ef92f752179f63"

consts:
  mediathek_container_name: mediathek
