#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if "run_as" not in values:
        # The default user of the container
        # https://github.com/ShaneIsrael/fireshare/blob/570ab5286cc606bee74d443bba9954b9a6b2f055/entrypoint.sh#L5
        values["run_as"] = {"user": 1000, "group": 1000}
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
