#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    # The deprecated storages were only used by the one-time data migration,
    # their data has already been copied to the Data storage.
    for key in ["remove_deprecated_storage", "avatars", "background_images", "attachments"]:
        values["storage"].pop(key, None)
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
