images:
  image:
    repository: ghcr.io/pocket-id/pocket-id
    tag: "v2.16.0@sha256:9366436f3fd21619ed7e5709fa0acac88130f73414ec8ee1caf768fc487111ea"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  pocket_id_container_name: pocket-id
  perms_container_name: permissions

  data_path: /app/data
