app_version: 0.12.0
capabilities: []
categories:
- backup
changelog_url: https://github.com/CampAsAChamp/truenas-config-backup/blob/main/CHANGELOG.md
date_added: '2026-07-27'
description: Scheduled backups of your TrueNAS system configuration, downloaded via
  the API.
home: https://github.com/CampAsAChamp/truenas-config-backup
host_mounts: []
icon: https://raw.githubusercontent.com/CampAsAChamp/truenas-config-backup/main/ix-dev/community/truenas-config-backup/icon.svg
keywords:
- backup
- config
- truenas
lib_version: 2.3.8
lib_version_hash: d21ab532cc602478624ae2d278538de12eb19f637e305f7c0ec53542979e9d14
maintainers:
- email: nickschneider101@gmail.com
  name: CampAsAChamp
  url: https://github.com/CampAsAChamp
name: truenas-config-backup
run_as_context:
- description: Container [truenas-config-backup] can run as any non-root user and
    group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/CampAsAChamp/truenas-config-backup
- https://github.com/CampAsAChamp/truenas-config-backup/pkgs/container/truenas-config-backup
title: TrueNAS Config Backup
train: community
version: 1.0.0
