images:
  image:
    repository: ghcr.io/jellyfin/jellyfin
    tag: "12.2@sha256:c3efa69a22f2691fc88d6bb035e87a8560e395a6047f062fb381c61c3185e8f5"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  jellyfin_container_name: jellyfin
  perms_container_name: permissions
  internal_web_port: 8096
  internal_https_port: 8920
