images:
  image:
    repository: ghcr.io/pocket-id/pocket-id
    tag: "v2.18.0@sha256:323e7ef5bfacf7cf32f22f3d10ccdf48e0c97c94d67e7e40b0b996830deb5165"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  pocket_id_container_name: pocket-id
  perms_container_name: permissions

  data_path: /app/data
