#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["network"]["broker_port"] = {
        "port_number": values["network"]["broker_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["ws_port"] = {
        "port_number": values["network"].get("ws_port", 8081),
        "bind_mode": "published" if values["network"]["enable_ws"] else "",
        "host_ips": [],
    }
    values["network"].pop("enable_ws", None)

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
