app_version: v2.0.1
capabilities: []
categories:
- productivity
changelog_url: https://github.com/oss-apps/split-pro/releases
date_added: '2026-03-04'
description: SplitPro is an open source alternative to Splitwise for sharing expenses
  with friends and groups.
home: https://github.com/oss-apps/split-pro
host_mounts: []
icon: https://media.sys.truenas.net/apps/split-pro/icons/icon.png
keywords:
- expense
- splitwise
- finance
- budget
- sharing
lib_version: 2.2.8
lib_version_hash: 76b40b42163deb26edbad5f973f1bd69b68bd85625bcd8247545194d99b9f912
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: split-pro
run_as_context:
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [split-pro] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/oss-apps/split-pro
title: SplitPro
train: community
version: 1.0.1
