#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.dns_config import migrate_dns_config
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "wg_easy": {
            "external_host": config["wgConfig"]["host"],
            "external_port": config["wgConfig"]["externalPort"],
            "password": config["wgConfig"]["password"],
            "persistent_keepalive": config["wgConfig"]["keepAlive"],
            "device_name": config["wgConfig"]["deviceName"],
            "client_mtu": config["wgConfig"]["clientMTU"],
            "client_default_address_range": config["wgConfig"]["clientAddressRange"],
            "client_default_dns": config["wgConfig"]["clientDNSServer"],
            "allowed_ips": config["wgConfig"]["allowedIPs"],
            "additional_envs": config["wgConfig"].get("additionalEnvs", []),
        },
        "network": {
            "host_network": config["wgNetwork"].get("hostNetwork", True),
            "web_port": config["wgNetwork"].get("webPort", 30058),
            "udp_port": config["wgNetwork"].get("udpPort", 30057),
            "dns_opts": migrate_dns_config(config["podOptions"].get("dnsConfig", {})),
        },
        "storage": {
            "config": migrate_storage_item(config["wgStorage"]["config"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["wgStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
