#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "pigallery": {
            "application_title": config["pigalleryConfig"].get(
                "applicationTitle", "PiGallery 2"
            ),
            "additional_envs": config["pigalleryConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["pigalleryRunAs"].get("user", 568),
            "group": config["pigalleryRunAs"].get("group", 568),
        },
        "network": {
            "host_network": config["pigalleryNetwork"].get("hostNetwork", False),
            "web_port": config["pigalleryNetwork"].get("webPort", 30099),
        },
        "storage": {
            "config": migrate_storage_item(config["pigalleryStorage"]["config"]),
            "db": migrate_storage_item(config["pigalleryStorage"]["db"]),
            "media": migrate_storage_item(config["pigalleryStorage"]["media"]),
            "thumbnails": migrate_storage_item(config["pigalleryStorage"]["thumbnails"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["pigalleryStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
