resources:
  limits:
    cpus: 4.0
    memory: 8192

trawl:
  browser_pool_size: 6
  proxy_url: ""
  residential_proxy_url: ""
  additional_envs:
    - name: SESSION_TTL_SECONDS
      value: "1800"

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30453
  dns_nameservers:
    - 1.1.1.1
    - 8.8.8.8

ix_volumes:
  extra: /opt/tests/mnt/trawl/extra

storage:
  additional_storage:
    - type: ix_volume
      mount_path: /extra-data
      read_only: false
      ix_volume_config:
        dataset_name: extra
        create_host_path: true
