resources:
  limits:
    cpus: 2.0
    memory: 4096

trawl:
  browser_pool_size: 2
  proxy_url: ""
  residential_proxy_url: ""
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30452
  dns_nameservers:
    - 1.1.1.1
    - 8.8.8.8

storage:
  additional_storage: []
