images:
  image:
    repository: odoo
    tag: "20.0-20260926@sha256:dc76c42d292af9c513de826620e5a5dbe8152383ce8767eb6ed1390a806eb32f"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  postgres_17_image:
    repository: postgres
    tag: "17.11-bookworm@sha256:639ab7ceb90e13123085b741fb31ef493fba25463002f6da665352e7b534b652"
  postgres_18_image:
    repository: postgres
    tag: "18.6-trixie@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722"
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: "1.2.21@sha256:721514696eeb5fedf7818f768e9608d9a3e07ce4551b4c1737faf3f1e6106517"

consts:
  odoo_container_name: odoo
  postgres_container_name: postgres
  perms_container_name: permissions
  data_path: /var/lib/odoo
  addons_path: /mnt/extra-addons
  conf_file_path: /etc/odoo/odoo.conf
  run_as_user: 100
  run_as_group: 101
  db_name: odoo
  db_user: odoo
  reserved_keys:
    - data_dir
    - addons_path
    - http_enable
    - http_interface
    - http_port
    - xmlrpc
    - xmlrpc_port
    - xmlrpc_interface
    - db_port
    - db_host
    - db_name
    - db_user
    - db_sslmode
    - db_password
  notes_body: |
    ## Default Username and Password

    The First time you log into the Odoo UI, use the following credentials.
    You should change them after the first login.

    Username: `admin`
    Password: `admin`
