app_version: 0.97.0
capabilities: []
categories:
- productivity
changelog_url: https://github.com/ulsklyc/yuvomi/releases
date_added: '2026-06-15'
description: Self-hosted family planner - tasks, calendars, shopping, meals, budget.
  Your data, your server.
home: https://github.com/ulsklyc/yuvomi
host_mounts: []
icon: https://media.sys.truenas.net/apps/yuvomi/icons/icon.png
keywords:
- family
- planner
- calendar
- productivity
lib_version: 2.3.6
lib_version_hash: 5067fd69a830797f96075fe2fe08aa41e2ec08d7c94cf5c6d6256690be7e06ae
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: yuvomi
run_as_context:
- description: Container [yuvomi] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/yuvomi/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/yuvomi/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/yuvomi/screenshots/screenshot3.png
- https://media.sys.truenas.net/apps/yuvomi/screenshots/screenshot4.png
- https://media.sys.truenas.net/apps/yuvomi/screenshots/screenshot5.png
sources:
- https://apps.truenas.com/catalog/yuvomi_community/
- https://github.com/ulsklyc/yuvomi
title: Yuvomi
train: community
version: 1.0.18
