resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

agent_hub:
  viewer_password: test-password
  machines:
    - name: work-laptop
      sha256: d6676af886f325a12dad3fac021b4b51d01340fde79740ccde0b3cb588e18f48
      share: full
    - name: home-pc
      sha256: 0f1e2d3c4b5a69788796a5b4c3d2e1f00f1e2d3c4b5a69788796a5b4c3d2e1f0
      share: metadata
  additional_envs: []

network:
  host_network: false
  certificate_id:
  web_port:
    bind_mode: published
    port_number: 8080
  ingest_port:
    bind_mode: published
    port_number: 8081

run_as:
  user: 568
  group: 568

storage:
  additional_storage: []
