resources:
  limits:
    cpus: 2.0
    memory: 4096

truenas_app_icon_manager:
  poll_interval_seconds: 30
  max_icon_size_bytes: 524288
  backup_retention_count: 25
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  config: /opt/tests/mnt/truenas-app-icon-manager/config

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  ix_apps:
    type: host_path
    read_only: false
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/truenas-app-icon-manager/ix-apps
  additional_storage: []
