app_version: 1.0.0
capabilities: []
categories:
  - media
changelog_url: https://github.com/ParsonLabs/Parson/releases
date_added: "2026-07-30"
description: Parson is a local-first music app for your own collection.
home: https://parson.dev
host_mounts: []
icon: https://media.sys.truenas.net/apps/parson/icons/icon.svg
keywords:
  - audio
  - media
  - music
  - self-hosted
  - streaming
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
  - email: dev@truenas.com
    name: truenas
    url: https://www.truenas.com/
name: parson
run_as_context:
  - description: Container [parson] runs as a non-root user and group.
    gid: 10001
    group_name: Host group is [unknown (10001)]
    uid: 10001
    user_name: Host user is [unknown (10001)]
screenshots:
  - https://media.sys.truenas.net/apps/parson/screenshots/screenshot1.png
sources:
  - https://apps.truenas.com/catalog/parson_community/
  - https://github.com/ParsonLabs/Parson
  - https://ghcr.io/parsonlabs/parson
title: Parson
train: community
version: 1.0.0
