#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "metube": {
            "additional_envs": config["metubeConfig"].get("additionalEnvs", []),
            "default_theme": config["metubeConfig"]["defaultTheme"],
        },
        "run_as": {
            "user": config["metubeRunAs"].get("user", 568),
            "group": config["metubeRunAs"].get("group", 568),
        },
        "network": {
            "web_port": config["metubeNetwork"].get("webPort", 32400),
            "host_network": config["metubeNetwork"]["hostNetwork"],
        },
        "storage": {
            "downloads": migrate_storage_item(config["metubeStorage"]["downloads"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["metubeStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
