app_version: "3.3"
capabilities:
- description: zfs-autobackup-init is able to change file ownership arbitrarily
  name: CHOWN
- description: zfs-autobackup-init is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: zfs-autobackup-init is able to bypass permission checks for file operations
  name: FOWNER
- description: zfs-autobackup, zfs-autobackup-init are able to perform system administration operations
  name: SYS_ADMIN
categories:
- backup
changelog_url: https://github.com/psy0rz/zfs_autobackup/releases
date_added: '2026-08-28'
description: zfs-autobackup creates ZFS snapshots on a schedule and replicates them to another pool or to a remote machine over SSH
home: https://github.com/psy0rz/zfs_autobackup
host_mounts: []
icon: https://media.sys.truenas.net/apps/zfs-autobackup/icons/icon.svg
keywords:
- zfs
- backup
- snapshot
- replication
lib_version: 2.3.11
lib_version_hash: 874636814efb275e5276ea9d709b7cd665fed42bb1d50328e853d9253a2e1229
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: zfs-autobackup
run_as_context:
- description: Container [zfs-autobackup] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://apps.truenas.com/catalog/zfs-autobackup_community/
- https://github.com/psy0rz/zfs_autobackup
- https://github.com/patte/zfs-autobackup-docker
title: zfs-autobackup
train: community
version: 1.0.0
