images:
  image:
    repository: ghcr.io/iongpt/boxarr
    tag: "2.1.0@sha256:f4e99515090a2dde550a61beaa0caa6f7e2c31ce2b80ffe8a5f6424059317fad"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  boxarr_container_name: boxarr
  perms_container_name: permissions
