images:
  image:
    repository: ghcr.io/lostb1t/remux
    tag: "0.26.0"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  remux_container_name: remux
  perms_container_name: permissions
  data_dir: /data
