images:
  image:
    repository: ghcr.io/juanfont/headscale
    tag: "v0.29.4@sha256:8833f828b414c0907b7e5c71da76473216fe17cce0818a166b536ec552c0903f"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  alpine_image:
    repository: alpine
    tag: "3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6"

consts:
  headscale_container_name: headscale
  perms_container_name: permissions
  run_path: /var/run/headscale
  lib_path: /var/lib/headscale
  config_path: /etc/headscale
  ssl_key_path: /certs/headscale.key
  ssl_cert_path: /certs/headscale.crt
