app_version: 2.1.1
capabilities: []
categories:
- security
changelog_url: https://github.com/hashicorp/vault/blob/main/CHANGELOG.md
date_added: '2026-09-29'
description: HashiCorp Vault is an identity-based secrets and encryption management
  system.
home: https://www.vaultproject.io
host_mounts: []
icon: https://media.sys.truenas.net/apps/vault/icons/icon.png
keywords:
- secrets
- encryption
- security
- pki
lib_version: 2.3.15
lib_version_hash: 418b1697e018a564438ced4d735f4ced3ea16cc9fa74971a6040e769c80a66e5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: vault
run_as_context:
- description: Container [audit-forwarder] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [vault] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/hashicorp/vault
- https://hub.docker.com/r/hashicorp/vault
title: Vault
train: community
version: 1.0.0
