images:
  image:
    repository: hashicorp/vault
    tag: "2.1.1@sha256:47f14a6acb98f48d798a07df7c83f23a6e636e1cf724c5f8ff165cb32667a1e2"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  vault_container_name: vault
  perms_container_name: permissions
  config_path: /vault/config/config.hcl
  data_path: /vault/data
  cluster_port: 8201
  ssl_key_path: /vault/certs/tls.key
  ssl_cert_path: /vault/certs/tls.crt
