images:
  image:
    repository: hashicorp/vault
    tag: "2.1.1@sha256:47f14a6acb98f48d798a07df7c83f23a6e636e1cf724c5f8ff165cb32667a1e2"
  fluent_bit_image:
    repository: ghcr.io/fluent/fluent-bit
    tag: "5.1.2@sha256:d792375ca8e53be72fc25716c28f291f32c6fc6f4f31d12d0d14bc78cefe9226"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  vault_container_name: vault
  perms_container_name: permissions
  audit_forwarder_container_name: audit-forwarder
  config_path: /vault/config/config.hcl
  data_path: /vault/data
  audit_path: /vault/audit
  audit_file: vault-audit.log
  fluent_bit_config_path: /fluent-bit/etc/vault-audit.yaml
  peer_ca_cert_path: /vault/certs/peer-ca.crt
  ssl_key_path: /vault/certs/tls.key
  ssl_cert_path: /vault/certs/tls.crt
