images:
  image:
    repository: alexta69/metube
    tag: "2026.09.28@sha256:04608d1df751c523db1d3d15c05301cdb6f3cbcaab7c04d3967f1627dffa80be"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  metube_container_name: metube
  perms_container_name: permissions
  downloads_path: /downloads
