images:
  image:
    repository: ghcr.io/louislam/uptime-kuma
    tag: "2.5.6@sha256:9912da7d7d9b6ddc0c2d904beb84d24689c1ed9c33b81419eb9008663a92a329"

consts:
  uptime_kuma_container_name: uptime-kuma
