images:
  image:
    repository: ghcr.io/koush/scrypted
    tag: "v0.147.0-noble-full@sha256:e78b4fcecdd6c61acaaf22b50ccef303c738da58cc0be57afdb116521df52296"
  nvidia_image:
    repository: ghcr.io/koush/scrypted
    tag: "v0.147.0-noble-nvidia@sha256:9ce2dcce0b0fd33e9d8363dd2f290c99402d28be8c7f41d309be8c0be69ee37b"
  lite_image:
    repository: ghcr.io/koush/scrypted
    tag: "v0.147.0-noble-lite@sha256:6e4ee79727c35eea14d6326b994fbb5b3e1137426449d2d8a9b4fed4d1f51bba"

consts:
  scrypted_container_name: scrypted
