images:
  image:
    repository: ghcr.io/nicotsx/zerobyte
    tag: "v0.43.1@sha256:a3c3a6f0b1936b1bfefeed92eee7213d7bb694915c8c064f5643fc3bdf5ad5e1"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  zerobyte_container_name: zerobyte
  perms_container_name: permissions
  internal_web_port: 4096
