TZ: Etc/UTC

optical:
  block_device: /dev/null
  sg_device: /dev/null

network:
  web_port:
    bind_mode: published
    port_number: 30475
    host_ips: []

storage:
  music:
    type: host_path
    host_path_config:
      acl_enable: false
      path: /opt/tests/mnt/actuallyfreecd/music

output:
  uid: -1
  gid: -1
  directory_mode: "0775"
  file_mode: "0664"

resources:
  limits:
    cpus: 2
    memory: 2048

ix_volumes: {}
