#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "tftpd": {
            "allow_create": config["tftpConfig"].get("allowCreate", True),
            "additional_envs": config["tftpConfig"].get("additionalEnvs", []),
        },
        "network": {
            "host_network": config["tftpNetwork"].get("hostNetwork", False),
            "tftp_port": config["tftpNetwork"].get("tftpPort", 69),
        },
        "storage": {
            "tftpboot": migrate_storage_item(config["tftpStorage"]["tftpboot"]),
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
