resources:
  limits:
    cpus: 2.0
    memory: 4096

ci: true

TZ: Etc/UTC

naswarden:
  truenas_host: truenas.example.com:443
  truenas_api_key: test-api-key
  truenas_tls: true
  truenas_insecure_tls: true
  docker_stats: true
  incus_url: ""
  incus_client_cert: ""
  incus_client_key: ""
  incus_insecure_tls: true
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 8080

run_as:
  user: 568
  group: 568

storage:
  additional_storage: []
