images:
  image:
    repository: zabbix/zabbix-server-pgsql
    tag: 7.4.8-ubuntu
  web_image:
    repository: zabbix/zabbix-web-nginx-pgsql
    tag: 7.4.8-ubuntu
  web_service_image:
    repository: zabbix/zabbix-web-service
    tag: 7.4.8-ubuntu
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.1

consts:
  server_container_name: server
  web_container_name: web
  web_service_container_name: web-service
  postgres_container_name: postgres
  perms_container_name: permissions
  db_user: zabbix
  db_name: zabbix

  internal_web_port: 8080
  internal_web_service_port: 8081

  run_as_user: 1997
  run_as_group: 1997

  notes_body: |
    Default credentials:
    - Username: `Admin`
    - Password: `zabbix`
