images:
  image:
    repository: ghcr.io/journeydocker/plex-auto-languages
    tag: "1.6.1@sha256:51224217f7a036e93ba0153d1c03d54b174d0fd9099f3e8873ee702b28bac23f"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  plex_auto_languages_container_name: plex-auto-languages
  perms_container_name: permissions
  internal_port: 9880
