images:
  image:
    repository: ghcr.io/lldap/lldap
    tag: "v0.6.3-alpine-rootless@sha256:ba2c50930ea998eefd5454aa678a7977448019248b1827da87d330df0b71c284"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  lldap_container_name: lldap
  perms_container_name: permissions
  ldaps_ssl_cert_path: /certs/cert.pem
  ldaps_ssl_key_path: /certs/key.pem
