images:
  image:
    repository: bpatrik/pigallery2
    tag: "3.5.2@sha256:d7a61b6daa410537064d4f661122545bc4d9b16cd91a3862d654c3555cb63992"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  pigallery_container_name: pigallery
  perms_container_name: permissions
  thumbnails_path: /app/data/thumbnails
  media_path: /app/data/media
  db_path: /app/data/db
  notes_body: |
    Default credentials:
      - Username: `admin`
      - Password: `admin`
