resources:
  limits:
    cpus: 4.0
    memory: 8192

TZ: Etc/UTC

prowler:
  db_password: prowlertest
  valkey_password: prowlertest
  neo4j_password: prowlertest
  django_secrets_encryption_key: "zDOCb2yTHBy_l4UQOZRWmFazVsTNIY8ggjCXxPgZxYA="
  ui_auth_secret: prowlertestsecret
  django_logging_level: INFO
  additional_envs: []

network:
  ui_port:
    bind_mode: published
    port_number: 30490
  api_port:
    bind_mode: published
    port_number: 30491
  mcp_port:
    bind_mode: exposed
    port_number: 30492

ix_volumes:
  api_config: /opt/tests/mnt/prowler/api-config
  api_output: /opt/tests/mnt/prowler/api-output
  postgres_data: /opt/tests/mnt/prowler/postgres-data
  valkey_data: /opt/tests/mnt/prowler/valkey-data
  neo4j_data: /opt/tests/mnt/prowler/neo4j-data

storage:
  api_config:
    type: ix_volume
    ix_volume_config:
      dataset_name: api_config
      create_host_path: true
  api_output:
    type: ix_volume
    ix_volume_config:
      dataset_name: api_output
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  valkey_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: valkey_data
      create_host_path: true
  neo4j_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: neo4j_data
      create_host_path: true
  additional_storage: []

labels: []
