images:
  image:
    repository: ghcr.io/mrtian2016/yunkan-cpu
    tag: 0.9.49
  openvino_image:
    repository: ghcr.io/mrtian2016/yunkan-openvino
    tag: 0.9.49
  cuda_image:
    repository: ghcr.io/mrtian2016/yunkan-cuda
    tag: 0.9.49
  tensorrt_image:
    repository: ghcr.io/mrtian2016/yunkan-trt
    tag: 0.9.49

consts:
  yunkan_container_name: yunkan
  internal_web_port: 23406
  internal_webrtc_port: 23515
  machine_id_path: /etc/machine-id
  product_uuid_path: /sys/class/dmi/id/product_uuid
