annotations:
  min_scale_version: 24.10.2.2
app_version: 1.1.2
capabilities: []
categories:
- media
changelog_url: https://github.com/Daddelgreis74/rtsp-stream-hub/releases
date_added: '2026-08-19'
description: Lightweight web application to manage, discover via ONVIF, and transcode
  RTSP camera streams into browser-compatible MJPEG.
home: https://github.com/Daddelgreis74/rtsp-stream-hub
host_mounts: []
icon: https://media.sys.truenas.net/apps/rtsp-stream-hub/icons/icon.svg
keywords:
- camera
- rtsp
- mjpeg
- streaming
- security
- onvif
- smarthome
lib_version: 2.3.11
lib_version_hash: 874636814efb275e5276ea9d709b7cd665fed42bb1d50328e853d9253a2e1229
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: rtsp-stream-hub
run_as_context:
- description: Container [rtsp-stream-hub] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/rtsp-stream-hub_community/
- https://ghcr.io/daddelgreis74/rtsp-stream-hub
- https://github.com/Daddelgreis74/rtsp-stream-hub
title: RTSP Stream Hub
train: community
version: 1.0.0
