app_version: v0.71.0
capabilities: []
categories:
- networking
changelog_url: https://github.com/fatedier/frp/releases
date_added: '2026-10-07'
description: frpc is the client of frp (Fast Reverse Proxy), a fast reverse proxy
  to help you expose a local service behind a NAT or firewall to the internet, or
  to access a service in another private network (stcp/sudp).
home: https://github.com/fatedier/frp
host_mounts: []
icon: https://media.sys.truenas.net/apps/frpc/icons/icon.png
keywords:
- network
- proxy
- tunnel
- nat
lib_version: 2.3.15
lib_version_hash: 418b1697e018a564438ced4d735f4ced3ea16cc9fa74971a6040e769c80a66e5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: frpc
run_as_context:
- description: Container [frpc] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/fatedier/frp
- https://hub.docker.com/r/fatedier/frpc
title: Frpc
train: community
version: 1.0.0
