resources:
  limits:
    cpus: 2
    memory: 4096

tmodloader:
  world_name: Docker
  world_size: 1
  world_difficulty: 0

  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8081
  server_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  data: /opt/tests/mnt/tmodloader/data
  backups: /opt/tests/mnt/tmodloader/backups

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  backups:
    type: ix_volume
    ix_volume_config:
      dataset_name: backups
      create_host_path: true
