resources:
  limits:
    cpus: 2
    memory: 4096
tmodloader:
  web_enabled: false
  config_source: env
  password: ''
  additional_envs:
  - name: TMOD_WORLDNAME
    value: TrueNASTest
  - name: TMOD_WORLDSIZE
    value: '1'
  - name: TMOD_AUTO_UPDATE
    value: '0'
  - name: TMOD_WORLDEVIL
    value: crimson
network:
  server_port:
    bind_mode: published
    port_number: 31077
  web_port:
    bind_mode: published
    port_number: 31080
storage:
  data:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/tmodloader-hostpath/data
      create_host_path: true
  backups:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/tmodloader-hostpath/backups
      create_host_path: true
