images:
  image:
    repository: ghcr.io/cinedock/cinedock
    tag: "4.9.8@sha256:b75155128d547138143e48c2920e46d1e87d9bdafe8076b242f0a23d1ff84be0"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  cinedock_container_name: cinedock
  perms_container_name: permissions
  config_path: /config
