images:
  image:
    repository: ghcr.io/ep1cman/unifi-protect-backup
    tag: "0.14.3@sha256:92a54a43f41ccbe7ee84b55fc3c73bd929f0c865113d7300c78702c218f08342"

consts:
  unifi_protect_backup_container_name: unifi-protect-backup
