#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "firefly_iii": {
            "additional_envs": config["fireflyConfig"].get("additionalEnvs", []),
            "db_password": get_value_from_secret(
                k8s_secrets, "postgres-creds", "POSTGRES_PASSWORD"
            ),
            "redis_password": get_value_from_secret(
                k8s_secrets, "redis-creds", "REDIS_PASSWORD"
            ),
            "app_key": get_value_from_secret(k8s_secrets, "firefly-config", "APP_KEY"),
            "app_url": config["fireflyConfig"]["appUrl"],
            "enable_importer": config["fireflyConfig"]["enableImporter"],
            "additional_importer_envs": config["fireflyConfig"]["additionalImporterEnvs"],
        },
        "network": {
            "web_port": config["fireflyNetwork"].get("webPort", 30044),
            "importer_port": config["fireflyNetwork"].get("importerPort", 30045),
        },
        "storage": {
            "uploads": migrate_storage_item(config["fireflyStorage"]["uploads"]),
            "postgres_data": migrate_storage_item(config["fireflyStorage"]["pgData"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["fireflyStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
