resources:
  limits:
    cpus: 4.0
    memory: 8192

puter:
  domain_name: "puter.localhost"
  db_password: "putertest"
  db_root_password: "putertestroot"
  enable_s3: false
  s3_access_key: "puter"
  s3_secret_key: "putersecret"
  s3_bucket: "puter-local"
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 4100

ix_volumes:
  config: /opt/tests/mnt/puter/config
  data: /opt/tests/mnt/puter/data
  valkey_data: /opt/tests/mnt/puter/valkey_data
  mariadb_data: /opt/tests/mnt/puter/mariadb_data
  dynamodb_data: /opt/tests/mnt/puter/dynamodb_data

storage:
  config:
    type: ix_volume
    ix_volume_config:
      dataset_name: config
      create_host_path: true
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  valkey_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: valkey_data
      create_host_path: true
  mariadb_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: mariadb_data
      create_host_path: true
  dynamodb_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: dynamodb_data
      create_host_path: true
  additional_storage: []