#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if values["storage"].get("uses_deprecated_media"):
        raise Exception(
            "Media storage was deprecated and now removed, "
            "please migrate your media storage and uncheck the "
            "'Use Deprecated Media Storage' option."
        )

    values["storage"].pop("uses_deprecated_media", None)
    values["storage"].pop("media", None)
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
