resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

swiparr:
  auth_secret: test-secret
  admin_username: test-admin
  provider: tmdb
  provider_lock: false
  allow_private_provider_urls: true
  tmdb_access_token: test-token
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  data: /opt/tests/mnt/swiparr/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
