images:
  image:
    repository: ghcr.io/shokoanime/server
    tag: "v5.3.3@sha256:b841f8249c9edfba102e4072e2b2a3eae4179e5dd553f29e11b9898a44f1e836"

consts:
  shoko_container_name: shoko-server
  internal_web_port: 8111
