#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["authentik"].pop("redis_password", None)
    
    new_labels = []
    for label in values["labels"]:
        filtered_containers = [
            container for container in label["containers"] 
            if container != "redis"
        ]
        if filtered_containers:
            new_labels.append({
                "key": label["key"],
                "value": label["value"],
                "containers": filtered_containers,
            })
    
    values["labels"] = new_labels
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
