images:
  image:
    repository: ghcr.io/d69wookie/actuallyfreecd-server
    tag: "1.0.2@sha256:9f0b8b6654de169cba04bdad8b4cf92b5f6b56abf1aa5fb16c18b69cd7b2d12f"

consts:
  actuallyfreecd_container_name: actuallyfreecd
  internal_web_port: 8080
