images:
  image:
    repository: ghcr.io/d69wookie/actuallyfreecd-server
    tag: "1.0.5@sha256:60d5a212f34faedc77b90556737da9e41be886101e69ff2e4a7d9556f5b7bb46"

consts:
  actuallyfreecd_container_name: actuallyfreecd
  internal_web_port: 8080
