#!/usr/bin/python3

import sys

if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    raise Exception(
        "Upgrading to version 2.0.0 from 1.x.x is not supported. "
        "Please perform a clean install of version 2.0.0 and migrate your data manually. "
        "See https://v2.dictionarry.dev/devlogs/profilarr-v2 for more details."
    )
