images:
  image:
    repository: tomsquest/docker-radicale
    tag: "3.8.3.0@sha256:a3b1b452f4bc3d1aee43015b85bc2d9ee5de0ff7e96d5d2b47f1d889aa682409"

consts:
  radicale_container_name: radicale
  ssl_key_path: /certs/key.pem
  ssl_cert_path: /certs/cert.pem
