resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

remux:
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 30009

labels: []

ix_volumes:
  data: /opt/tests/mnt/remux-data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage:
    - type: anonymous
      mount_path: /scratchpad
      volume_config:
        nocopy: true
