images:
  image:
    repository: ghcr.io/linuxserver/lazylibrarian
    tag: "978c264e-ls362@sha256:c8aead83b413cbda45828bc30668a748fa8f3e970203021a157d70623be3dcfc"

consts:
  lazylibrarian_container_name: lazylibrarian
  internal_web_port: 5299
