images:
  image:
    repository: ghcr.io/crocodilestick/calibre-web-automated
    tag: v4.0.6

consts:
  app_container_name: calibre-web-automated
  notes_body: |
    Default credentials:
    - Username: `admin`
    - Password: `admin123`
