#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "qbittorrent": {
            "additional_envs": config["qbitConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["qbitRunAs"].get("user", 568),
            "group": config["qbitRunAs"].get("group", 568),
        },
        "network": {
            "host_network": config["qbitNetwork"].get("hostNetwork", False),
            "web_port": config["qbitNetwork"].get("webPort", 30024),
            "bt_port": config["qbitNetwork"].get("btPort", 50413),
            "use_https_probe": config["qbitNetwork"].get("useHttpsProbe", False),
        },
        "storage": {
            "config": migrate_storage_item(config["qbitStorage"]["config"]),
            "downloads": migrate_storage_item(config["qbitStorage"]["downloads"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["qbitStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
