images:
  image:
    repository: lexfi/umlautadaptarrex
    tag: "1.4.0@sha256:0d0b9c9c39cf65c912c30bc4a942d4a2b28355c517c49f3cfa6a106bd515f456"

consts:
  umlautadaptarrex_container_name: umlautadaptarrex
  data_path: /data
