app_version: v0.8.5
capabilities: []
categories:
- productivity
- utilities
changelog_url: https://github.com/i1k3r/HAMAL-TRUENAS/releases
date_added: '2026-08-25'
description: Fast, private, temporary point-to-point local file transfer with ephemeral rooms, QR codes, and zero cloud dependencies.
home: https://github.com/i1k3r/HAMAL-TRUENAS
host_mounts: []
icon: https://media.sys.truenas.net/apps/hamal/icons/icon.png
keywords:
- file-transfer
- privacy
- lan-drop
- temporary-rooms
- qr-code
lib_version: 2.3.11
lib_version_hash: 874636814efb275e5276ea9d709b7cd665fed42bb1d50328e853d9253a2e1229
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: hamal
run_as_context:
- description: Container [hamal] runs as non-root user and group (10001:10001).
  gid: 10001
  group_name: hamal
  uid: 10001
  user_name: hamal
screenshots:
- https://media.sys.truenas.net/apps/hamal/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/hamal/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/hamal/screenshots/screenshot3.png
sources:
- https://github.com/i1k3r/HAMAL-TRUENAS
title: HAMAL
train: community
version: 1.0.0