#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.dns_config import migrate_dns_config
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "syncthing": {
            "additional_envs": config["syncthingConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["syncthingID"].get("user", 568),
            "group": config["syncthingID"].get("group", 568),
        },
        "network": {
            "host_network": config["syncthingNetwork"].get("hostNetwork", False),
            "web_port": config["syncthingNetwork"].get("webPort", 20910),
            "tcp_port": config["syncthingNetwork"].get("tcpPort", 20978),
            "udp_port": config["syncthingNetwork"].get("udpPort", 20979),
            "dns_opts": migrate_dns_config(config["podOptions"].get("dnsConfig", {})),
        },
        "storage": {
            "config": migrate_storage_item(config["syncthingStorage"]["config"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["syncthingStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
