#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def map_image_selector(image):
    match image:
        case "node14Image":
            return "node_14_image"
        case "node14MinimalImage":
            return "node_14_minimal_image"
        case "node16Image":
            return "node_16_image"
        case "node16MinimalImage":
            return "node_16_minimal_image"
        case "node18Image":
            return "image"
        case "node18MinimalImage":
            return "node_18_minimal_image"


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "node_red": {
            "additional_envs": config["noderedConfig"].get("additionalEnvs", []),
            "image_selector": map_image_selector(
                config["noderedConfig"]["imageSelector"]
            ),
            "enable_safe_mode": config["noderedConfig"]["safeMode"],
            "enable_projects": config["noderedConfig"]["enableProjects"],
        },
        "network": {
            "web_port": config["noderedNetwork"]["webPort"],
            "host_network": config["noderedNetwork"]["hostNetwork"],
        },
        "storage": {
            "data": migrate_storage_item(config["noderedStorage"]["data"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["noderedStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
