app_version: v3.24.3
capabilities:
- description: Databasus is able to change file ownership arbitrarily
  name: CHOWN
- description: Databasus is able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Databasus is able to bypass permission checks for file operations
  name: FOWNER
- description: Databasus is able to change group ID of processes
  name: SETGID
- description: Databasus is able to change user ID of processes
  name: SETUID
categories:
- productivity
date_added: '2026-03-26'
description: Databasus is a free, open source and self-hosted tool to backup databases
  (with focus on PostgreSQL). Make backups with different storages (S3, Google Drive,
  FTP, etc.) and notifications about progress (Slack, Discord, Telegram, etc.)
home: https://databasus.com
host_mounts: []
icon: https://media.sys.truenas.net/apps/databasus/icons/icon.svg
keywords:
- database
- management
lib_version: 2.3.0
lib_version_hash: c2d38144740c7336b2026e80ab52aafcae5389ff5ac54b2bd0b259c82171bde5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: databasus
run_as_context:
- description: Container [databasus] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://databasus.com
- https://hub.docker.com/r/databasus/databasus
title: Databasus
train: community
version: 1.0.0
