images:
  image:
    repository: databasus/databasus
    tag: v3.24.3
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  databasus_container_name: databasus
  perms_container_name: permissions
  web_port: 4005
  data_path: /databasus-data
