resources:
  limits:
    cpus: 4.0
    memory: 8192

TZ: Etc/UTC

calagopus:
  encryption_key: test-encryption-key-1234567890abcd
  db_password: test
  redis_password: test
  app_primary: true
  app_debug: false
  enable_wings_proxy: true
  use_decryption_cache: true
  use_internal_cache: true
  server_name: ""
  trusted_proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 30419
  sftp_port:
    bind_mode: published
    port_number: 30420

ix_volumes:
  data: /opt/tests/mnt/data
  logs: /opt/tests/mnt/logs
  wings_data: /opt/tests/mnt/wings_data
  postgres_data: /opt/tests/mnt/postgres_data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  logs:
    type: ix_volume
    ix_volume_config:
      dataset_name: logs
      create_host_path: true
  wings_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: wings_data
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []
