#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "readarr": {
            "instance_name": config["readarrConfig"].get("instanceName", "Readarr"),
            "additional_envs": config["readarrConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["readarrRunAs"].get("user", 568),
            "group": config["readarrRunAs"].get("group", 568),
        },
        "network": {
            "host_network": config["readarrNetwork"].get("hostNetwork", False),
            "web_port": config["readarrNetwork"].get("webPort", 20910),
        },
        "storage": {
            "config": migrate_storage_item(config["readarrStorage"]["config"]),
            "additional_storage": [
                migrate_storage_item(item)
                for item in config["readarrStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
