images:
  image:
    repository: ghcr.io/linuxserver/diskover
    tag: "2.3.5@sha256:7cef36aff4aa3b664fc58c8a71021453a0b22bc156cb47b7fac3a601c78de880"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  elastic_search_image:
    repository: elasticsearch
    tag: "9.5.3@sha256:a4e2b3d21ad0f779f3044bb6828b5289d5f1c241b3ddd7efae7adaf81bcff412"

consts:
  init_container_name: init
  diskover_data_container_name: diskoverdata
  elastic_search_container_name: elastic-search
  perms_container_name: permissions
  cron_file_path: /tmp/ix-crontab
  elastic_basic_auth_user: elastic
  elastic_run_as_user: 1000
  elastic_run_as_group: 1000
  elastic_port: 9200
  internal_web_port: 80
  notes_body: |
    Default credentials are:
    - Username: `diskover`
    - Password: `darkdata`

    Diskover Data will display an error page until the first indexing is complete.
    The indexing will run based on the cron schedule you set.

    You can also manually trigger an indexing by running the following command
    **in the Diskover Data container**:

    ```bash
    python3 /app/diskover/diskover.py <path_to_your_data>
    ```
