#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "twofactor_auth": {
            "additional_envs": config["twofauthConfig"].get("additionalEnvs", []),
            "app_key": get_value_from_secret(k8s_secrets, "twofauth-creds", "APP_KEY"),
            "app_name": config["twofauthConfig"]["appName"],
            "app_url": config["twofauthConfig"]["appUrl"],
            "site_owner_email": config["twofauthConfig"]["siteOwnerEmail"],
            "authentication_guard": config["twofauthConfig"]["authenticationGuard"],
            "authProxyHeaderUser": config["twofauthConfig"].get(
                "authProxyHeaderUser", ""
            ),
            "authProxyHeaderEmail": config["twofauthConfig"].get(
                "authProxyHeaderEmail", ""
            ),
            "webauthn_user_verification": config["twofauthConfig"][
                "webauthnUserVerification"
            ],
            "trusted_proxies": config["twofauthConfig"].get("trustedProxies", []),
        },
        "network": {
            "host_network": config["twofauthNetwork"].get("hostNetwork", False),
            "web_port": config["twofauthNetwork"].get("webPort", 30081),
        },
        "storage": {
            "config": migrate_storage_item(config["twofauthStorage"]["config"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["twofauthStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
