#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "jellyseerr": {
            "additional_envs": config["jellyseerrConfig"].get("additionalEnvs", []),
        },
        "network": {
            "web_port": config["jellyseerrNetwork"]["webPort"],
            "host_network": config["jellyseerrNetwork"]["hostNetwork"],
        },
        "run_as": {
            "user": config["jellyseerrRunAs"].get("user", 568),
            "group": config["jellyseerrRunAs"].get("group", 568),
        },
        "storage": {
            "config": migrate_storage_item(config["jellyseerrStorage"]["config"]),
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
