images:
  image:
    repository: koenkk/zigbee2mqtt
    tag: "2.14.2@sha256:addbfb08fcef2e4477de1535636118241e10d13e898fbe4d9faba8a4d7396311"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  yq_image:
    repository: mikefarah/yq
    tag: "4.54.1@sha256:4b3d9475d65571d28cbb19544d3820ec2945e4c8b2f18279394282b8dc3a592e"

consts:
  zigbee_container_name: zigbee2mqtt
  perms_container_name: permissions
  config_container_name: config
  data_path: /app/data
  notes_body: |
    For additional configuration, you can either edit the
    configuration file, use the web interface or add additional
    environment variables.</br>
    https://www.zigbee2mqtt.io/guide/configuration/#environment-variables
