images:
  image:
    repository: ghcr.io/derkezorm/nexdeck
    tag: 0.15.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  nexdeck_container_name: nexdeck
  perms_container_name: permissions
