resources:
  limits:
    cpus: 2.0
    memory: 4096

homedex:
  admin_password: a-test-admin-password-for-ci
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  web_port:
    bind_mode: published
    port_number: 8080
  networks: []

ix_volumes:
  data: /opt/tests/mnt/homedex/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
