annotations:
  min_scale_version: 24.10.2.2
app_version: v1.0.3
capabilities: []
categories:
- productivity
changelog_url: https://github.com/Kazwahs/arrvantage/releases
date_added: '2026-08-25'
description: A unified web dashboard for your media automation stack - arr apps, indexers, media servers, downloaders, and transcoders, all in one place.
home: https://github.com/Kazwahs/arrvantage
host_mounts: []
icon: https://raw.githubusercontent.com/Kazwahs/arrvantage/main/static/icons/logo.svg
keywords:
- dashboard
- media
- arr
- radarr
- sonarr
lib_version: 2.3.4
lib_version_hash: 2e3a8847308fb2eb0da046018f287c73822c094b5950a10377c3235794ff1242
maintainers:
- email: kazwahs42@gmail.com
  name: Kazwahs
  url: https://github.com/Kazwahs
name: arrvantage
run_as_context:
- description: Container [arrvantage] can run as any non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
screenshots: []
sources:
- https://github.com/Kazwahs/arrvantage
- https://github.com/Kazwahs/arrvantage/pkgs/container/arrvantage
title: arrVantage
train: community
version: 1.0.0