resources:
  limits:
    cpus: 2.0
    memory: 4096

run_as:
  user: 568
  group: 568

teslamate:
  postgres_image_selector: postgres_18_image
  db_password: test-teslamate-db-password
  encryption_key: test-encryption-key-for-teslamate
  enable_api: false
  api_token: ""
  disable_mqtt: true
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080
  api_port:
    bind_mode: published
    port_number: 8081

ix_volumes:
  import_data: /opt/tests/mnt/teslamate/import_data
  postgres_data: /opt/tests/mnt/teslamate/postgres_data

storage:
  import_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: import_data
      create_host_path: true
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []
