app_version: 0.2.4.8
capabilities:
- description: Bambuddy is able to bind to privileged ports (< 1024)
  name: NET_BIND_SERVICE
categories:
- productivity
changelog_url: https://github.com/maziggy/bambuddy/releases
date_added: '2026-07-03'
description: Your Bambu Lab. No Cloud. Your Rules. Self-hosted command center for
  Bambu Lab - from one A1 to a 40-printer farm.
home: https://bambuddy.cool/
host_mounts: []
icon: https://media.sys.truenas.net/apps/bambuddy/icons/icon.png
keywords:
- printer
- 3d
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bambuddy
run_as_context:
- description: Container [bambuddy] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/bambuddy_community/
- https://github.com/maziggy/bambuddy
title: Bambuddy
train: community
version: 1.0.1
