images:
  image:
    repository: ghcr.io/journeydocker/plex-auto-languages
    tag: "1.6.0@sha256:9b00a7877f9f85e0228a5d9aa3df5e6671f1116f1e9a8654e9d3f8ed40f2d694"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  plex_auto_languages_container_name: plex-auto-languages
  perms_container_name: permissions
  internal_port: 9880
