images:
  image:
    repository: ghcr.io/fliks-app/fliks
    tag: 4.0.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_image:
    repository: postgres
    tag: 18.6-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.16

consts:
  fliks_container_name: fliks
  perms_container_name: permissions
  postgres_container_name: postgres
  db_user: fliks
  db_name: fliks

  internal_web_port: 4848
