images:
  image:
    repository: ghcr.io/linuxserver/lazylibrarian
    tag: "9af8fbd8-ls360@sha256:451e73343d76ae09614b737dfaf90cdcd66d2168c599bb842aab3cd565a9a1d0"

consts:
  lazylibrarian_container_name: lazylibrarian
  internal_web_port: 5299
