images:
  image:
    repository: ghcr.io/grimmory-tools/grimmory
    tag: v3.0.3
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  mariadb_image:
    repository: mariadb
    tag: "12.2.2"

consts:
  grimmory_container_name: grimmory
  perms_container_name: permissions
  mariadb_container_name: mariadb
  db_user: grimmory
  db_name: grimmory
