images:
  image:
    repository: ghcr.io/derkezorm/nexbeat
    tag: "1.2.0@sha256:1e8debad4bfc06250fcdc5a7cb9f8308ad469dc2cfa31e3e0daf6b1b4d6f5a0a"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  nexbeat_container_name: nexbeat
  perms_container_name: permissions
