#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "netbootxyz": {
            "additional_envs": config["netbootxyzConfig"].get("additionalEnvs", []),
            "tftpd_opts": [],
        },
        "network": {
            "web_http_port": config["netbootxyzNetwork"]["webHttpPort"],
            "web_assets_port": config["netbootxyzNetwork"]["webAssetsPort"],
            "tftp_port": config["netbootxyzNetwork"]["tftpPort"],
            "host_network": config["netbootxyzNetwork"]["hostNetwork"],
        },
        "storage": {
            "data": migrate_storage_item(config["netbootxyzStorage"]["data"]),
            "assets": migrate_storage_item(config["netbootxyzStorage"]["assets"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["netbootxyzStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
