images:
  image:
    repository: jgraph/drawio
    tag: "32.2.0@sha256:eeb90e46cab38daf2b9f7887c9418d9fad219532cb03ad50826ef5a1f68d8a8e"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  drawio_container_name: drawio
  perms_container_name: permissions
  user_id: 1000
  group_id: 999
  internal_http_port: 8080
  internal_https_port: 8443
