#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.dns_config import migrate_dns_config
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    envs = []
    allowed_networks = []

    for env in config["plexConfig"].get("additionalEnvs", []):
        if env["name"] == "ALLOWED_NETWORKS":
            allowed_networks = env["value"].split(",")
        elif env["name"] != "NVIDIA_VISIBLE_DEVICES":
            envs.append(env)

    new_values = {
        "plex": {
            "additional_envs": envs,
            "claim_token": config["plexConfig"].get("claimToken", ""),
            "allowed_networks": allowed_networks,
            "image_selector": (
                "image"
                if config["plexConfig"]["imageSelector"] == "image"
                else "plex_pass_image"
            ),
        },
        "run_as": {
            "user": config["plexID"].get("user", 568),
            "group": config["plexID"].get("group", 568),
        },
        "network": {
            "host_network": config["plexNetwork"].get("hostNetwork", False),
            "web_port": config["plexNetwork"].get("webPort", 32400),
            "dns_opts": migrate_dns_config(config["podOptions"].get("dnsConfig", {})),
        },
        "storage": {
            "config": migrate_storage_item(config["plexStorage"]["config"]),
            "data": migrate_storage_item(config["plexStorage"]["data"]),
            "logs": migrate_storage_item(config["plexStorage"]["logs"]),
            "transcode": migrate_storage_item(config["plexStorage"]["transcode"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["plexStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(
            config["resources"], config["plexGPU"], values.get("gpu_choices", {})
        ),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
