images:
  image:
    repository: willtda/dropgate-server
    tag: 3.0.11
  container_utils_image:
    repository: ghcr.io/truenas/container_utils
    tag: latest

consts:
  dropgate_container_name: dropgate-server
  perms_container_name: permissions
  internal_web_port: 52443