images:
  image:
    repository: josh5/steam-headless
    tag: "debian@sha256:edb10f64058556ea80a651780c6bcc2f2791f7cebd2ee1b2d0049c728c0d2098"

consts:
  steam_headless_container_name: steam-headless
