images:
  image:
    repository: ghcr.io/dockroute/dockroute
    tag: 0.3.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  dockroute_container_name: dockroute
  perms_container_name: permissions
