#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if "run_as" not in values:
        # The user that used to run as before
        values["run_as"] = {"user": 0, "group": 0}
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
