images:
  image:
    repository: ghcr.io/elias02345/cloudgate
    tag: "v0.6.1@sha256:e6a1ad446f666089a94c3b920488a6c5747cb86ef37fe2c6edc0e3dd341d12f5"

consts:
  cloudgate_container_name: cloudgate
  run_as_user: 0
  run_as_group: 0
  data_path: /data
  web_port: 8080
