TZ: Etc/UTC
resources:
  limits:
    cpus: 2
    memory: 4096
litellm:
  db_password: testpassword
  master_key: sk-test-master-key-at-least-32-characters
  salt_key: sk-test-salt-key-at-least-32-characters
  additional_envs: []
network:
  networks: []
  web_port:
    bind_mode: published
    port_number: 8080
    host_ips: []
ix_volumes:
  postgres_data: /opt/tests/mnt/litellm/postgres-data
storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  additional_storage: []

labels: []
