images:
  image:
    repository: ghcr.io/pryaxis/tshock
    tag: "6.2.1@sha256:70e59a8e6b4c79b5fad469d320962c1fc98625ed3a955510a2f2641dbff2f7e7"

consts:
  terraria_container_name: terraria-tshock
  reserved_args:
    - -worldselectpath
    - -configpath
    - -additionalplugins
    - -config
    - -port
    - -world
    - -worldname
    - -rest-enabled
    - -rest-port
    - -autocreate
    - -worldevil
    - -maxplayers
    - -players
    - -difficulty
    - -seed
    - -password
    - -pass
    - -secure
