resources:
  limits:
    cpus: 2
    memory: 4096

TZ: UTC

overleaf:
  app_name: Overleaf Community Edition
  site_url: http://localhost:30461
  admin_email: admin@example.com
  invite_token_secret: test-invite-token-secret-32chars!!
  redis_password: testredispassword
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 30461
    container_port: 80

ix_volumes:
  overleaf-data: /opt/tests/mnt/overleaf/data
  mongo-data: /opt/tests/mnt/overleaf/mongo-data

storage:
  overleaf_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: overleaf-data
      create_host_path: true
  mongo_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: mongo-data
      create_host_path: true
  additional_storage: []
