#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if values["network"].get("host_network", False):
        raise Exception(
            "Host network is not a valid configuration in OpenWebUI. Please remove it and retry the upgrade."
        )

    values["network"].pop("host_network", None)
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
