images:
  image:
    repository: ghcr.io/grimmory-tools/grimmory
    tag: "v3.5.0@sha256:bf6fe21c6e247597f7869664a440b5a34242e2d2940575cae39c17bfaa66dc0b"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  mariadb_image:
    repository: mariadb
    tag: "13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"

consts:
  grimmory_container_name: grimmory
  perms_container_name: permissions
  mariadb_container_name: mariadb
  db_user: grimmory
  db_name: grimmory
