images:
  image:
    repository: gaseousgames/gaseousserver
    tag: "v1.7.14@sha256:5e506593ff09533f23e742470da2ef37ffe4051f3559dad3b038e81444df75a6"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  mariadb_image:
    repository: mariadb
    tag: "13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"

consts:
  gaseous_container_name: gaseous-server
  perms_container_name: permissions
  mariadb_container_name: mariadb
  db_user: gaseous
  db_name: gaseous
  internal_web_port: 80
  notes_body: |
    For information on how to use Gaseous, as well as adding roms,
    please visit the [official documentation](https://github.com/gaseous-project/gaseous-server/wiki).
