#!/usr/bin/python3

import os
import sys
import yaml
import secrets


def migrate(values):
    if "app_secret" not in values["zerobyte"]:
        values["zerobyte"]["app_secret"] = secrets.token_hex(32)[:64]

    if "base_url" not in values["zerobyte"]:
        values["zerobyte"]["base_url"] = "http://truenas.local:30314"

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
