#!/usr/bin/python3

import os
import sys
import yaml

def migrate(values):
    values["hermes-agent"].pop("enable_insecure_dashboard_access", None)

    if values["hermes-agent"].get("additional_envs", {}).get("HERMES_DASHBOARD_BASIC_AUTH_USERNAME") and values["hermes-agent"].get("additional_envs", {}).get("HERMES_DASHBOARD_BASIC_AUTH_PASSWORD"):
        values["hermes-agent"]["basic_auth_enabled"] = True
        values["hermes-agent"]["basic_auth_username"] = values["hermes-agent"]["additional_envs"].pop("HERMES_DASHBOARD_BASIC_AUTH_USERNAME")
        values["hermes-agent"]["basic_auth_password"] = values["hermes-agent"]["additional_envs"].pop("HERMES_DASHBOARD_BASIC_AUTH_PASSWORD")
    else:
        values["hermes-agent"]["basic_auth_enabled"] = False
        values["hermes-agent"].pop("basic_auth_username", None)
        values["hermes-agent"].pop("basic_auth_password", None)

    return values

if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
