#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["hermes_agent"].pop("enable_insecure_dashboard_access", None)

    username = password = key = ""
    new_env = []
    for env in values.get("additional_envs", []):
        if env["name"] == "HERMES_DASHBOARD_BASIC_AUTH_USERNAME":
            username = env["value"]
        elif env["name"] == "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD":
            password = env["value"]
        elif env["name"] == "HERMES_DASHBOARD_BASIC_AUTH_SECRET":
            key = env["value"]
        else:
            new_env.append(env)

    values["hermes_agent"]["enable_basic_auth"] = bool(username and password)
    values["hermes_agent"]["basic_auth_username"] = username
    values["hermes_agent"]["basic_auth_password"] = password
    values["hermes_agent"]["hmac_key"] = key
    values["additional_envs"] = new_env

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
