#!/usr/bin/python3

import os
import sys
import yaml

def migrate(values):
    values["hermes-agent"].pop("enable_insecure_dashboard_access", None)
    
    basic_auth = False
    username = ""
    password = ""
    new_env = []
    for env in values.get("additional_envs", []):
        if env["name"] == "HERMES_DASHBOARD_BASIC_AUTH_USERNAME":
            username = env["value"]
        elif env["name"] == "HERMES_DASHBOARD_BASIC_AUTH_PASSWORD":
            password = env["value"]
        else:
            new_env.append(env)

    if username and password:
        basic_auth = True

    values["hermes-agent"]["basic_auth_enabled"] = basic_auth
    values["hermes-agent"]["basic_auth_username"] = username
    values["hermes-agent"]["basic_auth_password"] = password
    values["additional_envs"] = new_env
    
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
