resources:
  limits:
    cpus: 2.0
    memory: 4096

logforge:
  central_fqdn: localhost
  admin_username: admin
  admin_password: TrueNASCatalog2026!
  admin_recovery_override: false
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 30488
  agent_port:
    bind_mode: published
    port_number: 30489

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
