images:
  image:
    repository: openuem/openuem-console
    tag: 0.12.0
  cert_manager_image:
    repository: openuem/openuem-cert-manager
    tag: 0.12.0
  ocsp_responder_image:
    repository: openuem/openuem-ocsp-responder
    tag: 0.12.0
  worker_image:
    repository: openuem/openuem-worker
    tag: 0.12.0
  nats_server_image:
    repository: nats
    tag: 2.12.6
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.2

consts:
  console_container_name: console
  cert_manager_container_name: cert-manager
  ocsp_responder_container_name: ocsp-responder
  notification_worker_container_name: notification-worker
  cert_manager_worker_container_name: cert-manager-worker
  agents_worker_container_name: agents-worker
  nats_server_container_name: nats-server
  perms_container_name: permissions
  postgres_container_name: postgres
  db_user: openuem
  db_name: openuem

  run_as_user: 0
  run_as_group: 0

  notes_body: |
    Default credentials:
    - Username: `openuem`
    - Password: _printed in the logs of the `console` container on first boot_
