images:
  image:
    repository: jxxghp/moviepilot-v2
    tag: latest
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_image:
    repository: postgres
    tag: 18.4-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.11
  redis_image:
    repository: redis
    tag: 7.4.1

consts:
  app_container_name: moviepilot-v2
  perms_container_name: permissions
  postgres_container_name: postgres
  redis_container_name: redis
  db_user: moviepilot
  db_name: moviepilot