resources:
  limits:
    cpus: 2.0
    memory: 4096

rust_desk:
  image_selector: "image"
  # mac_address: "02:42:ac:11:00:02"  # Optional MAC address for PRO edition
  allow_only_encrypted_connections: false
  additional_envs: []

network:
  relay_port:
    bind_mode: published
    port_number: 21117
  relay_web_clients_port:
    bind_mode: published
    port_number: 21119
  host_network: false

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
