app_version: 1.2.1
capabilities: []
categories:
- games
changelog_url: https://github.com/Daddelgreis74/switch-game-catalog/releases
date_added: '2026-08-26'
description: A lightweight, fast self-hosted NSW game library manager and catalog with automatic metadata parsing, multi-language support, and modern web dashboard.
home: https://github.com/Daddelgreis74/switch-game-catalog
host_mounts: []
icon: https://media.sys.truenas.net/apps/switch-game-catalog/icons/icon.svg
keywords:
- switch
- nsw
- game-catalog
- rom-manager
lib_version: 2.3.6
lib_version_hash: 5067fd69a830797f96075fe2fe08aa41e2ec08d7c94cf5c6d6256690be7e06ae
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: switch-game-catalog
run_as_context:
- description: Container [switch-game-catalog] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/Daddelgreis74/switch-game-catalog
- https://ghcr.io/daddelgreis74/switch-game-catalog
title: NSW Game Catalog
train: community
version: 1.0.0
