images:
  image:
    repository: ghcr.io/viren070/aiostreams
    tag: "v2.35.3@sha256:9ed6e7a6210d4f4937ed826a0d21bb36efcace6148eda98a29aeb2fb8346c635"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  aiostreams_container_name: aiostreams
  perms_container_name: permissions
