resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Etc/UTC

plmail:
  additional_envs:
    - name: APP_PUBLIC_URL
      value: http://localhost:8081
    - name: VAPID_SUBJECT
      value: mailto:admin@example.com

network:
  web_port:
    bind_mode: published
    port_number: 8081
  networks: []

storage:
  data:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/plmail/hostpath
      create_host_path: true
