resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: Europe/Berlin

borgui:
  initial_admin_password: "test-admin-password"
  base_path: ""
  public_base_url: ""
  enable_redis: true
  redis_password: "redis-test-password"
  enable_fuse: true
  mount_docker_socket: false
  additional_envs:
    - name: LOG_LEVEL
      value: DEBUG

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30082

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/borg-ui/data
  cache: /opt/tests/mnt/borg-ui/cache
  sources: /opt/tests/mnt/borg-ui/sources

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  cache:
    type: ix_volume
    ix_volume_config:
      dataset_name: cache
      create_host_path: true
  additional_storage:
    - type: ix_volume
      mount_path: /local
      ix_volume_config:
        dataset_name: sources
        create_host_path: true
