resources:
  limits:
    cpus: 1.0
    memory: 1024

TZ: Etc/UTC

geopulse:
  db_password: secret
  public_base_url: http://localhost:30078
  auth_secure_cookies: false
  admin_email: ""
  default_distance_unit: KILOMETERS
  default_temperature_unit: CELSIUS
  additional_backend_envs: []
  additional_frontend_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 30078

ix_volumes:
  postgres_data: /opt/tests/mnt/geopulse/postgres_data
  key_material: /opt/tests/mnt/geopulse/key_material
  import_drop: /opt/tests/mnt/geopulse/import_drop

storage:
  postgres_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: postgres_data
      create_host_path: true
  key_material:
    type: ix_volume
    ix_volume_config:
      dataset_name: key_material
      create_host_path: true
  import_drop:
    type: ix_volume
    ix_volume_config:
      dataset_name: import_drop
      create_host_path: true
  additional_storage: []
