app_version: 1.17.1
capabilities: []
categories:
  - database
changelog_url: https://github.com/qdrant/qdrant/releases
date_added: "2026-04-14"
description: Qdrant is a vector similarity search engine and vector database. It
  provides a production-ready service with a convenient API to store, search,
  and manage vectors with additional payload.
home: https://qdrant.tech
host_mounts: []
icon: https://media.sys.truenas.net/apps/qdrant/icons/icon.svg
keywords:
  - vector
  - database
  - search
  - ai
  - embeddings
  - gpu
lib_version: 2.3.3
lib_version_hash: b6a043c5dc3d4ba71901b9833713b4352b031f3bf39a1b3908e2cf17f1129d8d
maintainers:
  - email: dev@truenas.com
    name: truenas
    url: https://www.truenas.com/
name: qdrant
run_as_context:
  - description: Container [qdrant] can run as any non-root user and group.
    gid: 568
    group_name: Host group is [apps]
    uid: 568
    user_name: Host user is [apps]
screenshots: []
sources:
  - https://hub.docker.com/r/qdrant/qdrant
  - https://github.com/qdrant/qdrant
title: Qdrant
train: community
version: 1.0.0
