images:
  image:
    repository: borgwarehouse/borgwarehouse
    tag: "v3.6.3@sha256:4d8237acf8df6ced885c22de914c3246c59ae7fe6221d5742c142853e2a8821d"
  cron_image:
    repository: ixsystems/cron
    tag: "1.0.11@sha256:ffb8ab5a597da19bebb62e4bb4826b3d3ed6ce5946c45d965287df100b3f1201"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  borgwarehouse_container_name: borgwarehouse
  borgwarehouse_cron_container_name: cron
  perms_container_name: permissions

  internal_ssh_port: 22
  internal_web_port: 3000

  notes_body: |
    Default credentials:
    - Username: `admin`
    - Password: `admin`
