comfyui:
  cli_args: "--disable-xformers"
  additional_envs: []

network:
  webui_port:
    bind_mode: published
    port_number: 30481
  host_network: false

ix_volumes:
  models: /opt/tests/mnt/models
  input: /opt/tests/mnt/input
  output: /opt/tests/mnt/output
  workflows: /opt/tests/mnt/workflows
  custom_nodes: /opt/tests/mnt/custom_nodes
  user: /opt/tests/mnt/user
  hf_cache: /opt/tests/mnt/hf_cache
  torch_cache: /opt/tests/mnt/torch_cache

storage:
  models:
    type: ix_volume
    ix_volume_config:
      dataset_name: models
      create_host_path: true
  input:
    type: ix_volume
    ix_volume_config:
      dataset_name: input
      create_host_path: true
  output:
    type: ix_volume
    ix_volume_config:
      dataset_name: output
      create_host_path: true
  workflows:
    type: ix_volume
    ix_volume_config:
      dataset_name: workflows
      create_host_path: true
  custom_nodes:
    type: ix_volume
    ix_volume_config:
      dataset_name: custom_nodes
      create_host_path: true
  user:
    type: ix_volume
    ix_volume_config:
      dataset_name: user
      create_host_path: true
  hf_cache:
    type: ix_volume
    ix_volume_config:
      dataset_name: hf_cache
      create_host_path: true
  torch_cache:
    type: ix_volume
    ix_volume_config:
      dataset_name: torch_cache
      create_host_path: true
  additional_storage: []
