resources:
  limits:
    cpus: 2
    memory: 2048

hamal:
  base_url: ""
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 7700

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
  additional_storage: []