resources:
  limits:
    cpus: "2.0"
    memory: 2048

TZ: Etc/UTC

hamal:
  base_url: ""
  default_ttl: "1h"
  max_ttl: "24h"
  max_file_size: "10GiB"
  max_room_size: "10GiB"
  max_total_storage: "100GiB"
  min_free_space: "5GiB"
  log_level: "info"
  log_format: "json"
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 7700

run_as:
  user: 10001
  group: 10001

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
