#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["network"]["nat_type_test_port"] = {
        "port_number": values["network"].get("nat_type_test_port", 21115),
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["id_reg_hole_punch_port"] = {
        "port_number": values["network"].get("id_reg_hole_punch_port", 21116),
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["relay_port"] = {
        "port_number": values["network"].get("relay_port", 21117),
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["server_web_clients_port"] = {
        "port_number": values["network"].get("server_web_clients_port", 21118),
        "bind_mode": "published" if values["network"].get("enable_web_clients", False) else "",
        "host_ips": [],
    }
    values["network"]["relay_web_clients_port"] = {
        "port_number": values["network"].get("relay_web_clients_port", 21119),
        "bind_mode": "published" if values["network"].get("enable_web_clients", False) else "",
        "host_ips": [],
    }
    values["network"].pop("enable_web_clients", None)

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
