#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "vikunja": {
            "additional_envs": config["vikunjaConfig"].get("additionalEnvs", []),
            "jwt_secret": get_value_from_secret(
                k8s_secrets, "vikunja-creds", "VIKUNJA_SERVICE_JWTSECRET"
            ),
            "db_password": get_value_from_secret(
                k8s_secrets, "postgres-creds", "POSTGRES_PASSWORD"
            ),
            "redis_password": get_value_from_secret(
                k8s_secrets, "redis-creds", "REDIS_PASSWORD"
            ),
            "max_file_size": config["vikunjaConfig"]["maxFileSize"],
            "url": config["vikunjaConfig"]["url"],
        },
        "run_as": {
            "user": config["vikunjaRunAs"]["user"],
            "group": config["vikunjaRunAs"]["group"],
        },
        "network": {
            "web_port": config["vikunjaNetwork"]["webPort"],
        },
        "storage": {
            "data": migrate_storage_item(config["vikunjaStorage"]["data"]),
            "postgres_data": migrate_storage_item(config["vikunjaStorage"]["pgData"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["vikunjaStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
