{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.cloudflare_mesh_container_name, "image") %}
{% do c1.add_caps(["NET_ADMIN", "NET_RAW", "SYS_MODULE", "CHOWN", "FOWNER", "DAC_OVERRIDE"]) %}
{% do c1.healthcheck.disable() %}

{% if not values.network.host_network %}
  {% do c1.sysctls.add("net.ipv4.ip_forward", 1) %}
  {% do c1.sysctls.add("net.ipv6.conf.all.forwarding", 1) %}
  {% do c1.sysctls.add("net.ipv6.conf.default.forwarding", 1) %}
{% endif %}

{% do c1.environment.add_env("SRCNAT_ENABLED", true) %}
{% do c1.environment.add_env("MESH_NODE_TOKEN", values.cloudflare_mesh.mesh_token) %}
{% do c1.environment.add_user_envs(values.cloudflare_mesh.additional_envs) %}

{% do c1.add_tun_device() %}
{% do c1.add_storage("/var/lib/cloudflare-warp", values.storage.config) %}
{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{{ tpl.render() | tojson }}
