images:
  image:
    repository: ghcr.io/dmunozv04/isponsorblocktv
    tag: v2.10.0

consts:
  app_container_name: isponsorblocktv
  init_container_name: isponsorblocktv-init
  config_path: /app/data
  config_file: /app/data/config.json
