#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "elastic": {
            "password": config["esConfig"]["password"],
            "heap_size": config["esConfig"]["heapSize"],
            "node_name": config["esConfig"]["nodeName"],
            "additional_envs": config["esConfig"].get("additionalEnvs", []),
        },
        "network": {
            "web_port": config["esNetwork"]["httpPort"],
            "host_network": config["esNetwork"]["hostNetwork"],
            "certificate_id": config["esNetwork"].get("certificateID"),
        },
        "storage": {
            "data": migrate_storage_item(config["esStorage"]["data"]),
            "additional_storage": [],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
