resources:
  limits:
    cpus: 2.0
    memory: 4096

vault:
  ui: true
  log_level: info
  api_addr: ""
  additional_envs: []
network:
  certificate_id: null
  web_port:
    bind_mode: published
    port_number: 8200

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
