images:
  image:
    repository: ghcr.io/immich-app/immich-server
    tag: "v3.3.0@sha256:be56bc12c17a84617a979ad1eab1d9105bbec1955ffa7da09b3f9cf79d3bd09d"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  ml_image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: "v3.3.0@sha256:aa88ec3aef3bdc97ab31eff66acecc98bb6ee14d47b6122c25e761ed9f31a7da"
  ml_cuda_image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: "v3.3.0-cuda@sha256:72c6276bd96505b8cf543bbb3dc58da9fd0654fe361ba4140dca8407e3a2be71"
  ml_rocm_image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: "v3.3.0-rocm@sha256:f0f594014b7210e716e314aa9711f60aca9ff4688b47b94902de2ec2ac083822"
  ml_openvino_image:
    repository: ghcr.io/immich-app/immich-machine-learning
    tag: "v3.3.0-openvino@sha256:a79670d05f8da90c86f8074afe1beaf51abee53c58692ad45cae2efd9afd4aca"
  vectorchord_18_image:
    repository: ghcr.io/immich-app/postgres
    tag: "18-vectorchord1.1.1@sha256:e53734de78ebf59a92261033c7dca61f789d925b79e7b68883f65b016cf27ed7"
  redis_image:
    repository: valkey/valkey
    tag: "9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd"
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: "1.2.21@sha256:81e6dc8396e7226f5528981881bf973f16ce33b5ed39b4380bbd0d62713a475f"

consts:
  server_container_name: server
  ml_container_name: machine-learning
  pgvecto_container_name: pgvecto
  redis_container_name: redis
  perms_container_name: permissions
  ml_port: 32002
  ml_cache_path: /mlcache
  db_user: immich
  db_name: immich
  base_path: /data
