images:
  image:
    repository: bbernhard/signal-cli-rest-api
    tag: "0.101"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  signal_cli_rest_api_container_name: signal-cli-rest-api
  perms_container_name: permissions
  config_path: /config
