images:
  image:
    repository: wordpress
    tag: "7.1.2@sha256:8ae73d594a154e30b112e8d085afbc0895acf7651d8f53ef63aefb42e30822d5"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  mariadb_image:
    repository: mariadb
    tag: "13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"

consts:
  wordpress_container_name: wordpress
  perms_container_name: permissions
  mariadb_container_name: mariadb
  db_user: wordpress
  db_name: wordpress
  wordpress_run_user: 33
  wordpress_run_group: 33
  internal_web_port: 80
