images:
  image:
    repository: databasus/databasus
    tag: "v3.60.0@sha256:2e9aec567de7ed3f0c8f360ea72abe6a8425704d9272232dae4325ad920b9204"

consts:
  databasus_container_name: databasus
  internal_web_port: 4005
