app_version: 1.7.7
capabilities: []
categories:
- productivity
changelog_url: https://github.com/bulwarkmail/webmail/releases
date_added: '2026-05-25'
description: Bulwark is a modern, self-hosted webmail suite built for Stalwart Mail
  Server and powered by the JMAP protocol. It provides webmail, calendar, contacts,
  and file access through a browser-based interface.
home: https://bulwarkmail.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/bulwark-webmail/icons/icon.svg
keywords:
- webmail
- email
- jmap
- calendar
- contacts
lib_version: 2.3.5
lib_version_hash: c0d042e3de6350fae9aee546d3c79bc0accf1f2011da89cc1ebff29421aa7fc9
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: bulwark-webmail
run_as_context:
- description: Container [bulwark-webmail] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/bulwark-webmail_community/
- https://github.com/bulwarkmail/webmail
title: Bulwark Webmail
train: community
version: 1.0.8
