images:
  image:
    repository: wabayang/jelu
    tag: "0.88.1@sha256:ee436dc90ad0bc9ea84d6049b8d3d18a79478ce2ef0f27a974da93a72fb17c0d"

consts:
  jelu_container_name: jelu
  internal_web_port: 11111
  database_path: /database
  files_images_path: /files/images
  files_imports_path: /files/imports
