resources:
  limits:
    cpus: 2.0
    memory: 4096

qdrant:
  image_selector: "image"
  api_key: "test_api_key_1234567890"
  read_only_api_key: ""
  enable_cors: true
  gpu_indexing: false
  gpu_force_half_precision: false
  gpu_groups_count: 512
  gpu_device_filter: ""
  gpu_parallel_indexes: 1
  gpu_allow_integrated: false
  additional_envs: []

run_as:
  user: 568
  group: 568

network:
  host_network: false
  http_port:
    bind_mode: published
    port_number: 8080
  grpc_port:
    bind_mode: published
    port_number: 8081

ix_volumes:
  data: /opt/tests/mnt/qdrant/data
  snapshots: /opt/tests/mnt/qdrant/snapshots

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  snapshots:
    type: ix_volume
    ix_volume_config:
      dataset_name: snapshots
      create_host_path: true
  additional_storage: []
