images:
  image:
    repository: ghcr.io/jsdelivr/globalping-probe
    tag: "0.53.0@sha256:a2455e2863bacd656b604c1e837acadaff094e1c46471fc13896ec2884dfd721"

consts:
  probe_container_name: globalping-probe
  notes_body: |
    ## Important Information

    - If you provided an adoption token, your probe will be automatically adopted to your account
    - Check your probe status and logs at: https://dash.globalping.io
    - A new probe UUID is generated on each restart (no persistent storage).
    - As long as your public IP does not change when the probe is not running, the API will still correctly identify it as the same probe

    ## Limitations (from Globalping)

    - Only one probe can run per IP address
    - Probes connecting through anonymous proxies, Tor, or VPN services will be blocked
    - If a probe's location is not accurate you can change it in our dashboard
