#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["network"]["web_port"] = {
        "port_number": values["network"]["web_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["agent_port"] = {
        "port_number": values["network"].get("agent_port", 50000),
        "bind_mode": "published" if values["network"]["enable_agent"] else "",
        "host_ips": [],
    }
    values["network"].pop("enable_agent", None)

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
