#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "zerotier": {
            "auth_token": config["zerotierConfig"]["authToken"],
            "identity_public": config["zerotierConfig"]["identityPublic"],
            "identity_secret": config["zerotierConfig"]["identitySecret"],
            "networks": config["zerotierConfig"]["networks"],
            "additional_envs": config["zerotierConfig"].get("additionalEnvs", []),
        },
        "network": {
            "host_network": config["zerotierNetwork"].get("hostNetwork", False),
        },
        "storage": {
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config.get("zerotierStorage", {}).get(
                    "additionalStorages", []
                )
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
