images:
  image:
    repository: tomsquest/docker-radicale
    tag: "3.8.1.1@sha256:e6d8c17bc4d75f3fd40e52b20421ba244c17ca08fb01cd7dc90d5d78ba51b58d"

consts:
  radicale_container_name: radicale
  ssl_key_path: /certs/key.pem
  ssl_cert_path: /certs/cert.pem
