#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["opencloud"]["additional_csp"] = [
        {
            "directive": x["directive"],
            "items": (
                [{"value": i, "placeholder": ""} for i in x["items"]] if isinstance(x["items"], list) else x["items"]
            ),
        }
        for x in values["opencloud"]["additional_csp"]
    ]
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
