images:
  image:
    repository: ghcr.io/linuxserver/piwigo
    tag: "16.4.0@sha256:6cc93ec5af88d1cbd24670a51e2bebf8ea5fe7b16a6a45545684fc26cb50ec7c"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  mariadb_image:
    repository: mariadb
    tag: "13.0.2@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d"

consts:
  piwigo_container_name: piwigo
  init_container_name: init
  perms_container_name: permissions
  mariadb_container_name: mariadb
  db_user: piwigo
  db_name: piwigo
  internal_web_port: 80
