images:
  image:
    repository: ghcr.io/sasray/cinefind-bridge
    tag: v2.0.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
consts:
  bridge_container_name: cinefind-bridge
  perms_container_name: permissions
  data_path: /data
bridge:
  pairing_code: ''
  seerr_url: ''
  seerr_api_key: ''
  radarr_url: ''
  radarr_api_key: ''
  sonarr_url: ''
  sonarr_api_key: ''
  display_name: TrueNAS
run_as:
  user: 568
  group: 568
storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      acl_enable: false
    host_path_config:
      path: ''
      acl_enable: false
