images:
  image:
    repository: ghcr.io/logseq/logseq-webapp
    tag: "latest@sha256:de87c4a26986278b52f778d4d28c03e32d68a7c7f42bae128614bcaa3f26c231"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  perms_container_name: permissions
  logseq_container_name: logseq
  ssl_key_path: /etc/nginx/certs/tls.key
  ssl_cert_path: /etc/nginx/certs/tls.crt
