resources:
  limits:
    cpus: 2.0
    memory: 4096

yunkan:
  image_selector: image
  db_password: test
  webrtc_extern_ips: ""
  mount_product_uuid: true
  devices: []
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 31406
  webrtc_port:
    bind_mode: published
    port_number: 33515

ix_volumes:
  yunkan-data: /opt/tests/mnt/yunkan/data
  yunkan-recordings: /opt/tests/mnt/yunkan/recordings
  mariadb_data: /opt/tests/mnt/yunkan/mariadb_data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: yunkan-data
      create_host_path: true
  recordings:
    type: ix_volume
    ix_volume_config:
      dataset_name: yunkan-recordings
      create_host_path: true
  mariadb_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: mariadb_data
      create_host_path: true
  additional_storage: []
