resources:
  limits:
    cpus: 2.0
    memory: 4096

yunkan:
  image_selector: image
  webrtc_extern_ips:
    - "192.0.2.10"
    - "public.example.com"
  mount_product_uuid: false
  devices: []
  additional_envs: []

network:
  host_network: true

ix_volumes:
  data: /opt/tests/mnt/yunkan/data
  recordings: /opt/tests/mnt/yunkan/recordings

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  recordings:
    type: ix_volume
    ix_volume_config:
      dataset_name: recordings
      create_host_path: true
  additional_storage: []
