annotations:
  min_scale_version: 24.10.2.2
app_version: 4.0.1019.1099
capabilities: []
categories:
- media
changelog_url: https://github.com/Sportarr/Sportarr/releases
date_added: '2026-07-10'
description: Sportarr is a sports PVR for Usenet and BitTorrent users. It monitors
  sports leagues, searches indexers for event releases, sends them to a download
  client, and renames and organizes recordings into a sports media library.
home: https://github.com/Sportarr/Sportarr
host_mounts: []
icon: https://media.sys.truenas.net/apps/sportarr/icons/icon.png
keywords:
- media
- sports
- pvr
- dvr
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: sportarr
run_as_context:
- description: Container [sportarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/sportarr_community/
- https://github.com/Sportarr/Sportarr
- https://hub.docker.com/r/sportarr/sportarr
title: Sportarr
train: community
version: 1.0.0
