#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "homarr": {
            "additional_envs": config["homarrConfig"].get("additionalEnvs", []),
            "nextauth_secret": get_value_from_secret(
                k8s_secrets, "homarr-creds", "NEXTAUTH_SECRET"
            ),
        },
        "run_as": {
            "user": config["homarrRunAs"].get("user", 568),
            "group": config["homarrRunAs"].get("group", 568),
        },
        "network": {
            "web_port": config["homarrNetwork"]["webPort"],
            "host_network": config["homarrNetwork"].get("hostNetwork", False),
        },
        "storage": {
            "configs": migrate_storage_item(config["homarrStorage"]["configs"]),
            "data": migrate_storage_item(config["homarrStorage"]["data"]),
            "icons": migrate_storage_item(config["homarrStorage"]["icons"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["homarrStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
