annotations:
  min_scale_version: 24.10.2.2
app_version: 4.0.6
capabilities: []
categories:
- productivity
changelog_url: https://github.com/Lissy93/dashy/releases
date_added: '2024-08-01'
description: Dashy is a self-hostable personal dashboard built for you.
home: https://dashy.to/
host_mounts: []
icon: https://media.sys.truenas.net/apps/dashy/icons/icon.png
keywords:
- dashboard
lib_version: 2.3.4
lib_version_hash: 2e3a8847308fb2eb0da046018f287c73822c094b5950a10377c3235794ff1242
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: dashy
run_as_context:
- description: Container [dashy] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots:
- https://media.sys.truenas.net/apps/dashy/screenshots/screenshot1.gif
- https://media.sys.truenas.net/apps/dashy/screenshots/screenshot2.gif
sources:
- https://dashy.to/
- https://github.com/lissy93/dashy
title: Dashy
train: community
version: 2.0.3
