app_version: 1.8.7
capabilities: []
categories:
- productivity
changelog_url: https://github.com/blinkospace/blinko/releases
date_added: '2026-04-09'
description: Blinko is the next generation of open-source AI-powered card notes designed
  to help you quickly capture and organize inspiration so that ideas never run out.
home: https://blinko.space
host_mounts: []
icon: https://media.sys.truenas.net/apps/blinko/icons/icon.png
keywords:
- notes
- cards
lib_version: 2.3.3
lib_version_hash: afa5d7d30a811afe017626efff68d8c2937ac050d53a6857076dcb52098f313e
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: blinko
run_as_context:
- description: Container [blinko] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://github.com/blinkospace/blinko
- https://hub.docker.com/r/blinkospace/blinko
title: Blinko
train: community
version: 1.0.4
