images:
  image:
    repository: subsimail/subsimail
    tag: "8.0.2@sha256:1c0680c4f6f7e4197442be241c4ade2f8efb3c63803f377d43f2147ff2a9a9ef"

consts:
  subsimail_container_name: subsimail
  data_dir: /app/data
