images:
  image:
    repository: ghcr.io/linuxserver/lazylibrarian
    tag: "8006a0fc-ls367@sha256:2ad8abf05b0fc3ae0e9bebfd50dc0d530c4d672bc341e87d990978f62761c7fe"

consts:
  lazylibrarian_container_name: lazylibrarian
  internal_web_port: 5299
