app_version: 13.0.24
capabilities:
- description: Seadoc, Seafile are able to change file ownership arbitrarily
  name: CHOWN
- description: Seadoc, Seafile are able to bypass file permission checks
  name: DAC_OVERRIDE
- description: Seadoc, Seafile are able to bypass permission checks for file operations
  name: FOWNER
- description: Seadoc, Seafile are able to change group ID of processes
  name: SETGID
- description: Seadoc, Seafile are able to change user ID of processes
  name: SETUID
categories:
- storage
changelog_url: https://manual.seafile.com/latest/changelog/server-changelog/
date_added: '2026-05-13'
description: Seafile - An open source cloud storage system with privacy preservation
  and teamwork features.
home: https://www.seafile.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/seafile/icons/icon.svg
keywords:
- storage
- cloud
- collaboration
- file-sharing
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: seafile
run_as_context:
- description: Container [mariadb] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [nginx] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [seadoc] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
- description: Container [seafile] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://apps.truenas.com/catalog/seafile_community/
- https://hub.docker.com/r/seafileltd/seafile-mc
- https://manual.seafile.com/
- https://www.seafile.com/
title: Seafile
train: community
version: 1.0.0
