images:
  image:
    repository: kerberos/agent
    tag: "v3.12.8@sha256:58d654db0cc80ca3edf5df67451cd4dc0ac6389d79db23c8b33db822b1914bfb"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  kerberos_container_name: kerberos-agent
  perms_container_name: permissions
  config_container_name: config
