images:
  image:
    repository: drakkan/sftpgo
    tag: "v2.7.6@sha256:1edd28d80de2a008863fbfc58c8ff7db47b1b410bae48d4e6076192337809b11"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  plugins_image:
    repository: drakkan/sftpgo
    tag: "v2.7.6-plugins@sha256:c2f59aab0e6de518e839b3a77e9aae62b290cbd3dc2f0fbdc1ee38a64c8a46e7"

consts:
  sftpgo_container_name: sftpgo
  perms_container_name: permissions
  config_dir_path: /var/lib/sftpgo
  data_dir_path: /srv/sftpgo/data
  backups_dir_path: /srv/sftpgo/backups
  ssl_key_dir: /srv/sftpgo/certs
  ssl_cert_dir: /srv/sftpgo/certs
  ssl_key_name: private.key
  ssl_cert_name: public.crt
