resources:
  limits:
    cpus: 2
    memory: 4096
rotki:
  session_key: catalog-test-only-key-not-for-production-0123456789
  secure_cookie: '1'
  additional_envs:
  - name: LOGLEVEL
    value: info
network:
  web_port:
    bind_mode: published
    port_number: 30921
    host_ips:
    - 127.0.0.1
run_as:
  user: 10001
  group: 10001
storage:
  data:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/rotki-hostpath/data
      create_host_path: true
      auto_permissions: true
  logs:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/rotki-hostpath/logs
      create_host_path: true
      auto_permissions: true
  additional_storage: []
