images:
  image:
    repository: ghcr.io/endless1233214/plainnvr
    tag: 0.1.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  plainnvr_container_name: plainnvr
  perms_container_name: permissions
  data_path: /data
  recordings_path: /recordings
