resources:
  limits:
    cpus: 2.0
    memory: 4096

TZ: America/Los_Angeles

photostructure:
  additional_envs:
    - name: PS_CPU_BUSY_PERCENT
      value: "50"

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30492

run_as:
  user: 568
  group: 568

storage:
  library:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/library
      create_host_path: true
  config:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/config
      create_host_path: true
  cache:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/cache
      create_host_path: true
  additional_storage:
    - type: host_path
      read_only: true
      mount_path: /photos
      host_path_config:
        path: /opt/tests/mnt/photos
        create_host_path: true
