images:
  image:
    repository: ghcr.io/sethforprivacy/simple-monero-wallet-rpc
    tag: "v0.18.5.1@sha256:09ff81f470d6d37811e3fde808c5cd1158a8cd2c42abbfb935b33f26f91e879d"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  perms_container_name: permissions
  monero_wallet_rpc_container_name: monero-wallet-rpc
  run_as_user: 1000
  run_as_group: 1000
  reserved_wallet_flags:
    - --non-interactive
    - --rpc-bind-ip
    - --rpc-bind-port
    - --confirm-external-bind
    - --wallet-dir
    - --daemon-address
    - --trusted-daemon
    - --daemon-ssl
    - --rpc-use-ipv6
