images:
  image:
    repository: ghcr.io/linuxserver/lazylibrarian
    tag: "14830967-ls361@sha256:15b6497dae3447852d9cbef36be5deac6f0e20d5f96ad182fb106037ebd93bbf"

consts:
  lazylibrarian_container_name: lazylibrarian
  internal_web_port: 5299
