app_version: v0.17.3
capabilities: []
categories:
- fitness
changelog_url: https://github.com/CodeWithCJ/SparkyFitness/releases
date_added: '2026-07-09'
description: SparkyFitness is a self-hosted fitness and nutrition tracking application
  with AI coaching, workout logging, and health data integrations.
home: https://github.com/CodeWithCJ/SparkyFitness
host_mounts: []
icon: https://media.sys.truenas.net/apps/sparkyfitness/icons/icon.png
keywords:
- fitness
- nutrition
- health
- tracking
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: sparkyfitness
run_as_context:
- description: Container [frontend] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [server] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/sparkyfitness_community/
- https://github.com/CodeWithCJ/SparkyFitness
title: SparkyFitness
train: community
version: 1.0.3
