images:
  # Frontend image (key must end in 'image')
  image:
    repository: codewithcj/sparkyfitness
    tag: latest
  server_image:
    repository: codewithcj/sparkyfitness_server
    tag: latest
  postgres_image:
    repository: postgres
    tag: 18.3-alpine

consts:
  db_container_name: sparkyfitness-db
  server_container_name: sparkyfitness-server
  frontend_container_name: sparkyfitness-frontend
  perms_container_name: sparkyfitness-perms
  db_user: sparky
  app_db_user: sparky_app
  db_name: sparkyfitness_db
  server_port: 3010
  frontend_port: 80
