images:
  image:
    repository: codewithcj/sparkyfitness
    tag: latest
  server_image:
    repository: codewithcj/sparkyfitness_server
    tag: latest
  postgres_18_image:
    repository: postgres
    tag: 18.3-alpine
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.8
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  sparkyfitness_frontend_container_name: sparkyfitness-frontend
  sparkyfitness_server_container_name: sparkyfitness-server
  sparkyfitness_db_container_name: sparkyfitness-db
  perms_container_name: permissions
  db_user: sparky
  db_name: sparkyfitness
  server_port: 3010
