images:
  image:
    repository: rustdesk/rustdesk-server
    tag: 1.1.15
  pro_image:
    repository: rustdesk/rustdesk-server-pro
    tag: 1.8.2
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  rust_desk_relay_container_name: rust-desk-relay
  perms_container_name: permissions
