resources:
  limits:
    cpus: 2.0
    memory: 4096

nas_doctor:
  scan_interval: "30m"
  timezone: "Etc/UTC"
  mount_docker_socket: true
  mount_host_logs: true
  mount_host_mnt: true
  mount_dev: true
  mount_sys: true
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 30060

ix_volumes:
  data: /opt/tests/mnt/nas-doctor/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
