images:
  image:
    repository: ghcr.io/home-operations/jackett
    tag: "0.24.2756@sha256:0bf0da12bc2ee0afd5afdfbdca56e4866cb4956df1fbb9bafab8264543e1f667"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  jackett_container_name: jackett
  perms_container_name: permissions
