resources:
  limits:
    cpus: 2.0
    memory: 4096

run_as:
  user: 568
  group: 568

languagetool:
  java_xms: "256m"
  java_xmx: "512m"
  pipeline_prewarming: false
  additional_envs: []

network:
  host_network: false
  web_port:
    bind_mode: published
    port_number: 38010

ix_volumes:
  ngrams: /opt/tests/mnt/languagetool/ngrams

storage:
  ngrams:
    type: ix_volume
    ix_volume_config:
      dataset_name: ngrams
      create_host_path: true
  additional_storage: []
