images:
  image:
    repository: ghcr.io/home-operations/qbittorrent
    tag: "5.2.3@sha256:4fcf15b7f265c2c8d7bc2a7e13240a07e0593c326f3cf3b5b9bb69eec5b79299"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  qbittorrent_container_name: qbittorrent
  perms_container_name: permissions
