images:
  image:
    repository: lancachenet/monolithic
    tag: "latest@sha256:37f28b362c939a333f3e4f12aa8ca80604cf75050b2f190d0ad972b2fedce00e"

consts:
  lancache_container_name: lancache-monolithic
