app_version: web-v2.9.2
capabilities: []
categories:
- media
changelog_url: https://gitlab.com/storyteller-platform/storyteller/-/releasess
date_added: '2026-06-24'
description: Storyteller is a self-hosted platform for creating and reading ebooks
  with synced narration.
home: https://storyteller-platform.dev/
host_mounts: []
icon: https://media.sys.truenas.net/apps/storyteller/icons/icon.png
keywords:
- ebooks
lib_version: 2.3.6
lib_version_hash: 5067fd69a830797f96075fe2fe08aa41e2ec08d7c94cf5c6d6256690be7e06ae
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: storyteller
run_as_context:
- description: Container [sonarr] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://gitlab.com/storyteller-platform/storyteller
title: Storyteller
train: community
version: 1.0.0
