#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "handbrake": {
            "additional_envs": config["handbrakeConfig"].get("additionalEnvs", []),
            "dark_mode": config["handbrakeConfig"]["darkMode"],
            "vnc_password": config["handbrakeConfig"]["vncPassword"],
            "secure_connection": config["handbrakeConfig"]["secureConnection"],
        },
        "network": {
            "web_port": config["handbrakeNetwork"]["webPort"],
            "vnc_port": config["handbrakeNetwork"]["vncPort"],
            "host_network": config["handbrakeNetwork"].get("hostNetwork", False),
        },
        "run_as": {
            "user": config["handbrakeID"].get("user", 568),
            "group": config["handbrakeID"].get("group", 568),
        },
        "storage": {
            "config": migrate_storage_item(config["handbrakeStorage"]["config"]),
            "storage": migrate_storage_item(config["handbrakeStorage"]["storage"]),
            "output": migrate_storage_item(config["handbrakeStorage"]["output"]),
            "watch": migrate_storage_item(config["handbrakeStorage"]["watch"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["handbrakeStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
