annotations:
  min_scale_version: 24.10.2.2
app_version: 0.23.1
capabilities: []
categories:
- media
changelog_url: https://github.com/lostb1t/remux/releases
date_added: '2026-08-09'
description: Remux is a self-hosted media server with a Jellyfin-compatible API that
  brings Stremio add-ons, local files, and WebDAV sources together under one roof.
home: https://github.com/lostb1t/remux
host_mounts: []
icon: https://media.sys.truenas.net/apps/remux/icons/icon.png
keywords:
- media
- streaming
- jellyfin
- stremio
- debrid
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: remux
run_as_context:
- description: Container [remux] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://apps.truenas.com/catalog/remux_community/
- https://github.com/lostb1t/remux
title: Remux
train: community
version: 1.0.0
