app_version: 0.23.1
capabilities: []
categories:
- media
changelog_url: https://github.com/lostb1t/remux/releases
date_added: '2026-08-11'
description: Remux is a self-hosted media server with a Jellyfin-compatible API that
  brings Stremio add-ons, local files, and WebDAV sources together under one roof.
home: https://github.com/lostb1t/remux
host_mounts: []
icon: https://media.sys.truenas.net/apps/remux/icons/icon.png
keywords:
- media
- streaming
- jellyfin
- stremio
- debrid
lib_version: 2.3.9
lib_version_hash: a8673072613a14c3b5468881b4912f7bb4c789ed663c142e2e9aa0a12d7ed101
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: remux
run_as_context:
- description: Container [remux] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://apps.truenas.com/catalog/remux_community/
- https://github.com/lostb1t/remux
title: Remux
train: community
version: 1.0.0
