images:
  image:
    repository: chocobozzz/peertube
    tag: v8.1.8
  postgres_17_image:
    repository: postgres
    tag: "17.10-bookworm"
  postgres_18_image:
    repository: postgres
    tag: "18.4-trixie"
  redis_image:
    repository: redis
    tag: "7-alpine"
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.8

consts:
  peertube_container_name: peertube
  postgres_container_name: postgres
  redis_container_name: redis
  perms_container_name: permissions
  db_user: peertube
  db_name: peertube
  web_port: 9000
  rtmp_port: 1935
