images:
  image:
    repository: ghcr.io/timothepoznanski/poznote
    tag: "6.105.0-rootless@sha256:5d135c7f4dedc9931f935cd74e5397a6bb770b8b61fa8aa6d0599980346ed4f6"
  mcp_image:
    repository: ghcr.io/timothepoznanski/poznote-mcp
    tag: "6.105.0@sha256:072ca9770e11d518cefa29096438f71ebbcee5428325ef6c5ac845cfe0663af2"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  poznote_container_name: poznote
  mcp_container_name: mcp
  perms_container_name: permissions
  data_path: /var/www/html/data
  internal_web_port: 8080
  internal_mcp_port: 8045
  run_as_user: 1000
  run_as_group: 1000
  notes_body: |
    Default credentials:
      - Username: `admin_change_me`
      - Password: `admin`
