images:
  image:
    repository: ghcr.io/gramps-project/grampsweb
    tag: "26.9.1@sha256:ac4db1ba963f5d2604e6b9a34be50c5a2c37271699f5a6df93c9492ecc8870e5"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  redis_image:
    repository: valkey/valkey
    tag: "9.1.2@sha256:418652cfb58ef879d4978c33553735d7147016032d5aefaa14c828e611eb9dfd"

consts:
  web_container_name: web
  celery_container_name: celery
  perms_container_name: permissions
  redis_container_name: redis
  internal_web_port: 5000
