#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "navidrome": {
            "additional_envs": config["navidromeConfig"].get("additionalEnvs", []),
            "welcome_message": config["navidromeConfig"]["uiWelcomeMessage"],
            "local_playback": config["navidromeConfig"]["localPlayback"],
        },
        "run_as": {
            "user": config["navidromeRunAs"].get("user", 568),
            "group": config["navidromeRunAs"].get("group", 568),
        },
        "network": {
            "web_port": config["navidromeNetwork"].get("webPort", 32400),
            "host_network": config["navidromeNetwork"].get("hostNetwork", False),
        },
        "storage": {
            "data": migrate_storage_item(config["navidromeStorage"]["data"]),
            "music": migrate_storage_item(config["navidromeStorage"]["music"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["navidromeStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
