app_version: v6.25.0
capabilities: []
categories:
- financial
changelog_url: https://github.com/xmrig/xmrig/blob/master/CHANGELOG.md
date_added: '2026-02-11'
description: A high performance, open source CPU/GPU miner.
home: https://xmrig.com
host_mounts:
- description: Hugepages device
  host_path: /dev/hugepages
- description: CPU device
  host_path: /dev/cpu
icon: https://media.sys.truenas.net/apps/xmrig/icons/icon.png
keywords:
- monero
- cryptocurrency
- blockchain
- privacy
- mining
lib_version: 2.2.2
lib_version_hash: 68a92a0c1f8193b040cc1193f9648e9ec8bd6cef0b45d9d5c0d1a6e641f8146b
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: xmrig
run_as_context:
- description: Container [xmrig] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://xmrig.com
- https://github.com/xmrig/xmrig
- https://github.com/MAGICGrants/xmrig-docker
title: XMRig
train: community
version: 1.0.0
