images:
  image:
    repository: ghcr.io/magicgrants/xmrig-docker
    tag: v6.25.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  perms_container_name: permissions
  xmrig_container_name: xmrig
  run_as_user: 0
  run_as_group: 0
  reserved_flags:
    - --url
    - --threads
    - --cpu-priority
    - --donate-level
    - --user
    - --pass
    - --randomx-1gb-pages
    - --randomx-wrmsr
    - --proxy
    - --config
