images:
  image:
    repository: ghcr.io/sassanix/warracker/main
    tag: "0.10.1.14@sha256:8d5c3abbc2d9b6719ba0035d535a76e448112e4719f79abde51da18cd02e8e3f"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  postgres_17_image:
    repository: postgres
    tag: "17.11-bookworm@sha256:639ab7ceb90e13123085b741fb31ef493fba25463002f6da665352e7b534b652"
  postgres_18_image:
    repository: postgres
    tag: "18.6-trixie@sha256:5a5a84b19854a9ffaa54082c166ff4ec27473a361e496e5ea167f298f2da9722"
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: "1.2.21@sha256:721514696eeb5fedf7818f768e9608d9a3e07ce4551b4c1737faf3f1e6106517"

consts:
  warracker_container_name: warracker
  postgres_container_name: postgres
  perms_container_name: permissions
  # Seems to be hardcoded in some migrations
  db_user: warranty_user
  # Seems to be hardcoded in some migrations
  db_name: warranty_db
