app_version: 1.0.1
capabilities: []
categories:
- networking
changelog_url: https://github.com/germondai/trawl/releases
date_added: '2026-07-22'
description: Self-hosted web scraping engine that bypasses JS challenges and captchas.
  A FlareSolverr and Byparr drop-in replacement.
home: https://trawl.germondai.com/
host_mounts: []
icon: https://media.sys.truenas.net/apps/trawl/icons/icon.svg
keywords:
- networking
- scraper
- captcha
- flaresolverr
- prowlarr
- jackett
lib_version: 2.3.8
lib_version_hash: cd75c897a1e8fef54b5bd00d0d8849f240bc50db2ef650eccc0ee74f3b2b2dc1
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: trawl
run_as_context:
- description: Container [redis] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [trawl] runs as root user and group.
  gid: 0
  group_name: Host group is [root]
  uid: 0
  user_name: Host user is [root]
screenshots: []
sources:
- https://apps.truenas.com/catalog/trawl_community/
- https://github.com/germondai/trawl
title: TRAWL
train: community
version: 1.0.0
