images:
  image:
    repository: cloudreve/cloudreve
    tag: v4
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_17_image:
    repository: paradedb/paradedb
    tag: 0.22.5-pg17
  redis_image:
    repository: redis
    tag: latest
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.4

consts:
  cloudreve_container_name: cloudreve
  perms_container_name: permissions
  postgres_container_name: postgres
  redis_container_name: redis
  data_path: /cloudreve/data
  db_user: cloudreve
  db_name: cloudreve
