images:
  image:
    repository: ghcr.io/bearbinary/omni-infra-provider-truenas
    tag: v0.16.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  omni_container_name: controller
  perms_container_name: permissions
