#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    vols = []
    for item in config["chiaStorage"]["additionalVolumes"]:
        vol = migrate_storage_item(item, include_read_only=True)
        vol["is_plot_dir"] = item.get("isPlotDir", False)
        vols.append(vol)

    new_values = {
        "TZ": config["TZ"],
        "chia": {
            "service": config["chiaConfig"]["service"],
            "farmer_address": config["chiaConfig"].get("farmer_address", ""),
            "farmer_port": config["chiaConfig"].get("farmer_port", 8447),
            "ca": config["chiaConfig"].get("ca", ""),
            "full_node_peer": config["chiaConfig"].get("full_node_peer", ""),
            "additional_envs": config["chiaConfig"].get("additionalEnvs", []),
        },
        "network": {
            "chia_port": config["chiaNetwork"]["chiaPort"],
            "farmer_port": config["chiaNetwork"]["farmerPort"],
        },
        "storage": {
            "data": migrate_storage_item(config["chiaStorage"]["data"]),
            "plots": migrate_storage_item(config["chiaStorage"]["plots"]),
            "additional_storage": vols,
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
