images:
  image:
    repository: ghcr.io/maintainerr/maintainerr
    tag: "3.30.1@sha256:8251a1f0ba5d71acc878846a727fba566ec87cbfbf6a914fb881a5953af53d46"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  maintainerr_container_name: maintainerr
  perms_container_name: permissions
  data_path: /opt/data
