images:
  image:
    repository: ghcr.io/bearbinary/omni-infra-provider-truenas
    tag: "v0.16.2@sha256:51e397ea5cf8f9ddb238a2fbbb96974be9c5fda057f15fd7b42fd35c924063a0"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  omni_container_name: controller
  perms_container_name: permissions
