images:
  image:
    repository: ghcr.io/jlesage/handbrake
    tag: "v26.09.1@sha256:6f3a121e235d34e7299080e8cbac5284060e942fb2b137f777e2521fb7af65ae"

consts:
  handbrake_container_name: handbrake
  output_path: /output
