images:
  image:
    repository: ghcr.io/oss-apps/splitpro
    tag: v2.0.1
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: ghcr.io/oss-apps/postgres
    tag: 18.0-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.2

consts:
  splitpro_container_name: split-pro
  perms_container_name: permissions
  postgres_container_name: postgres
  db_user: splitpro
  db_name: splitpro
