resources:
  limits:
    cpus: 2.0
    memory: 2048

t3monitoring:
  server_name: t3monitoring.example.com
  force_backend_https: true
  db_password: db-t3monitoring-password
  db_root_password: root-db-t3monitoring-password
  encryption_key: test-encryption-key-0123456789abcdef0123456789abcdef01234567
  admin_user: admin
  admin_password: test-admin-password
  install_tool_password: test-install-tool-password
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 8080

ix_volumes:
  fileadmin: /opt/tests/mnt/t3monitoring/fileadmin
  var_log: /opt/tests/mnt/t3monitoring/var_log
  db_data: /opt/tests/mnt/t3monitoring/db_data

storage:
  fileadmin:
    type: ix_volume
    ix_volume_config:
      dataset_name: fileadmin
      create_host_path: true
  var_log:
    type: ix_volume
    ix_volume_config:
      dataset_name: var_log
      create_host_path: true
  db_data:
    type: ix_volume
    ix_volume_config:
      dataset_name: db_data
      create_host_path: true
  additional_storage: []
