app_version: v0.8.4
capabilities: []
categories:
- media
changelog_url: https://github.com/iv-org/invidious/blob/master/CHANGELOG.md
date_added: '2026-05-18'
description: Invidious is an alternative front-end to YouTube
home: https://invidious.io/
host_mounts: []
icon: https://media.sys.truenas.net/apps/invidious/icons/icon.svg
keywords:
- youtube
lib_version: 2.3.5
lib_version_hash: c0d042e3de6350fae9aee546d3c79bc0accf1f2011da89cc1ebff29421aa7fc9
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: glance
run_as_context:
- description: Container [companion] runs as non-root user and group.
  gid: 10001
  group_name: Host group is [unknown (10001)]
  uid: 10001
  user_name: Host user is [unknown (10001)]
- description: Container [invidious] runs as non-root user and group.
  gid: 1000
  group_name: Host group is [unknown (1000)]
  uid: 1000
  user_name: Host user is [unknown (1000)]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://hub.docker.com/r/glanceapp/glance
title: Glance
train: community
version: 1.0.0
