images:
  image:
    repository: glanceapp/glance
    tag: latest
  container_utils_image:
    repository: ghcr.io/truenas/container_utils
    tag: latest

consts:
  app_container_name: glance
  perms_container_name: glance-perms
