images:
  image:
    repository: glanceapp/glance
    tag: v0.8.4
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  yq_image:
    repository: mikefarah/yq
    tag: 4.53.2

consts:
  config_container_name: config
  glance_container_name: glance
  perms_container_name: permissions
  config_path: /app/config
