images:
  image:
    repository: sportarr/sportarr
    tag: 4.0.1020.1100
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  sportarr_container_name: sportarr
  perms_container_name: permissions
