images:
  image:
    repository: ghcr.io/lms-community/lyrionmusicserver
    tag: "9.1.2-stable@sha256:490a72fa6eb696df1c92e9aca68fb4d980aebf5aab8ce0a6b99857b74986329f"

consts:
  lms_container_name: lms
  reserved_flags:
    - --httpport
    - --cliport
