#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    # "image" is now only used to track the app_version, keep existing installs on their version
    if values["postgres"]["image_selector"] == "image":
        values["postgres"]["image_selector"] = "v17_image"
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
