app_version: '0.101'
capabilities: []
categories:
- productivity
changelog_url: https://github.com/bbernhard/signal-cli-rest-api/releases
date_added: '2025-11-14'
description: This project creates a small dockerized REST API around signal-cli.
home: https://github.com/bbernhard/signal-cli-rest-api
host_mounts: []
icon: https://media.sys.truenas.net/apps/signal-cli-rest-api/icons/icon.svg
keywords:
- signal
lib_version: 2.3.15
lib_version_hash: 418b1697e018a564438ced4d735f4ced3ea16cc9fa74971a6040e769c80a66e5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: signal-cli-rest-api
run_as_context:
- description: Container [signal-cli-rest-api] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/signal-cli-rest-api_community/
- https://github.com/bbernhard/signal-cli-rest-api
- https://hub.docker.com/r/bbernhard/signal-cli-rest-api
title: Signal CLI REST API
train: community
version: 1.1.12
