images:
  image:
    repository: ghcr.io/we-promise/sure
    tag: 0.7.0
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2
  postgres_18_image:
    repository: postgres
    tag: 18.3-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.7
  redis_image:
    repository: valkey/valkey
    tag: 9.0.3

consts:
  web_container_name: web
  worker_container_name: worker
  postgres_container_name: postgres
  redis_container_name: redis
  perms_container_name: permissions
  db_user: sure
  db_name: sure

  run_as_user: 1000
  run_as_group: 1000
