images:
  image:
    repository: ghcr.io/wolveix/satisfactory-server
    tag: "v1.9.10@sha256:e0f2f8c9759875c97add050d3a344167b71cb41bef68e85771f1ea8cc8c00301"

consts:
  satisfactory_container_name: satisfactory
