images:
  image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.5.0-java21
  j21_alpine_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.5.0-java21-alpine
  j25_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.5.0-java25
  j8_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.5.0-java8
  j11_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.5.0-java11
  j17_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.5.0-java17

  # Deprecated images
  j21_g_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.1.0-java21-graalvm
  j25_g_image:
    repository: ghcr.io/itzg/minecraft-server
    tag: 2026.1.0-java25-graalvm

consts:
  minecraft_container_name: minecraft
