images:
  image:
    repository: itzg/minecraft-server
    tag: 2026.3.1-java21
  j21_g_image:
    repository: itzg/minecraft-server
    tag: 2026.1.0-java21-graalvm
  j21_alpine_image:
    repository: itzg/minecraft-server
    tag: 2026.3.1-java21-alpine
  j25_image:
    repository: itzg/minecraft-server
    tag: 2026.3.1-java25
  j25_g_image:
    repository: itzg/minecraft-server
    tag: 2026.1.0-java25-graalvm
  j8_image:
    repository: itzg/minecraft-server
    tag: 2026.3.1-java8
  j11_image:
    repository: itzg/minecraft-server
    tag: 2026.3.1-java11
  j17_image:
    repository: itzg/minecraft-server
    tag: 2026.3.1-java17

consts:
  minecraft_container_name: minecraft
