images:
  image:
    repository: ghcr.io/continuwuity/continuwuity
    tag: "v26.9.1@sha256:c9c62bc5c0a641f3f713945c701b069c7bc30d2612b54d4a5de80a5be19d5420"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  continuwuity_container_name: continuwuity
  perms_container_name: permissions
  database_path: /var/lib/continuwuity
