app_version: 0.7.2
capabilities: []
categories:
- health
changelog_url: https://github.com/Maxren2/ebbwell/releases
date_added: '2026-10-02'
description: Private, self-hosted period tracker and ovulation estimator with symptothermal
  rules, reminders, app lock, partner sharing, single sign-on and local accounts.
home: https://github.com/Maxren2/ebbwell
host_mounts: []
icon: https://media.sys.truenas.net/apps/ebbwell/icons/icon.png
keywords:
- health
- period
- cycle
- fertility
- privacy
lib_version: 2.3.15
lib_version_hash: 418b1697e018a564438ced4d735f4ced3ea16cc9fa74971a6040e769c80a66e5
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: ebbwell
run_as_context:
- description: Container [ebbwell] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://apps.truenas.com/catalog/ebbwell_community/
- https://github.com/Maxren2/ebbwell
- https://github.com/Maxren2/ebbwell/pkgs/container/ebbwell
title: Ebbwell
train: community
version: 1.0.1
