#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.dns_config import migrate_dns_config
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "photoprism": {
            "admin_password": config["photoprismConfig"].get("password", ""),
            "site_url": config["photoprismConfig"].get("siteURL", ""),
            "public": config["photoprismConfig"]["public"],
            "additional_envs": config["photoprismConfig"].get("additionalEnvs", []),
        },
        "run_as": {
            "user": config["photoprismID"].get("user", 568),
            "group": config["photoprismID"].get("group", 568),
        },
        "network": {
            "host_network": config["photoprismNetwork"].get("hostNetwork", False),
            "web_port": config["photoprismNetwork"].get("webPort", 32400),
            "certificate_id": config["photoprismNetwork"].get("certificateID", None),
            "dns_opts": migrate_dns_config(config["podOptions"].get("dnsConfig", {})),
        },
        "storage": {
            "import": migrate_storage_item(config["photoprismStorage"]["import"]),
            "storage": migrate_storage_item(config["photoprismStorage"]["storage"]),
            "originals": migrate_storage_item(config["photoprismStorage"]["originals"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["photoprismStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(
            config["resources"], config["photoprismGPU"], values.get("gpu_choices", {})
        ),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
