resources:
  limits:
    cpus: 2.0
    memory: 4096

archivebox:
  base_url: http://localhost:5797
  server_security_mode: safe-onedomain-nojsreplay
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 5797

run_as:
  user: 911
  group: 911

storage:
  data:
    type: host_path
    host_path_config:
      path: /opt/tests/mnt/archivebox/host-data
      create_host_path: true
      acl_enable: false
  additional_storage: []
