resources:
  limits:
    cpus: 2.0
    memory: 4096

open_terminal:
  terminal_api_key: some-secret
  additional_envs: []

network:
  api_port:
    bind_mode: published
    port_number: 8080
  host_network: false

run_as:
  user: 568
  group: 568

ix_volumes:
  data: /opt/tests/mnt/open-terminal/data

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  additional_storage: []
