app_version: 3.0.0
capabilities: []
categories:
- monitoring
changelog_url: https://github.com/teslamate-org/teslamate/releases
date_added: '2026-04-08'
description: A self-hosted data logger for your Tesla
home: https://docs.teslamate.org/
host_mounts: []
icon: https://media.sys.truenas.net/apps/teslamate/icons/icon.svg
keywords:
- tesla
- ev
- logging
- grafana
lib_version: 2.3.1
lib_version_hash: 561017357f22eafbedca2a97f747325cb83149fe1b5f765a2fbda71ab77d96ed
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: teslamate
run_as_context:
- description: Container [api] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
- description: Container [teslamate] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
screenshots: []
sources:
- https://github.com/teslamate-org/teslamate
- https://hub.docker.com/r/teslamate/teslamate
title: TeslaMate
train: community
version: 1.0.0
