images:
  image:
    repository: ghcr.io/golmenero/ratelog
    tag: 0.1.0
  postgres_image:
    repository: postgres
    tag: 17.7-bookworm
  postgres_upgrade_image:
    repository: postgres
    tag: 16.11-bookworm
  container_utils_image:
    repository: ghcr.io/truenas/container_utils
    tag: latest

consts:
  app_container_name: ratelog
  perms_container_name: ratelog-perms
  db_user: ratelog
  db_name: ratelog