images:
  image:
    repository: ghcr.io/ulsklyc/yuvomi
    tag: 1.40.7
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  yuvomi_container_name: yuvomi
  perms_container_name: permissions
