#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["network"]["manage_http_port"] = {
        "port_number": values["network"]["manage_http_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["manage_https_port"] = {
        "port_number": values["network"]["manage_https_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["portal_http_port"] = {
        "port_number": values["network"]["portal_http_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["portal_https_port"] = {
        "port_number": values["network"]["portal_https_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["app_discovery_port"] = {
        "port_number": values["network"]["app_discovery_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["discovery_port"] = {
        "port_number": values["network"]["discovery_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["manager_v1_port"] = {
        "port_number": values["network"]["manager_v1_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["manager_v2_port"] = {
        "port_number": values["network"]["manager_v2_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["adopt_v1_port"] = {
        "port_number": values["network"]["adopt_v1_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["upgrade_v1_port"] = {
        "port_number": values["network"]["upgrade_v1_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["transfer_v2_port"] = {
        "port_number": values["network"]["transfer_v2_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["rtty_port"] = {
        "port_number": values["network"]["rtty_port"],
        "bind_mode": "published",
        "host_ips": [],
    }
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
