images:
  image:
    repository: ghcr.io/immichframe/immichframe
    tag: "v1.0.39.0@sha256:b4bd2ac6ec75c0117a24bd627dc0b449d485ac87ec3a410c73d5db05a4bbfcaf"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  frame_container_name: frame
  perms_container_name: permissions
