resources:
  limits:
    cpus: 2.0
    memory: 4096

wallabag:
  domain_name: "http://localhost:30430"
  additional_envs: []

network:
  web_port:
    bind_mode: published
    port_number: 30430

ix_volumes:
  data: /opt/tests/mnt/wallabag/data
  images: /opt/tests/mnt/wallabag/images

storage:
  data:
    type: ix_volume
    ix_volume_config:
      dataset_name: data
      create_host_path: true
  images:
    type: ix_volume
    ix_volume_config:
      dataset_name: images
      create_host_path: true
