images:
  image:
    repository: adguard/adguardhome
    tag: "v0.107.79@sha256:aba9e3bf0613be3ba3755e1fc311b126e2c24bec25e18b6483894a88283074f0"

consts:
  adguard_container_name: adguard
  config_path: /opt/adguardhome/conf
  work_path: /opt/adguardhome/work
  notes_body: |
    After initial setup, you need to stop and start the app from
    the TrueNAS SCALE UI for the configuration to take effect.
