#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config.get("TZ", "Etc/UTC"),
        "recyclarr": {
            "additional_envs": config["recyclarrConfig"].get("additionalEnvs", []),
            "create_config": config["recyclarrConfig"].get("createConfig", False),
            "cron_schedule": config["recyclarrConfig"].get("cronSchedule", "@daily"),
        },
        "run_as": {
            "user": config["recyclarrRunAs"].get("user", 568),
            "group": config["recyclarrRunAs"].get("group", 568),
        },
        "network": {
            "host_network": False,
        },
        "storage": {
            "config": migrate_storage_item(config["recyclarrStorage"]["config"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["recyclarrStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
