{% set tpl = ix_lib.base.render.Render(values) %}

{% set c1 = tpl.add_container(values.consts.app_container_name, "image") %}
{% do c1.healthcheck.set_test("curl", {"port": values.consts.internal_web_port}) %}

{% do c1.environment.add_env("PORT", values.consts.internal_web_port) %}
{% do c1.environment.add_env("STORAGE_DIR", values.consts.config_dir) %}
{% do c1.environment.add_env("SPOTIFY_API_REDIRECT_URI", "https://jjdenhertog.github.io/spotify-to-plex/callback.html") %}
{% do c1.environment.add_env("PLEX_APP_ID", "eXf+f9ktw3CZ8i45OY468WxriOCtoFxuNPzVeDcAwfw=") %}
{% do c1.environment.add_env("SPOTIFY_SCRAPER_URL", "http://localhost:3020") %}
{% do c1.environment.add_env("ENCRYPTION_KEY", values.spotify_to_plex.encryption_key) %}
{% do c1.environment.add_env("SPOTIFY_API_CLIENT_ID", values.spotify_to_plex.spotify_api_client_id) %}
{% do c1.environment.add_env("SPOTIFY_API_CLIENT_SECRET", values.spotify_to_plex.spotify_api_client_secret) %}
{% do c1.environment.add_user_envs(values.spotify_to_plex.additional_envs) %}

{% do c1.add_port(values.network.web_port, {"container_port": values.consts.internal_web_port}) %}

{% do c1.add_storage(values.consts.config_dir, values.storage.config) %}
{% for store in values.storage.additional_storage %}
  {% do c1.add_storage(store.mount_path, store) %}
{% endfor %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
