{% set tpl = ix_lib.base.render.Render(values) %}
{% set app = tpl.add_container(values.consts.app_container_name, "image") %}

{% do app.healthcheck.set_test("curl", {"port": values.consts.internal_web_port, "path": "/"}) %}

{% do app.environment.add_env("PORT", values.consts.internal_web_port) %}
{% do app.environment.add_env("SPOTIFY_API_CLIENT_ID", values.spotify_to_plex.spotify_api_client_id) %}
{% do app.environment.add_env("SPOTIFY_API_CLIENT_SECRET", values.spotify_to_plex.spotify_api_client_secret) %}
{% do app.environment.add_env("ENCRYPTION_KEY", values.spotify_to_plex.encryption_key) %}
{% do app.environment.add_env("SPOTIFY_API_REDIRECT_URI", values.consts.spotify_api_redirect_uri) %}
{% do app.environment.add_env("PLEX_APP_ID", values.consts.plex_app_id) %}
{% do app.environment.add_env("STORAGE_DIR", "/app/config") %}
{% do app.environment.add_env("SPOTIFY_SCRAPER_URL", "http://localhost:3020") %}
{% do app.environment.add_user_envs(values.spotify_to_plex.additional_envs) %}

{% do app.add_port(values.network.web_port, {"container_port": values.consts.internal_web_port}) %}

{% do app.add_storage("/app/config", values.storage.config) %}
{% for store in values.storage.additional_storage %}
  {% do app.add_storage(store.mount_path, store) %}
{% endfor %}

{% do tpl.portals.add(values.network.web_port) %}

{{ tpl.render() | tojson }}
