images:
  image:
    repository: dbeaver/cloudbeaver
    tag: "26.2.1@sha256:34b078483dac9502ed6a718a68c54368d55dd0abbc7b392d6e78b90f6a9ec3f6"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  cloudbeaver_container_name: cloudbeaver
  perms_container_name: permissions
  run_as_user: 8978
  run_as_group: 8978
