images:
  image:
    repository: ghcr.io/linuxserver/speedtest-tracker
    tag: "1.15.0@sha256:dc439a8bbadd3d0d4a4af4ee64bf30a6db9ced425c00ac12ea2ff04e15669ed1"

consts:
  speedtest_container_name: speedtest-tracker
  ssl_key_path: /config/keys/cert.key
  ssl_cert_path: /config/keys/cert.crt
  notes_body: |
    Default credentials are:
    - Username: `admin@example.com`
    - Password: `password`
