images:
  image:
    repository: ghcr.io/linuxserver/calibre
    tag: "9.16.0@sha256:4b1673b28f18c170e8d6c48c791e67520df44dc4f9b9e8f63fef21d23910abab"

consts:
  calibre_container_name: calibre
  config_path: /config
  internal_web_port: 8081
  no_auth_warning: |
    ⚠️ Calibre is running without authentication.
    See the potential security risks: https://info.linuxserver.io/issues/2024-10-06-securing-kasm/
