images:
  image:
    repository: ghcr.io/golmenero/ratelog
    tag: v1.6.2
  postgres_18_image:
    repository: postgres
    tag: 18.6-trixie
  postgres_upgrade_image:
    repository: ixsystems/postgres-upgrade
    tag: 1.2.16
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  ratelog_container_name: ratelog
  postgres_container_name: postgres
  perms_container_name: permissions
  db_user: ratelog
  db_name: ratelog
