images:
  image:
    repository: ghcr.io/uurdemir/agent-hub-ui
    tag: "0.4.0@sha256:8937b22be93595d12a58ed3f7acfe86f1055ae6ec9f644466957789a1526180a"

consts:
  agent_hub_container_name: agent-hub
  ssl_cert_path: /etc/certs/agent-hub/tls.crt
  ssl_key_path: /etc/certs/agent-hub/tls.key
