images:
  image:
    repository: ghcr.io/moghtech/komodo-core
    tag: "2.3.3@sha256:bca73d0eee143066228fb9b80c38a5a2726e573ad2758f7aa92b5c91a8aef1c7"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"
  periphery_image:
    repository: ghcr.io/moghtech/komodo-periphery
    tag: "2.3.3@sha256:fa3f1a641a265216066676950d5eecdf506955a7bafe2f01996135ae93115cd5"
  mongo_image:
    repository: mongo
    tag: "8.3.11@sha256:5d7043a4ffe02b9ed1b6e0bab057546981af5ca0a79107e9c461e49bc44c0a7b"

consts:
  core_container_name: core
  periphery_container_name: periphery
  mongo_container_name: mongo
  perms_container_name: permissions
  db_user: komodo
  db_name: komodo
  internal_periphery_port: 8120
  syncs_directory: /syncs
