images:
  image:
    repository: ghcr.io/garethgeorge/backrest
    tag: "v1.14.1@sha256:b852979754281026230cc69fb11428e6d57c9a97784ab4a444ffc7934c53a215"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  backrest_container_name: backrest
  perms_container_name: permissions

  data_dir_path: /data
  cache_dir_path: /cache
  config_dir_path: /config
  config_file_path: /config/config.json
