images:
  image:
    repository: ghcr.io/linuxserver/calibre
    tag: "9.15.0@sha256:84d3e30e0f0b3bf74260ff3312d4443121f5359387e50691a49a86ea219ed347"

consts:
  calibre_container_name: calibre
  config_path: /config
  internal_web_port: 8081
  no_auth_warning: |
    ⚠️ Calibre is running without authentication.
    See the potential security risks: https://info.linuxserver.io/issues/2024-10-06-securing-kasm/
