#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item
from migration_helpers.kubernetes_secrets import get_value_from_secret


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    k8s_secrets = values.get("release_secrets", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "n8n": {
            "additional_envs": config["n8nConfig"].get("additionalEnvs", []),
            "db_password": get_value_from_secret(
                k8s_secrets, "postgres-creds", "POSTGRES_PASSWORD"
            ),
            "redis_password": get_value_from_secret(
                k8s_secrets, "redis-creds", "REDIS_PASSWORD"
            ),
            "encryption_key": get_value_from_secret(
                k8s_secrets, "n8n-creds", "N8N_ENCRYPTION_KEY"
            ),
            "web_host": config["n8nConfig"]["webHost"],
        },
        "run_as": {
            "user": config["n8nRunAs"].get("user", 568),
            "group": config["n8nRunAs"].get("group", 568),
        },
        "network": {
            "web_port": config["n8nNetwork"].get("webPort", 32400),
            "certificate_id": config["n8nNetwork"].get("certificateID", None),
        },
        "storage": {
            "data": migrate_storage_item(config["n8nStorage"]["data"]),
            "postgres_data": migrate_storage_item(config["n8nStorage"]["pgData"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["n8nStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
