#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    if "run_as" not in values:
        # If run_as is not present, set it to 1000
        # as this is how it was running before
        values.update({"run_as": {"user": 1000, "group": 1000}})
    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
