#!/usr/bin/python3

import os
import sys
import yaml


def migrate(values):
    values["network"]["web_port"] = {
        "port_number": values["network"].get("web_port", 30058),
        "bind_mode": "published",
        "host_ips": [],
    }
    values["network"]["no_auth_port"] = {
        "port_number": values["network"].get("no_auth_port", 30059),
        "bind_mode": "published" if values["network"].get("enable_no_auth") else "",
        "host_ips": [],
    }
    values["network"].pop("enable_no_auth", None)

    values["network"]["rtsp_port"] = {
        "port_number": values["network"].get("rtsp_port", 30060),
        "bind_mode": "published" if values["network"].get("enable_rtsp") else "",
        "host_ips": [],
    }
    values["network"].pop("enable_rtsp", None)

    values["network"]["go2rtc_port"] = {
        "port_number": values["network"].get("go2rtc_port", 30062),
        "bind_mode": "published" if values["network"].get("enable_go2rtc") else "",
        "host_ips": [],
    }
    values["network"].pop("enable_go2rtc", None)

    values["network"]["webrtc_port"] = {
        "port_number": values["network"].get("webrtc_port", 30061),
        "bind_mode": "published" if values["network"].get("enable_webrtc") else "",
        "host_ips": [],
    }
    values["network"].pop("enable_webrtc", None)

    return values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
