images:
  image:
    repository: automaticrippingmachine/automatic-ripping-machine
    tag: "2.24.4@sha256:b1d0d5773f450d80dc8dbedc5976576a7b10762837b031946e3f126908d78a43"
  container_utils_image:
    repository: ixsystems/container-utils
    tag: "1.0.2@sha256:46eba20714c1cc6784f60e245c32c33a2d9f616e47d804694a9854248c89a992"

consts:
  arm_container_name: automatic-ripping-machine
  perms_container_name: permissions
  internal_web_port: 8080
