#!/usr/bin/python3

import os
import sys
import yaml

from migration_helpers.resources import migrate_resources
from migration_helpers.storage import migrate_storage_item


def migrate(values):
    config = values.get("helm_secret", {}).get("config", {})
    if not config:
        raise ValueError("No config found in values")

    new_values = {
        "TZ": config["TZ"],
        "jenkins": {
            "additional_envs": config["jenkinsConfig"].get("additionalEnvs", []),
            "additional_java_opts": config["jenkinsConfig"].get("jenkinsJavaOpts", []),
            "additional_opts": config["jenkinsConfig"].get("jenkinsOpts", []),
        },
        "network": {
            "web_port": config["jenkinsNetwork"]["webPort"],
            "enable_agent": config["jenkinsNetwork"]["agent"],
            "agent_port": config["jenkinsNetwork"].get("agentPort", 50000),
            "certificate_id": config["jenkinsNetwork"].get("certificateID"),
            "host_network": config["jenkinsNetwork"].get("hostNetwork", False),
        },
        "storage": {
            "home": migrate_storage_item(config["jenkinsStorage"]["home"]),
            "additional_storage": [
                migrate_storage_item(item, include_read_only=True)
                for item in config["jenkinsStorage"]["additionalStorages"]
            ],
        },
        "resources": migrate_resources(config["resources"]),
    }

    return new_values


if __name__ == "__main__":
    if len(sys.argv) != 2:
        exit(1)

    if os.path.exists(sys.argv[1]):
        with open(sys.argv[1], "r") as f:
            print(yaml.dump(migrate(yaml.safe_load(f.read()))))
