app_version: 4.0.0
capabilities: []
categories:
- media
changelog_url: https://github.com/fliks-app/fliks/releases
date_added: '2026-09-07'
description: Fliks is a self-hosted media manager and streaming server for movies
  and TV shows.
home: https://github.com/fliks-app/fliks
host_mounts: []
icon: https://media.sys.truenas.net/apps/fliks/icons/icon.svg
keywords:
- media
- movies
- series
- tv
- streaming
lib_version: 2.3.11
lib_version_hash: 874636814efb275e5276ea9d709b7cd665fed42bb1d50328e853d9253a2e1229
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: fliks
run_as_context:
- description: Container [fliks] can run as any non-root user and group.
  gid: 568
  group_name: Host group is [apps]
  uid: 568
  user_name: Host user is [apps]
- description: Container [postgres] runs as non-root user and group.
  gid: 999
  group_name: Host group is [docker]
  uid: 999
  user_name: Host user is [netdata]
screenshots: []
sources:
- https://apps.truenas.com/catalog/fliks_community/
- https://github.com/fliks-app/fliks
title: Fliks
train: community
version: 1.1.0
